import React, { useState, useEffect, useMemo, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
    Search,
    Loader2,
    XCircle,
    Database,
    BarChart3,
    Eye,
    EyeOff,
    Users,
    Shield,
    TrendingUp,
    Activity,
    Globe,
    Lightbulb,
    ShoppingCart,
    Layers,
    PieChart,
    DollarSign,
    Megaphone,
    FolderOpen,
    FileText,
    Package,
    Beaker,
    GitBranch,
    Calendar,
    Download,
    Radio,
    Star,
    Truck,
    BookOpen,
    Zap,
    CheckCircle2,
    Lock
} from "lucide-react";
import axios from "axios";
import { useAuth } from "../../../utils/AuthContext";

const API_BASE = import.meta.env.VITE_API_URL
    ? `${import.meta.env.VITE_API_URL}/api`
    : "/api";

// Switch UI component
const Switch = ({ checked, onChange }) => (
    <button
        type="button"
        role="switch"
        aria-checked={checked}
        onClick={(e) => {
            e.stopPropagation();
            onChange();
        }}
        className={`relative inline-flex h-5 w-9 shrink-0 cursor-pointer items-center rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none ${checked ? 'bg-indigo-600' : 'bg-slate-200'
            }`}
    >
        <span
            className={`pointer-events-none inline-block h-4 w-4 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out ${checked ? 'translate-x-4' : 'translate-x-0'
                }`}
        />
    </button>
);

// Map tab names to icons for visual identification
const TAB_ICON_MAP = {
    "Business Overview": Activity,
    "India Overview": Globe,
    "Availability Analysis": ShoppingCart,
    "Market Coverage": Layers,
    "Visibility Analysis": Eye,
    "Market Share": PieChart,
    "Sales Data": TrendingUp,
    "Pricing Analysis": DollarSign,
    "Performance Marketing": Megaphone,
    "Portfolio Analysis": FolderOpen,
    "Content Analysis": FileText,
    "Inventory Analysis": Package,
    "Play it Yourself": Beaker,
    "Category RCA": GitBranch,
    "Scheduled Reports": Calendar,
    "Download Report": Download,
    "Ad Auto": Radio,
    "Rating": Star,
    "Supply": Truck,
    "PDS Score": BarChart3,
};

// Gradient color pairs for KPI cards
const CARD_GRADIENTS = [
    { from: "#6366f1", to: "#818cf8" }, // Indigo
    { from: "#8b5cf6", to: "#a78bfa" }, // Violet
    { from: "#3b82f6", to: "#60a5fa" }, // Blue
    { from: "#06b6d4", to: "#22d3ee" }, // Cyan
    { from: "#10b981", to: "#34d399" }, // Emerald
    { from: "#f59e0b", to: "#fbbf24" }, // Amber
    { from: "#ef4444", to: "#f87171" }, // Red
    { from: "#ec4899", to: "#f472b6" }, // Pink
    { from: "#14b8a6", to: "#2dd4bf" }, // Teal
    { from: "#f97316", to: "#fb923c" }, // Orange
    { from: "#84cc16", to: "#a3e635" }, // Lime
    { from: "#7c3aed", to: "#a78bfa" }, // Purple
];

// The canonical list of tabs (must match RolesPermissions.jsx)
const tabsList = [
    "Business Overview", "India Overview", "Availability Analysis",
    "Market Coverage", "Visibility Analysis", "Market Share", "Sales Data",
    "Pricing Analysis", "Performance Marketing", "Portfolio Analysis", "Content Analysis",
    "Inventory Analysis", "Play it Yourself", "Category RCA",
    "Scheduled Reports", "Download Report", "Ad Auto", "Rating", "Supply", "PDS Score",
    "Insights"
];

// Comprehensive KPI metrics mapped to each page/tab
const PAGE_KPIS_MAP = {
    "Business Overview": [
        { id: "offtake", label: "Offtakes", val: "₹12.4 Cr", delta: "+4.2%", desc: "sum(Offtakes)", tooltip: "The total sales value generated by a product or brand over a specified period." },
        { id: "availability", label: "Availability", val: "89.4%", delta: "+1.8%", desc: "% stock availability", tooltip: "The proportion of stores or locations where a product is available for purchase." },
        { id: "share_of_search", label: "Share of Search", val: "24.5%", delta: "-0.5%", desc: "Top 10 Rank Positions", tooltip: "Share of Search is calculated based on Top 10 rank positions." },
        { id: "market_share", label: "Market Share", val: "18.2%", delta: "+0.9%", desc: "% brand share of category", tooltip: "The percentage of total category sales contributed by a brand." },
        { id: "promo", label: "Promo", val: "12.3%", delta: "+2.1%", desc: "% discounted items sold", tooltip: "A price reduction or special offer applied to a product to encourage purchase." },
        { id: "inorganic_sales", label: "Inorganic Sales", val: "₹19.12 Lac", delta: "+17.0%", desc: "Advertising-driven sales revenue", tooltip: "Sales generated through paid advertising channels." },
        { id: "conversion", label: "Conversion", val: "25.5%", delta: "+31.0%", desc: "Overall conversion rate", tooltip: "Conversion rate measuring order completions relative to clicks." },
        { id: "roas", label: "ROAS (Return on Ad Spend)", val: "1.89", delta: "+18.1%", desc: "Return on Ad Spend", tooltip: "Advertising efficiency metric (revenue generated / ad spend)." },
        { id: "orders", label: "Orders", val: "5.9K", delta: "+17.7%", desc: "Ad Quantity Sold", tooltip: "Quantity of products sold directly driven by paid advertising campaigns." },
        { id: "spend", label: "Spend", val: "₹10.12 Lac", delta: "+5.1%", desc: "Total spend incurred", tooltip: "Total spend incurred across all running ad networks." },
        { id: "category_size", label: "Category Size", val: "₹45.2 Cr", delta: "+8.4%", desc: "Total size of the category", tooltip: "The total sales value of all products within a specific category over a defined period." },
        { id: "sponsored_sos", label: "Sponsored SOS", val: "17.6%", delta: "-8.6%", desc: "Paid search visibility", tooltip: "The proportion of a brand's product visibility within sponsored or paid search results." },
        { id: "organic_sos", label: "Organic SOS", val: "20.7%", delta: "+19.5%", desc: "Unpaid search visibility", tooltip: "The proportion of a brand's product visibility within organic (non-paid) search results." },
        { id: "cpm", label: "CPM (Cost per Mille)", val: "₹142", delta: "-2.4%", desc: "Cost per 1000 impressions", tooltip: "The cost incurred to generate one thousand impressions." },
        { id: "cpc", label: "CPC (Cost per Click)", val: "₹4.12", delta: "-3.2%", desc: "Cost per click", tooltip: "The cost incurred for each user click on an advertisement." },
        { id: "impressions", label: "Impressions", val: "1.2M", delta: "+14.2%", desc: "Total ad views", tooltip: "The total number of times a product or advertisement is displayed to users." },
        { id: "clicks", label: "Clicks", val: "42K", delta: "+8.9%", desc: "Total ad clicks", tooltip: "The total number of times users interact with a product or advertisement by clicking on it." },
        { id: "ctr", label: "CTR (Click-Through Rate)", val: "3.5%", delta: "+0.4%", desc: "Clicks / Impressions", tooltip: "The percentage of impressions that result in user clicks." },
        { id: "cost_per_click", label: "Cost per Click (CPC)", val: "₹4.12", delta: "-3.2%", desc: "Average cost paid", tooltip: "The average cost paid for each click on an advertisement." }
    ],
    "India Overview": [
        { id: "osa", label: "OSA (On-Shelf Availability)", val: "89.4%", delta: "+1.8%", desc: "On-shelf stock availability percentage", tooltip: "Measures on-shelf stock availability percentage." },
        { id: "listing_pct", label: "Listing %", val: "92.4%", delta: "+1.2%", desc: "% of total possible SKUs listed", tooltip: "% of total possible SKUs that are listed on the platform/store." },
        { id: "market_share", label: "Market Share", val: "22.1%", delta: "+1.4%", desc: "The percentage of total category sales", tooltip: "The percentage of total category sales contributed by a brand." },
        { id: "sales", label: "Sales", val: "₹8.4 Cr", delta: "+6.1%", desc: "Total sales value generated", tooltip: "The total sales value generated by a product or brand over a specified period." },
        { id: "orders", label: "Orders", val: "42.1K", delta: "+9.2%", desc: "Total completed transactions", tooltip: "The total number of completed purchase transactions within a given period." }
    ],

    "Availability Analysis": [
        { id: "osa", label: "OSA (On-Shelf Availability)", val: "89.4%", delta: "+1.8%", desc: "On-shelf stock availability percentage", tooltip: "Measures on-shelf stock availability percentage." },
        { id: "stock_availability", label: "Stock Availability", val: "92.1%", delta: "+1.5%", desc: "Proportion of stores available", tooltip: "The proportion of stores or locations where a product is available for purchase at a given time." },
        { id: "doi", label: "Days of Inventory (DOI)", val: "14.2 Days", delta: "-1.5", desc: "Days current inventory is expected to last", tooltip: "The number of days current inventory is expected to last based on the recent sales trend (last 30 days)." },
        { id: "metro_city_stock_availability", label: "Metro City Stock Availability", val: "78.5%", delta: "-2.0%", desc: "Stock availability in metro cities", tooltip: "The proportion of stores or locations where a product is available for purchase at a given time for metro cities." },
        { id: "psl", label: "PSL (Potential Sales Loss)", val: "₹4.2 Lac", delta: "-12%", desc: "Estimated sales loss due to unavailability", tooltip: "The estimated sales loss due to unavailability, derived by comparing actual sales with expected sales adjusted for availability (OSA)." },
        { id: "soh", label: "SOH (Stock on Hand)", val: "45K units", delta: "+5.8%", desc: "Total inventory available", tooltip: "Total inventory available at a given point in time." },
        { id: "wt_osa_pct", label: "Wt. OSA% (Weighted On-Shelf Availability)", val: "89.4%", delta: "+1.8%", desc: "Weighted availability score", tooltip: "Measures product availability weighted by its importance (e.g., sales contribution or store weight)." },
        { id: "offtake_share", label: "Offtake Share", val: "18.2%", delta: "+0.9%", desc: "Category contribution to total sales", tooltip: "Product/Category's contribution to total sales." }
    ],
    "Market Coverage": [
        { id: "stock_availability", label: "Stock Availability", val: "92.1%", delta: "+1.5%", desc: "Proportion of stores available", tooltip: "The proportion of stores or locations where a product is available for purchase at a given time." },
        { id: "metro_city_stock_availability", label: "Metro City Stock Availability", val: "78.5%", delta: "-2.0%", desc: "Availability in metro cities", tooltip: "The proportion of stores or locations where a product is available for purchase at a given time for metro cities." },
        { id: "osa", label: "OSA", val: "89.4%", delta: "+1.8%", desc: "On-Shelf Availability", tooltip: "On-shelf stock availability percentage." },
        { id: "market_share", label: "Market Share %", val: "18.2%", delta: "+0.9%", desc: "% brand share of category", tooltip: "The percentage of total category sales contributed by a brand." },
        { id: "overall_share_of_visibility", label: "Overall Share of Visibility", val: "24.5%", delta: "-0.5%", desc: "Overall search visibility", tooltip: "The proportion of a brand's product visibility within the top search results, including both organic and sponsored placements." },
        { id: "paid_share_of_visibility", label: "Paid Share of Visibility", val: "17.6%", delta: "-8.6%", desc: "Paid search visibility", tooltip: "The proportion of a brand's product visibility within sponsored or paid placements in search results." }
    ],
    "Visibility Analysis": [
        { id: "Share of Shelf_access", label: "Share of Shelf - Page Access", val: "Active", delta: "0", desc: "Share of Shelf tab access", tooltip: "Gives access to the Share of Shelf view." },
        { id: "Share of Shelf_overall_sos", label: "Share of Shelf - Overall SOS", val: "19.6%", delta: "+4.3%", desc: "Overall search share of shelf", tooltip: "The proportion of a brand's product visibility within the top search results, including both organic and sponsored placements." },
        { id: "Share of Shelf_sponsored_sos", label: "Share of Shelf - Sponsored SOS", val: "17.6%", delta: "-8.6%", desc: "Paid search visibility", tooltip: "The proportion of a brand's product visibility within sponsored or paid placements in search results." },
        { id: "Share of Shelf_organic_sos", label: "Share of Shelf - Organic SOS", val: "20.7%", delta: "+19.5%", desc: "Unpaid search visibility", tooltip: "The proportion of a brand's product visibility within organic (non-paid) search results." },
        
        { id: "BSR_access", label: "BSR - Page Access", val: "Active", delta: "0", desc: "BSR tab access", tooltip: "Gives access to the BSR view." },
        { id: "BSR_products_in_bsr", label: "BSR - Products in BSR", val: "314", delta: "0", desc: "Products ranked in top 100 BSR", tooltip: "Products ranked in top 100 BSR." },
        { id: "BSR_avg_bsr_position", label: "BSR - Avg. BSR Position", val: "15.3", delta: "0", desc: "Average ranking across tracked products", tooltip: "Average ranking across tracked products." },
        { id: "BSR_bsr_sov", label: "BSR - BSR SOS %", val: "19.5%", delta: "0", desc: "Share of Voice in Best Seller rankings", tooltip: "Share of Voice in Best Seller rankings." },
        { id: "BSR_top_10_bsr_products", label: "BSR - Top 10 BSR Products", val: "199", delta: "0", desc: "Products in top 10 BSR positions", tooltip: "Products in top 10 BSR positions." }
    ],
    "Market Share": [
        { id: "category_size", label: "Category Size", val: "₹45.2 Cr", delta: "+8.4%", desc: "Total size of the category market", tooltip: "The total sales value of all products within a specific category over a defined period." },
        { id: "market_leader_sales", label: "Market Leader Sales", val: "₹12.4 Cr", delta: "+3.2%", desc: "Top-performing brand sales", tooltip: "Total sales of the top-performing brand in the category from estimated sales." },
        { id: "brand_estimated_sales", label: "Brand Estimated Sales", val: "₹8.4 Cr", delta: "+6.1%", desc: "Total sales value generated", tooltip: "The total sales value generated by a product or brand from estimated sales." },
        { id: "market_share", label: "Market Share %", val: "18.2%", delta: "+0.9%", desc: "% brand share of category", tooltip: "The percentage of total category sales contributed by a brand." },
        { id: "overall_share_of_visibility", label: "Overall Share of Visibility", val: "24.5%", delta: "-0.5%", desc: "Overall search visibility", tooltip: "The proportion of a brand's product visibility within the top search results, including both organic and sponsored placements." },
        { id: "paid_share_of_visibility", label: "Paid Share of Visibility", val: "17.6%", delta: "-8.6%", desc: "Paid search visibility", tooltip: "The proportion of a brand's product visibility within sponsored or paid placements in search results." }
    ],
    "Sales Data": [
        { id: "sales_revenue", label: "Sales Revenue", val: "₹8.4 Cr", delta: "+6.1%", desc: "Total invoices value", tooltip: "Gross invoices value generated by transactions." },
        { id: "orders_count", label: "Orders Count", val: "42.1K", delta: "+9.2%", desc: "Count of paid transactions", tooltip: "Total orders processed through digital checkouts." },
        { id: "average_order_value", label: "Average Order Value", val: "₹1,995", delta: "+2.1%", desc: "Revenue / Order count", tooltip: "Average transaction spend value per order." }
    ],
    "Pricing Analysis": [
        { id: "discount_pct", label: "Discount %", val: "14.2%", delta: "+0.8%", desc: "Average discount depth", tooltip: "Average discount percentage applied to listed retail prices." },
        { id: "weighted_discount", label: "Weighted Discount", val: "12.3%", delta: "+1.5%", desc: "Discount weighted by sales", tooltip: "Average discount across all SKUs, weighted by sales volume." },
        { id: "average_selling_price", label: "Average Selling Price", val: "₹249", delta: "-1.5%", desc: "Average price paid per unit", tooltip: "The average net price paid per unit across all platforms." },
        { id: "price_drop_my_skus", label: "Price Drop(my SKUs)", val: "4 Alerts", delta: "-1", desc: "Price drops on our SKUs", tooltip: "Number of our SKUs that experienced price drops." },
        { id: "price_increase_my_skus", label: "Price Increase(my SKUs)", val: "2 Alerts", delta: "+1", desc: "Price increases on our SKUs", tooltip: "Number of our SKUs that experienced price increases." },
        { id: "price_drop_comp_skus", label: "Price Drop(comp. SkUs)", val: "12 Alerts", delta: "+4", desc: "Price drops on competitor SKUs", tooltip: "Number of competitor SKUs that experienced price drops." },
        { id: "price_increase_comp_skus", label: "Price Increase(comp. SKUs)", val: "8 Alerts", delta: "-2", desc: "Price increases on competitor SKUs", tooltip: "Number of competitor SKUs that experienced price increases." },
        { id: "price_unit_1g_1piece", label: "Price/Unit 1g / 1 piece", val: "₹0.48/g", delta: "+1.2%", desc: "Price per unit weight/piece", tooltip: "Average price normalized per gram or per piece." }
    ],
    "Performance Marketing": [
        { id: "impressions", label: "Impressions", val: "1.2M", delta: "+14.2%", desc: "Total ad views", tooltip: "The total number of times a product or advertisement is displayed to users." },
        { id: "conversion", label: "Conversion", val: "25.5%", delta: "+31.0%", desc: "Ad conversion rate", tooltip: "The rate at which user interactions (such as clicks or views) result in a purchase." },
        { id: "spend", label: "Spend", val: "₹10.12 Lac", delta: "+5.1%", desc: "Total ad investment", tooltip: "The total investment made in advertising and promotional activities." },
        { id: "roas", label: "ROAS", val: "1.89", delta: "+18.1%", desc: "Return on Ad Spend", tooltip: "The revenue generated for every unit of advertising spend." },
        { id: "cpm", label: "CPM", val: "₹142", delta: "-2.4%", desc: "Cost per mille", tooltip: "The cost incurred to generate one thousand impressions." },
        { id: "sales", label: "Sales", val: "₹19.12 Lac", delta: "+17.0%", desc: "Ad-driven sales", tooltip: "The total sales value generated by a product or brand over a specified period." }
    ],
    "Portfolio Analysis": [
        { id: "active_skus", label: "Active SKUs", val: "142 SKUs", delta: "+5", desc: "SKUs with active sales", tooltip: "SKUs showing nonzero sales volume over the past 30 days." },
        { id: "new_sku_contribution", label: "New SKU Revenue", val: "₹45.2 Lac", delta: "+12.4%", desc: "Sales of SKUs <90d old", tooltip: "Revenue share of products launched in the last 90 days." }
    ],
    "Content Analysis": [
        { id: "title_score", label: "Title Score", val: "88.4%", delta: "+2.1%", desc: "SKU title quality rating", tooltip: "Quality compliance score for listing titles." },
        { id: "image_score", label: "Image Score", val: "91.2%", delta: "+1.5%", desc: "Hero image compliance rating", tooltip: "Quality compliance score for primary product listing images." },
        { id: "si_score", label: "SI Score(Secondary Image Score)", val: "85.6%", delta: "+2.4%", desc: "Secondary image score", tooltip: "Quality compliance score for secondary product listing images." },
        { id: "description_score", label: "Description Score", val: "82.4%", delta: "-1.1%", desc: "Bullets and description quality", tooltip: "Quality compliance score for features and description." },
        { id: "rating_score", label: "Rating Score", val: "4.4 Stars", delta: "+0.1", desc: "Average consumer rating", tooltip: "Average consumer rating score across online listings." },
        { id: "overall_score", label: "Overall Score", val: "84.5%", delta: "+2.4%", desc: "Aggregate listing score", tooltip: "Aggregate content health and quality optimization score." }
    ],
    "Inventory Analysis": [
        { id: "doh", label: "DOH", val: "12 Days", delta: "-1.5", desc: "Days of Hand", tooltip: "Days of Hand inventory availability." },
        { id: "drr", label: "DRR", val: "4.5", delta: "+0.2", desc: "Daily Run Rate", tooltip: "Daily Run Rate of stock usage." },
        { id: "total_boxes_required", label: "Total Boxes Required", val: "240", delta: "+12", desc: "Total boxes required", tooltip: "Total number of inventory boxes required." },
        { id: "drr_qty", label: "DRR Qty", val: "1,200", delta: "+45", desc: "Daily run rate quantity", tooltip: "Daily Run Rate unit quantity." },
        { id: "current_doh", label: "Current DOH", val: "14.2 Days", delta: "-0.8", desc: "Current days of hand", tooltip: "Current Days of Hand inventory cover." },
        { id: "req_po_qty", label: "Req PO Qty", val: "5,000", delta: "+150", desc: "Required Purchase Order Quantity", tooltip: "Required Purchase Order Unit Quantity." },
        { id: "req_boxes", label: "Req Boxes", val: "100", delta: "+5", desc: "Required Boxes", tooltip: "Required number of inventory boxes." },
        { id: "threshold_doh", label: "Threshold DOH", val: "7 Days", delta: "0", desc: "Minimum safe inventory cover", tooltip: "Minimum Days of Hand safety threshold." }
    ],
    "Play it Yourself": [
        { id: "custom_reports", label: "Custom Reports Created", val: "42", delta: "+6", desc: "User compiled reports", tooltip: "Reports customized and exported using playground variables." }
    ],
    "Category RCA": [
        { id: "root_causes_identified", label: "RCA Incidents", val: "8 Actionable", delta: "-2", desc: "Key root causes flags", tooltip: "Root Cause Analysis (RCA) issues detected in listing health." }
    ],
    "Scheduled Reports": [
        { id: "reports_delivered", label: "Delivered Reports", val: "142", delta: "+12", desc: "Dispatched report emails", tooltip: "Automated distribution reports successfully sent to recipients." },
        // Business Overview KPIs
        { id: "offtake", label: "Offtake", val: "₹12.4 Cr", delta: "+4.2%", desc: "Total sales value", tooltip: "The total sales value generated by a product or brand over a specified period." },
        { id: "units_sold", label: "Units Sold", val: "42K", delta: "+8.9%", desc: "Total units sold", tooltip: "The total number of product units sold over a specified period." },
        { id: "orders", label: "Orders", val: "5.9K", delta: "+17.7%", desc: "Total completed transactions", tooltip: "The total number of completed purchase transactions within a given period." },
        { id: "stock_availability", label: "Stock Availability", val: "89.4%", delta: "+1.8%", desc: "% stock available", tooltip: "The proportion of stores or locations where a product is available for purchase." },
        { id: "listing_pct", label: "Listing %", val: "92.4%", delta: "+1.2%", desc: "% SKUs listed", tooltip: "% of total possible SKUs that are listed on the platform/store." },
        { id: "inorganic_sales", label: "Inorganic Sales", val: "₹19.12 Lac", delta: "+17.0%", desc: "Advertising-driven sales revenue", tooltip: "Sales generated through paid advertising channels." },
        { id: "roas", label: "ROAS", val: "1.89", delta: "+18.1%", desc: "Return on Ad Spend", tooltip: "The revenue generated for every unit of advertising spend." },
        { id: "conversion_rate", label: "Conversion Rate", val: "25.5%", delta: "+31.0%", desc: "Overall conversion rate", tooltip: "Conversion rate measuring order completions relative to clicks." },
        { id: "cpm", label: "CPM", val: "₹142", delta: "-2.4%", desc: "Cost per 1000 impressions", tooltip: "The cost incurred to generate one thousand impressions." },
        { id: "cpc", label: "CPC", val: "₹4.12", delta: "-3.2%", desc: "Cost per click", tooltip: "The cost incurred for each user click on an advertisement." },
        { id: "bmi_sales_ratio", label: "BMI Sales Ratio", val: "2.1%", delta: "+0.2%", desc: "BMI as % of sales", tooltip: "Brand Marketing Investment as a percentage of total sales." },
        { id: "promo_pct", label: "Promo %", val: "12.3%", delta: "+2.1%", desc: "% discounted items sold", tooltip: "A price reduction or special offer applied to a product to encourage purchase." },
        // Availability KPIs
        { id: "osa_pct", label: "OSA %", val: "89.4%", delta: "+1.8%", desc: "On-Shelf Availability %", tooltip: "On-shelf stock availability percentage." },
        { id: "stock_out_pct", label: "Stock Out %", val: "10.6%", delta: "-1.8%", desc: "% out-of-stock instances", tooltip: "Percentage of stores/locations where a product is out of stock." },
        { id: "doi", label: "DOI", val: "14.2 Days", delta: "-1.5", desc: "Days of Inventory", tooltip: "The number of days current inventory is expected to last based on recent sales trend." },
        { id: "sos_pct", label: "SOS %", val: "24.5%", delta: "-0.5%", desc: "Share of Search %", tooltip: "Share of Search is calculated based on Top 10 rank positions." },
        { id: "psl", label: "PSL", val: "₹4.2 Lac", delta: "-12%", desc: "Potential Sales Loss", tooltip: "The estimated sales loss due to unavailability." },
        { id: "assortment", label: "Assortment", val: "142 SKUs", delta: "+5", desc: "Active SKU count", tooltip: "Number of distinct SKUs listed and available." },
        { id: "metro_city_stock_availability", label: "Metro City Stock Availability", val: "78.5%", delta: "-2.0%", desc: "Metro city availability %", tooltip: "Stock availability in metro cities." },
        // Visibility KPIs
        { id: "overall_sos_pct", label: "Overall SOS %", val: "19.6%", delta: "+4.3%", desc: "Overall Share of Search %", tooltip: "The proportion of a brand's product visibility within the top search results." },
        { id: "sponsored_sos_pct", label: "Sponsored SOS %", val: "17.6%", delta: "-8.6%", desc: "Sponsored search visibility", tooltip: "The proportion of a brand's product visibility within sponsored placements." },
        { id: "organic_sos_pct", label: "Organic SOS %", val: "20.7%", delta: "+19.5%", desc: "Organic search visibility", tooltip: "The proportion of a brand's product visibility within organic search results." },
        { id: "ad_position", label: "Ad Position", val: "2.4", delta: "-0.3", desc: "Average sponsored position", tooltip: "Average position of sponsored listings in search results." },
        { id: "org_position", label: "Org Position", val: "3.1", delta: "-0.2", desc: "Average organic position", tooltip: "Average position of organic listings in search results." },
        // Pricing KPIs
        { id: "ecp", label: "ECP", val: "₹249", delta: "-1.5%", desc: "Effective Consumer Price", tooltip: "The average net price paid per unit across all platforms." },
        { id: "mrp", label: "MRP", val: "₹299", delta: "0%", desc: "Maximum Retail Price", tooltip: "The maximum retail price of the product." },
        { id: "discount_pct", label: "Discount %", val: "14.2%", delta: "+0.8%", desc: "Average discount depth", tooltip: "Average discount percentage applied to listed retail prices." },
        { id: "rpi", label: "RPI", val: "0.97", delta: "+0.01", desc: "Relative Price Index", tooltip: "Brand price relative to category average price." },
        // Performance Marketing KPIs
        { id: "impressions", label: "Impressions", val: "1.2M", delta: "+14.2%", desc: "Total ad views", tooltip: "The total number of times a product or advertisement is displayed to users." },
        { id: "clicks", label: "Clicks", val: "42K", delta: "+8.9%", desc: "Total ad clicks", tooltip: "The total number of times users interact with a product or advertisement." },
        { id: "spend", label: "Spend", val: "₹10.12 Lac", delta: "+5.1%", desc: "Total ad investment", tooltip: "The total investment made in advertising and promotional activities." },
        // Inventory KPIs
        { id: "current_inventory", label: "Current Inventory", val: "45K units", delta: "+5.8%", desc: "Total inventory available", tooltip: "Total inventory available at a given point in time." },
        { id: "target_inventory", label: "Target Inventory", val: "50K units", delta: "0%", desc: "Target inventory level (MSL)", tooltip: "Minimum Stock Level (MSL) or target inventory to maintain." },
        { id: "inventory_health_pct", label: "Inventory Health %", val: "90%", delta: "+2%", desc: "Inventory vs. target %", tooltip: "Ratio of current inventory to target inventory as a percentage." },
        { id: "days_on_hand", label: "Days On Hand", val: "12 Days", delta: "-1.5", desc: "Days of inventory on hand", tooltip: "Days of Hand inventory availability." },
        // Content KPIs
        { id: "overall_content_score", label: "Overall Content Score", val: "84.5%", delta: "+2.4%", desc: "Aggregate listing score", tooltip: "Aggregate content health and quality optimization score." },
        { id: "title_score", label: "Title Score", val: "88.4%", delta: "+2.1%", desc: "SKU title quality rating", tooltip: "Quality compliance score for listing titles." },
        { id: "image_score", label: "Image Score", val: "91.2%", delta: "+1.5%", desc: "Hero image compliance rating", tooltip: "Quality compliance score for primary product listing images." },
        { id: "description_score", label: "Description Score", val: "82.4%", delta: "-1.1%", desc: "Description quality score", tooltip: "Quality compliance score for features and description." },
        { id: "title_length", label: "Title Length", val: "72 chars", delta: "+2", desc: "Title character count", tooltip: "Number of characters in the product title." },
        { id: "word_count", label: "Word Count", val: "148 words", delta: "+5", desc: "Description word count", tooltip: "Number of words in the product description." },
        // Market Share KPIs
        { id: "sales_value", label: "Sales Value", val: "₹8.4 Cr", delta: "+6.1%", desc: "Brand estimated sales value", tooltip: "The total sales value generated by a product or brand from estimated sales." },
        { id: "market_share_pct", label: "Market Share %", val: "18.2%", delta: "+0.9%", desc: "% brand share of category", tooltip: "The percentage of total category sales contributed by a brand." },
        { id: "category_size", label: "Category Size", val: "₹45.2 Cr", delta: "+8.4%", desc: "Total size of the category", tooltip: "The total sales value of all products within a specific category over a defined period." }
    ],
    "Download Report": [
        { id: "total_downloads", label: "Total Downloads", val: "342", delta: "+45", desc: "PDF/Excel report counts", tooltip: "Standard dashboard reports downloaded by client users." }
    ],
    "Ad Auto": [
        { id: "auto_campaigns", label: "Auto Campaigns", val: "8 Active", delta: "+1", desc: "AI managed campaigns", tooltip: "Self-optimizing advertising campaign setups currently active." }
    ],
    "Rating": [
        { id: "overall_rating", label: "Average Rating", val: "4.4 Stars", delta: "+0.1", desc: "Mean review rating score", tooltip: "Average customer rating across all online listings." }
    ],
    "Supply": [
        { id: "Prioritize PO_po_number", label: "Prioritize PO - PO Number", val: "N/A", delta: "0", desc: "PO Number", tooltip: "Unique identifier for the Purchase Order." },
        { id: "Prioritize PO_priority", label: "Prioritize PO - Priority", val: "N/A", delta: "0", desc: "Priority level", tooltip: "Calculated priority level based on stockout risk." },
        { id: "Prioritize PO_projected_sales_at_risk", label: "Prioritize PO - Projected Sales At Risk", val: "N/A", delta: "0", desc: "Sales at risk", tooltip: "Projected revenue loss if the inventory deficit is not filled." },
        { id: "Prioritize PO_platform_warehouse", label: "Prioritize PO - Platform Warehouse", val: "N/A", delta: "0", desc: "Platform Warehouse", tooltip: "Platform warehouse location." },
        { id: "Prioritize PO_status", label: "Prioritize PO - Status", val: "N/A", delta: "0", desc: "PO status", tooltip: "Current status of the PO." },
        { id: "Prioritize PO_billed_value", label: "Prioritize PO - Billed Value", val: "N/A", delta: "0", desc: "Billed value", tooltip: "Total billed value of the PO." },
        { id: "Prioritize PO_order_value", label: "Prioritize PO - Order Value", val: "N/A", delta: "0", desc: "Order value", tooltip: "Total ordered value of the PO." },
        { id: "Prioritize PO_raised_on", label: "Prioritize PO - Raised On", val: "N/A", delta: "0", desc: "Raised date", tooltip: "Date when the PO was raised." },
        { id: "Prioritize PO_appt_date", label: "Prioritize PO - Appointment Date", val: "N/A", delta: "0", desc: "Appointment date", tooltip: "Date of the delivery appointment." },
        { id: "Prioritize PO_expiry", label: "Prioritize PO - Expiry", val: "N/A", delta: "0", desc: "Expiry date", tooltip: "Expiry date of the PO." },
        { id: "Prioritize PO_avg_doi", label: "Prioritize PO - Avg DOI", val: "N/A", delta: "0", desc: "Avg DOI", tooltip: "Average Days of Inventory cover." },
        { id: "Prioritize PO_lt_days", label: "Prioritize PO - Lead Time (Days)", val: "N/A", delta: "0", desc: "Lead time", tooltip: "Lead time in days." },
        { id: "Prioritize PO_fill_c_p_b_g", label: "Prioritize PO - Fill (C-P-B-G)", val: "N/A", delta: "0", desc: "Fill status", tooltip: "Fill rate status metrics." },
        { id: "Prioritize PO_consumption_day", label: "Prioritize PO - Consumption / Day", val: "N/A", delta: "0", desc: "Consumption/day", tooltip: "Daily unit sales rate." },

        { id: "Fix Stock Transfer_sku_name", label: "Stock Transfer - SKU Name", val: "N/A", delta: "0", desc: "SKU Name", tooltip: "Name of the SKU." },
        { id: "Fix Stock Transfer_from_cfa_surplus", label: "Stock Transfer - From CFA (Surplus)", val: "N/A", delta: "0", desc: "From CFA", tooltip: "Origin CFA with surplus inventory." },
        { id: "Fix Stock Transfer_to_cfa_deficit", label: "Stock Transfer - To CFA (Deficit)", val: "N/A", delta: "0", desc: "To CFA", tooltip: "Destination CFA with deficit inventory." },
        { id: "Fix Stock Transfer_distance_km", label: "Stock Transfer - Distance (KM)", val: "N/A", delta: "0", desc: "Distance", tooltip: "Distance between CFAs in kilometers." },
        { id: "Fix Stock Transfer_doi_deficit", label: "Stock Transfer - DOI (Deficit)", val: "N/A", delta: "0", desc: "DOI Deficit", tooltip: "DOI at the destination CFA." },
        { id: "Fix Stock Transfer_doi_surplus", label: "Stock Transfer - DOI (Surplus)", val: "N/A", delta: "0", desc: "DOI Surplus", tooltip: "DOI at the origin CFA." },
        { id: "Fix Stock Transfer_soh_deficit", label: "Stock Transfer - SOH (Deficit)", val: "N/A", delta: "0", desc: "SOH Deficit", tooltip: "Stock on Hand at the destination CFA." },
        { id: "Fix Stock Transfer_soh_surplus", label: "Stock Transfer - SOH (Surplus)", val: "N/A", delta: "0", desc: "SOH Surplus", tooltip: "Stock on Hand at the origin CFA." },
        { id: "Fix Stock Transfer_cpd_deficit", label: "Stock Transfer - CPD (Deficit)", val: "N/A", delta: "0", desc: "CPD Deficit", tooltip: "Consumption Per Day at the destination CFA." },
        { id: "Fix Stock Transfer_transfer_qty", label: "Stock Transfer - Transfer Qty", val: "N/A", delta: "0", desc: "Transfer Qty", tooltip: "Recommended transfer quantity." },

        { id: "Manage Surplus_sku_sap_code", label: "Manage Surplus - SKU (SAP Code)", val: "N/A", delta: "0", desc: "SKU / SAP Code", tooltip: "SKU Name and SAP code." },
        { id: "Manage Surplus_severity", label: "Manage Surplus - Severity", val: "N/A", delta: "0", desc: "Severity", tooltip: "Severity score of the surplus." },
        { id: "Manage Surplus_surplus_ea", label: "Manage Surplus - Surplus (EA)", val: "N/A", delta: "0", desc: "Surplus EA", tooltip: "Surplus quantity in eaches." },
        { id: "Manage Surplus_net_doi", label: "Manage Surplus - Net DOI", val: "N/A", delta: "0", desc: "Net DOI", tooltip: "Net cover days of the surplus." },
        { id: "Manage Surplus_cfas_count", label: "Manage Surplus - CFAs Count", val: "N/A", delta: "0", desc: "CFAs Count", tooltip: "Count of CFAs where this SKU has surplus." },
        { id: "Manage Surplus_dead_cfas", label: "Manage Surplus - Dead CFAs", val: "N/A", delta: "0", desc: "Dead CFAs", tooltip: "Count of CFAs with no movement." },
        { id: "Manage Surplus_min_expiry", label: "Manage Surplus - Min Expiry", val: "N/A", delta: "0", desc: "Min Expiry", tooltip: "Minimum days to batch expiry." },
        { id: "Manage Surplus_value_at_risk", label: "Manage Surplus - Value At Risk", val: "N/A", delta: "0", desc: "Value at Risk", tooltip: "Financial value at risk in Lakhs." },
        { id: "Manage Surplus_team_action_recommendation", label: "Manage Surplus - Team / Action Recommendation", val: "N/A", delta: "0", desc: "Team & Action", tooltip: "Target team and recommended action details." }
    ],
    "PDS Score": [
        { id: "pds_overall_score", label: "PDS Overall Score", val: "84.5", delta: "+2.4", desc: "% title, image, and bullets optimization", tooltip: "Aggregate Product Detail Page content optimization score." },
        { id: "dmmh_lever", label: "DMMH Lever", val: "N/A", delta: "0", desc: "DMMH Lever Category", tooltip: "DMMH Lever Category classification." },
        { id: "dmmh_sub_lever", label: "DMMH Sub-Lever", val: "N/A", delta: "0", desc: "DMMH Sub-Lever Detail", tooltip: "DMMH Sub-Lever Specific metric." },
        { id: "target", label: "Target", val: "N/A", delta: "0", desc: "Target metric value", tooltip: "Defined target threshold." },
        { id: "weight", label: "Weight", val: "N/A", delta: "0", desc: "Lever weight percentage", tooltip: "Assigned weight score in final calculation." },
        { id: "score", label: "Score", val: "N/A", delta: "0", desc: "Raw score achieved", tooltip: "Raw compliance score achieved." },
        { id: "wt_score", label: "Wt Score", val: "N/A", delta: "0", desc: "Weighted score", tooltip: "Weighted score contribution." },
        { id: "wt_target", label: "Wt Target", val: "N/A", delta: "0", desc: "Weighted target", tooltip: "Weighted target contribution." }
    ],
    "Insights": [
        { id: "share_headroom_hotspots", label: "Share Headroom Hotspots", val: "₹0", delta: "0", desc: "Offtake Loss Impact", tooltip: "Hotspots representing market share headroom loss or gain." },
        { id: "price_parity_radar", label: "Price Parity Radar", val: "₹0", delta: "0", desc: "Opportunity Available", tooltip: "Radar alert when client pricing deviates from parity." },
        { id: "ds_listing_summary", label: "DS Listing Summary", val: "₹0", delta: "0", desc: "Potential Sales Loss", tooltip: "Overview of listing presence in active dark stores." },
        { id: "competitor_osa_weak_spots", label: "Competitor OSA Weak Spots", val: "₹0", delta: "0", desc: "Opportunity Available", tooltip: "Regions where competitors are out of stock." },
        { id: "remove_ad_low_osa", label: "Remove Ad Low OSA", val: "₹0", delta: "0", desc: "Ad Efficiency Loss", tooltip: "Flagging active ads pointing to low on-shelf availability products." },
        { id: "surplus_stock", label: "Surplus Stock", val: "0 Units", delta: "0", desc: "Excess Inventory", tooltip: "Surplus inventory at hand exceeding coverage target." },
        { id: "prioritise_po", label: "Prioritise PO", val: "₹0", delta: "0", desc: "Projected Sales Loss", tooltip: "Unfilled PO lines that risk immediate stockouts." },
        { id: "transfer_issue", label: "Transfer Issue", val: "₹0", delta: "0", desc: "Projected Sales Loss", tooltip: "Issues arising from slow or pending inter-CFA stock transfers." },
        { id: "new_market_entry", label: "New Market Entry", val: "2026-07-01", delta: "0", desc: "Last Seen Date", tooltip: "Date and details of new competitor entries." },
        { id: "dark_store_coverage_gaps", label: "Dark Store Coverage Gaps", val: "₹0", delta: "0", desc: "Potential Sales Loss", tooltip: "Listing absence across prominent dark store locations." },
        { id: "new_dark_store_expansion", label: "New Dark Store Expansion", val: "₹0", delta: "0", desc: "Potential Sales Loss", tooltip: "New dark store locations opened in key regions." },
        { id: "co_relations", label: "Co-Relations", val: "N/A", delta: "0", desc: "KPI Anomalies Detected", tooltip: "Correlated shifts across major KPIs." }
    ]
};

const ManageKpi = () => {
    const { user: loggedInUser, setUser: setLoggedInUser } = useAuth();
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const [usersData, setUsersData] = useState([]);
    const [allDatabases, setAllDatabases] = useState([]);
    const [selectedDb, setSelectedDb] = useState("");
    const [selectedUser, setSelectedUser] = useState("all");
    const [searchTerm, setSearchTerm] = useState("");
    const [activePage, setActivePage] = useState("");
    const [hoveredTooltip, setHoveredTooltip] = useState(null);

    // Track KPI settings changed state to force re-render
    const [configVersion, setConfigVersion] = useState(0);

    useEffect(() => {
        fetchPermissionsUsers();
        fetchDatabases();
    }, []);

    const fetchDatabases = async () => {
        try {
            const token = sessionStorage.getItem("token");
            const response = await axios.get(`${API_BASE}/admin/databases`, {
                headers: { Authorization: `Bearer ${token}` }
            });
            if (response.data.success) {
                const uniqueDbs = [];
                const seenNames = new Set();
                for (const db of response.data.data) {
                    if (db && db.db_name) {
                        const name = db.db_name.toLowerCase().trim();
                        if (!seenNames.has(name)) {
                            seenNames.add(name);
                            uniqueDbs.push({
                                id: db.db_id,
                                name: name
                            });
                        }
                    }
                }
                setAllDatabases(uniqueDbs);
                
                // Auto-select first database if none selected (prioritizing 'mars')
                if (uniqueDbs.length > 0 && !selectedDb) {
                    const hasMars = uniqueDbs.find(d => d.name.toLowerCase() === 'mars');
                    setSelectedDb(hasMars ? hasMars.name : uniqueDbs[0].name);
                }
            }
        } catch (err) {
            console.error('[ManageKpi] Failed to fetch databases:', err);
        }
    };

    const fetchPermissionsUsers = async () => {
        try {
            setLoading(true);
            setError(null);
            const token = sessionStorage.getItem("token");
            const response = await axios.get(`${API_BASE}/admin/permissions/users`, {
                headers: { Authorization: `Bearer ${token}` }
            });
            if (response.data.success) {
                const users = response.data.data.map((user) => {
                    const tabPerms = user.tabPermissions || {};
                    const hasAnyPerm = Object.keys(tabPerms).length > 0;
                    const tabs = tabsList.reduce((acc, tab) => {
                        acc[tab] = hasAnyPerm ? (tabPerms[tab] !== undefined ? tabPerms[tab] : true) : true;
                        return acc;
                    }, {});

                    // Add KPI permissions
                    Object.keys(tabPerms).forEach(key => {
                        if (key.startsWith('kpi_')) {
                            tabs[key] = tabPerms[key];
                        }
                    });

                    return {
                        id: user.id,
                        email: user.email,
                        name: user.name || user.email.split('@')[0],
                        role: user.role || 'user',
                        dbName: user.dbName || 'N/A',
                        dbStatus: user.dbStatus,
                        tabs
                    };
                });
                setUsersData(users);

                // Auto-select first database from users if databases API list not loaded yet (prioritizing 'mars')
                if (!selectedDb) {
                    const uniqueDbs = [...new Set(users.map(u => u.dbName).filter(d => d && d !== 'N/A'))].sort();
                    if (uniqueDbs.length > 0) {
                        const hasMars = uniqueDbs.find(d => d.toLowerCase() === 'mars');
                        setSelectedDb(hasMars || uniqueDbs[0]);
                    }
                }
            }
        } catch (err) {
            console.error('[ManageKpi] Failed to fetch users:', err);
            setError('Failed to load KPI data');
        } finally {
            setLoading(false);
        }
    };

    // All unique databases
    const uniqueDatabases = useMemo(() => {
        if (allDatabases.length > 0) {
            return allDatabases.map(db => db.name).sort();
        }
        return [...new Set(usersData.map(u => u.dbName).filter(d => d && d !== 'N/A'))].sort();
    }, [allDatabases, usersData]);

    // Users filtered by selected database
    const filteredUsers = useMemo(() => {
        if (!selectedDb) return [];
        return usersData.filter(u => u.dbName?.toLowerCase().trim() === selectedDb?.toLowerCase().trim());
    }, [usersData, selectedDb]);

    // Check tab permission per database (Client)
    // If any active user in this client has permission, the page is ACTIVE.
    const clientPages = useMemo(() => {
        if (!selectedDb) return {};
        const map = {};
        tabsList.forEach(tab => {
            const hasAccess = filteredUsers.some(u => u.tabs[tab] === true && u.dbStatus !== false);
            map[tab] = hasAccess;
        });
        return map;
    }, [filteredUsers, selectedDb]);

    // Reset selectedUser only when Client (Database) changes
    useEffect(() => {
        if (selectedDb) {
            setSelectedUser("all");
        }
    }, [selectedDb]);

    // Auto-select the first active page when client changes or active page becomes inactive
    useEffect(() => {
        if (selectedDb && (!activePage || !clientPages[activePage])) {
            const firstActive = tabsList.find(tab => clientPages[tab] === true);
            if (firstActive) {
                setActivePage(firstActive);
            } else {
                setActivePage("");
            }
        }
    }, [selectedDb, clientPages, activePage]);

    // Dynamic KPI retriever to get KPIs from both local maps and ClickHouse permissions
    const getDynamicPageKpis = useCallback((pageName) => {
        if (!pageName || !selectedDb) return [];

        // 1. Get the list of all unique flat KPI IDs for this page from the database (via user.tabs)
        const dbUsers = usersData.filter(u => u.dbName?.toLowerCase().trim() === selectedDb?.toLowerCase().trim());
        const kpiIds = new Set();
        
        dbUsers.forEach(user => {
            Object.keys(user.tabs).forEach(key => {
                const prefix = `kpi_${pageName}_`;
                if (key.startsWith(prefix)) {
                    const kpiId = key.substring(prefix.length);
                    if (kpiId && !kpiId.endsWith('_access')) {
                        kpiIds.add(kpiId);
                    }
                }
            });
        });

        // 2. Also merge with any hardcoded ones in PAGE_KPIS_MAP as fallbacks
        const hardcodedKpis = PAGE_KPIS_MAP[pageName] || [];
        hardcodedKpis.forEach(kpi => {
            kpiIds.add(kpi.id);
        });

        const hardcodedIds = hardcodedKpis.map(k => k.id);
        const filteredKpiIds = Array.from(kpiIds).filter(id => hardcodedIds.includes(id));
        const sortedKpiIds = filteredKpiIds.sort((a, b) => {
            const idxA = hardcodedIds.indexOf(a);
            const idxB = hardcodedIds.indexOf(b);
            
            if (idxA >= 0 && idxB >= 0) {
                return idxA - idxB;
            }
            if (idxA >= 0) return -1;
            if (idxB >= 0) return 1;
            return a.localeCompare(b);
        });

        // 3. Map to final KPI objects
        const formatLabel = (id) => {
            let displayId = id;
            let prefix = "";
            const subPages = ["Prioritize PO", "Fix Stock Transfer", "Manage Surplus", "Share of Shelf", "BSR", "Share Of shelf"];
            const matchingSub = subPages.find(sp => id.toLowerCase().startsWith(sp.toLowerCase() + "_"));
            if (matchingSub) {
                prefix = matchingSub.toLowerCase().startsWith('bsr') ? "BSR - " : "Share of Shelf - ";
                displayId = id.substring(matchingSub.length + 1);
            }

            const cleaned = displayId.replace(/[_-]/g, ' ')
                .split(' ')
                .map(w => w.charAt(0).toUpperCase() + w.slice(1))
                .join(' ');
            return prefix + cleaned;
        };

        return sortedKpiIds.map(id => {
            const found = hardcodedKpis.find(k => k.id === id);
            if (found) return found;

            return {
                id,
                label: formatLabel(id),
                val: "N/A",
                delta: "0",
                desc: formatLabel(id),
                tooltip: `Dynamic KPI permission: ${id}`
            };
        });
    }, [selectedDb, usersData]);

    // Helpers to manage ClickHouse database and LocalStorage persisted KPI config
    // `page` defaults to `activePage` so existing toggle/save logic works unchanged,
    // but can be overridden when computing counts for other tabs in the left panel.
    const getKpiStatus = (kpiId, page = activePage) => {
        if (!selectedDb || !page) return true;
        const flatKey = `kpi_${page}_${kpiId}`;

        if (selectedUser && selectedUser !== 'all') {
            const usr = usersData.find(u => u.email === selectedUser);
            if (usr) {
                const dbVal = usr.tabs[flatKey];
                if (dbVal !== undefined) return dbVal;
            }
        } else {
            // Check if there is any user in the selected database and get their KPI permission
            const dbUsers = usersData.filter(u => u.dbName?.toLowerCase().trim() === selectedDb?.toLowerCase().trim());
            if (dbUsers.length > 0) {
                const dbVal = dbUsers[0].tabs[flatKey];
                if (dbVal !== undefined) return dbVal;
            }
        }

        const key = `kpi_config_${selectedDb.toLowerCase()}_${page.replace(/\s+/g, '_').toLowerCase()}_${kpiId}`;
        const stored = localStorage.getItem(key);
        return stored === null ? true : stored === 'true';
    };

    const handleToggleKpi = async (kpiId) => {
        if (!selectedDb || !activePage) return;
        const current = getKpiStatus(kpiId);
        const newStatus = !current;
        const flatKey = `kpi_${activePage}_${kpiId}`;

        // 1. Optimistic update
        setUsersData(prev => prev.map(u => {
            if (selectedUser && selectedUser !== 'all') {
                if (u.email === selectedUser) {
                    return {
                        ...u,
                        tabs: { ...u.tabs, [flatKey]: newStatus }
                    };
                }
            } else {
                if (u.dbName?.toLowerCase().trim() === selectedDb?.toLowerCase().trim()) {
                    return {
                        ...u,
                        tabs: { ...u.tabs, [flatKey]: newStatus }
                    };
                }
            }
            return u;
        }));

        // 2. LocalStorage legacy fallback
        const key = `kpi_config_${selectedDb.toLowerCase()}_${activePage.replace(/\s+/g, '_').toLowerCase()}_${kpiId}`;
        localStorage.setItem(key, String(newStatus));
        setConfigVersion(v => v + 1);

        // Update logged in user context in real time if editing current DB/User
        const isLoggedUserAffected = (selectedUser === loggedInUser?.email) || 
                                     (selectedUser === 'all' && loggedInUser?.dbName?.toLowerCase() === selectedDb?.toLowerCase());
        if (loggedInUser && isLoggedUserAffected) {
            const updatedUser = {
                ...loggedInUser,
                tabPermissions: {
                    ...loggedInUser.tabPermissions,
                    [flatKey]: newStatus
                }
            };
            setLoggedInUser(updatedUser);
            sessionStorage.setItem("user", JSON.stringify(updatedUser));
        }

        // 3. Persist to backend
        try {
            const token = sessionStorage.getItem("token");
            await axios.patch(`${API_BASE}/admin/permissions/kpi-permissions`, {
                dbName: selectedDb,
                page: activePage,
                kpis: { [kpiId]: newStatus },
                userEmail: selectedUser
            }, {
                headers: { Authorization: `Bearer ${token}` }
            });
        } catch (err) {
            console.error('[ManageKpi] Failed to update KPI permission in ClickHouse:', err);
            // Revert state on error
            setUsersData(prev => prev.map(u => {
                if (selectedUser && selectedUser !== 'all') {
                    if (u.email === selectedUser) {
                        return {
                            ...u,
                            tabs: { ...u.tabs, [flatKey]: current }
                        };
                    }
                } else {
                    if (u.dbName === selectedDb) {
                        return {
                            ...u,
                            tabs: { ...u.tabs, [flatKey]: current }
                        };
                    }
                }
                return u;
            }));
            localStorage.setItem(key, String(current));
            setConfigVersion(v => v + 1);
        }
    };

    const handleEnableAll = async () => {
        if (!selectedDb || !activePage) return;
        const kpis = getDynamicPageKpis(activePage);
        const batch = {};
        kpis.forEach(k => {
            batch[k.id] = true;
        });

        // 1. Optimistic update
        setUsersData(prev => prev.map(u => {
            if (selectedUser && selectedUser !== 'all') {
                if (u.email === selectedUser) {
                    const updatedTabs = { ...u.tabs };
                    kpis.forEach(k => {
                        updatedTabs[`kpi_${activePage}_${k.id}`] = true;
                    });
                    return { ...u, tabs: updatedTabs };
                }
            } else {
                if (u.dbName?.toLowerCase().trim() === selectedDb?.toLowerCase().trim()) {
                    const updatedTabs = { ...u.tabs };
                    kpis.forEach(k => {
                        updatedTabs[`kpi_${activePage}_${k.id}`] = true;
                    });
                    return { ...u, tabs: updatedTabs };
                }
            }
            return u;
        }));

        // 2. LocalStorage legacy fallback
        kpis.forEach(k => {
            const key = `kpi_config_${selectedDb.toLowerCase()}_${activePage.replace(/\s+/g, '_').toLowerCase()}_${k.id}`;
            localStorage.setItem(key, "true");
        });
        setConfigVersion(v => v + 1);

        // Update logged in user context in real time if editing current DB/User
        const isLoggedUserAffected = (selectedUser === loggedInUser?.email) || 
                                     (selectedUser === 'all' && loggedInUser?.dbName?.toLowerCase() === selectedDb?.toLowerCase());
        if (loggedInUser && isLoggedUserAffected) {
            const updatedPerms = { ...loggedInUser.tabPermissions };
            kpis.forEach(k => {
                updatedPerms[`kpi_${activePage}_${k.id}`] = true;
            });
            const updatedUser = {
                ...loggedInUser,
                tabPermissions: updatedPerms
            };
            setLoggedInUser(updatedUser);
            sessionStorage.setItem("user", JSON.stringify(updatedUser));
        }

        // 3. Persist to backend
        try {
            const token = sessionStorage.getItem("token");
            await axios.patch(`${API_BASE}/admin/permissions/kpi-permissions`, {
                dbName: selectedDb,
                page: activePage,
                kpis: batch,
                userEmail: selectedUser
            }, {
                headers: { Authorization: `Bearer ${token}` }
            });
        } catch (err) {
            console.error('[ManageKpi] Failed to enable all KPIs:', err);
            fetchPermissionsUsers();
        }
    };

    const handleDisableAll = async () => {
        if (!selectedDb || !activePage) return;
        const kpis = getDynamicPageKpis(activePage);
        const batch = {};
        kpis.forEach(k => {
            batch[k.id] = false;
        });

        // 1. Optimistic update
        setUsersData(prev => prev.map(u => {
            if (selectedUser && selectedUser !== 'all') {
                if (u.email === selectedUser) {
                    const updatedTabs = { ...u.tabs };
                    kpis.forEach(k => {
                        updatedTabs[`kpi_${activePage}_${k.id}`] = false;
                    });
                    return { ...u, tabs: updatedTabs };
                }
            } else {
                if (u.dbName?.toLowerCase().trim() === selectedDb?.toLowerCase().trim()) {
                    const updatedTabs = { ...u.tabs };
                    kpis.forEach(k => {
                        updatedTabs[`kpi_${activePage}_${k.id}`] = false;
                    });
                    return { ...u, tabs: updatedTabs };
                }
            }
            return u;
        }));

        // 2. LocalStorage legacy fallback
        kpis.forEach(k => {
            const key = `kpi_config_${selectedDb.toLowerCase()}_${activePage.replace(/\s+/g, '_').toLowerCase()}_${k.id}`;
            localStorage.setItem(key, "false");
        });
        setConfigVersion(v => v + 1);

        // Update logged in user context in real time if editing current DB/User
        const isLoggedUserAffected = (selectedUser === loggedInUser?.email) || 
                                     (selectedUser === 'all' && loggedInUser?.dbName?.toLowerCase() === selectedDb?.toLowerCase());
        if (loggedInUser && isLoggedUserAffected) {
            const updatedPerms = { ...loggedInUser.tabPermissions };
            kpis.forEach(k => {
                updatedPerms[`kpi_${activePage}_${k.id}`] = false;
            });
            const updatedUser = {
                ...loggedInUser,
                tabPermissions: updatedPerms
            };
            setLoggedInUser(updatedUser);
            sessionStorage.setItem("user", JSON.stringify(updatedUser));
        }

        // 3. Persist to backend
        try {
            const token = sessionStorage.getItem("token");
            await axios.patch(`${API_BASE}/admin/permissions/kpi-permissions`, {
                dbName: selectedDb,
                page: activePage,
                kpis: batch,
                userEmail: selectedUser
            }, {
                headers: { Authorization: `Bearer ${token}` }
            });
        } catch (err) {
            console.error('[ManageKpi] Failed to disable all KPIs:', err);
            fetchPermissionsUsers();
        }
    };

    // Filter pages list based on search term
    const searchedPages = useMemo(() => {
        const q = searchTerm.toLowerCase().trim();
        return tabsList.filter(tab => !q || tab.toLowerCase().includes(q));
    }, [searchTerm]);

    // Get count of active KPIs for a given page
    const getActiveKpiCount = (pageName) => {
        if (!selectedDb) return 0;
        const kpis = getDynamicPageKpis(pageName);
        // Pass pageName explicitly so we check the correct page's KPI status,
        // not the currently selected activePage.
        return kpis.filter(k => getKpiStatus(k.id, pageName)).length;
    };

    const selectedPageKpis = useMemo(() => getDynamicPageKpis(activePage), [activePage, getDynamicPageKpis]);

    if (loading) {
        return (
            <div className="flex items-center justify-center py-20">
                <Loader2 className="w-6 h-6 text-indigo-600 animate-spin" />
                <span className="ml-3 text-sm text-slate-500 font-medium">Loading KPI Manager...</span>
            </div>
        );
    }

    if (error) {
        return (
            <div className="flex flex-col items-center justify-center py-20 gap-3">
                <XCircle className="w-8 h-8 text-rose-500" />
                <span className="text-sm text-slate-600 font-medium">{error}</span>
                <button
                    onClick={fetchPermissionsUsers}
                    className="px-4 py-2 bg-indigo-600 text-white rounded-xl text-xs font-bold hover:bg-indigo-700 transition-all cursor-pointer"
                >
                    Retry
                </button>
            </div>
        );
    }

    const activePageIconIdx = tabsList.indexOf(activePage);
    const activePageGradient = CARD_GRADIENTS[activePageIconIdx >= 0 ? activePageIconIdx % CARD_GRADIENTS.length : 0];

    return (
        <div className="space-y-6 animate-in fade-in duration-500 font-sans">
            {/* Header */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-slate-100 pb-5">
                <div>
                    <h2 className="text-sm font-bold text-indigo-600 uppercase tracking-widest mb-1">Manage KPI Configurations</h2>
                    <p className="text-slate-500 text-xs font-medium">
                        Configure page-specific KPIs. Pages with disabled permissions are automatically locked.
                    </p>
                </div>
                <div className="flex items-center gap-3 w-full md:w-auto flex-wrap">
                    {/* Client Selector */}
                    <div className="relative w-full md:w-auto">
                        <Database className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-indigo-500 pointer-events-none" />
                        <select
                            value={selectedDb}
                            onChange={(e) => setSelectedDb(e.target.value)}
                            className="w-full md:w-52 pl-10 pr-9 py-2.5 bg-white border border-slate-200 rounded-xl text-xs font-bold text-slate-700 shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 cursor-pointer appearance-none transition-all"
                            style={{
                                backgroundImage: `url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%236b7280' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e")`,
                                backgroundPosition: 'right 0.75rem center',
                                backgroundRepeat: 'no-repeat',
                                backgroundSize: '1.2em 1.2em'
                            }}
                        >
                            {uniqueDatabases.map(db => (
                                <option key={db} value={db}>
                                    {db.toUpperCase()}
                                </option>
                            ))}
                        </select>
                    </div>

                    {/* User Selector */}
                    <div className="relative w-full md:w-auto">
                        <Users className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-indigo-500 pointer-events-none" />
                        <select
                            value={selectedUser}
                            onChange={(e) => setSelectedUser(e.target.value)}
                            className="w-full md:w-56 pl-10 pr-9 py-2.5 bg-white border border-slate-200 rounded-xl text-xs font-bold text-slate-700 shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 cursor-pointer appearance-none transition-all"
                            style={{
                                backgroundImage: `url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%236b7280' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e")`,
                                backgroundPosition: 'right 0.75rem center',
                                backgroundRepeat: 'no-repeat',
                                backgroundSize: '1.2em 1.2em'
                            }}
                        >
                            <option value="all">— All Users —</option>
                            {usersData.filter(u => u.dbName?.toLowerCase().trim() === selectedDb?.toLowerCase().trim()).map(u => (
                                <option key={u.id} value={u.email}>
                                    {u.name || u.email} ({u.role.toUpperCase()})
                                </option>
                            ))}
                        </select>
                    </div>
                </div>
            </div>

            {/* Split Layout Container */}
            <div className="grid grid-cols-12 gap-6 items-start">
                
                {/* Left Side: Pages Rail (Col 4) */}
                <div className="col-span-12 lg:col-span-4 bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden flex flex-col max-h-[700px]">
                    <div className="p-4 border-b border-slate-100 bg-slate-50/50 flex flex-col gap-3">
                        <div className="flex items-center justify-between">
                            <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">Pages / Tabs</span>
                            <span className="text-[10px] font-bold text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded-full">
                                {tabsList.filter(t => clientPages[t]).length} Active
                            </span>
                        </div>
                        <div className="relative">
                            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                            <input
                                type="text"
                                placeholder="Search pages..."
                                value={searchTerm}
                                onChange={(e) => setSearchTerm(e.target.value)}
                                className="w-full pl-9 pr-4 py-2 bg-white border border-slate-200 rounded-xl text-xs font-medium focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 transition-all"
                            />
                        </div>
                    </div>

                    <div className="overflow-y-auto p-2 space-y-1 divide-y divide-slate-50 max-h-[580px]" style={{ scrollbarWidth: 'thin' }}>
                        {searchedPages.map((tab, idx) => {
                            const isPageActive = clientPages[tab] === true;
                            const isSelected = activePage === tab;
                            const PageIcon = TAB_ICON_MAP[tab] || BarChart3;
                            const totalKpis = getDynamicPageKpis(tab).length;
                            const enabledKpis = isPageActive ? getActiveKpiCount(tab) : 0;

                            return (
                                <div
                                    key={tab}
                                    onClick={() => isPageActive && setActivePage(tab)}
                                    className={`flex items-center justify-between p-3 rounded-xl transition-all cursor-pointer select-none group border border-transparent ${
                                        !isPageActive
                                            ? "opacity-40 cursor-not-allowed bg-slate-50/20"
                                            : isSelected
                                                ? "bg-indigo-50/80 border-indigo-100 text-indigo-700 shadow-sm"
                                                : "hover:bg-slate-50 text-slate-600 hover:text-slate-900"
                                    }`}
                                >
                                    <div className="flex items-center gap-3 min-w-0">
                                        <div className={`p-2 rounded-lg transition-colors ${
                                            isSelected 
                                                ? "bg-indigo-500 text-white" 
                                                : isPageActive 
                                                    ? "bg-slate-100 text-slate-500 group-hover:bg-indigo-50 group-hover:text-indigo-600" 
                                                    : "bg-slate-100 text-slate-400"
                                        }`}>
                                            <PageIcon className="w-4 h-4" />
                                        </div>
                                        <div className="text-left min-w-0">
                                            <p className={`text-xs font-bold leading-none mb-1 ${
                                                isSelected ? "text-indigo-900" : "text-slate-700"
                                            }`}>
                                                {tab}
                                            </p>
                                            <p className="text-[10px] text-slate-400 font-medium">
                                                {isPageActive ? `${enabledKpis} of ${totalKpis} KPIs enabled` : "Permission Disabled"}
                                            </p>
                                        </div>
                                    </div>

                                    {/* Action/Indicator status */}
                                    <div className="flex items-center">
                                        {isPageActive ? (
                                            <span className={`w-2 h-2 rounded-full ${
                                                isSelected ? "bg-indigo-600" : "bg-emerald-500"
                                            }`} />
                                        ) : (
                                            <Lock className="w-3 h-3 text-slate-400" />
                                        )}
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>

                {/* Right Side: KPIs Settings Container (Col 8) */}
                <div className="col-span-12 lg:col-span-8 space-y-4 min-h-[400px]">
                    <AnimatePresence mode="wait">
                        {activePage ? (
                            <motion.div
                                key={activePage + selectedDb}
                                initial={{ opacity: 0, x: 10 }}
                                animate={{ opacity: 1, x: 0 }}
                                exit={{ opacity: 0, x: -10 }}
                                transition={{ duration: 0.2 }}
                                className="space-y-4"
                            >
                                {/* Info card header */}
                                <div className="bg-white border border-slate-200 p-5 rounded-2xl shadow-sm flex flex-col sm:flex-row justify-between sm:items-center gap-4">
                                    <div className="flex items-center gap-4">
                                        <div
                                            className="w-12 h-12 rounded-xl flex items-center justify-center shadow-sm"
                                            style={{
                                                background: `linear-gradient(135deg, ${activePageGradient.from}15, ${activePageGradient.to}25)`,
                                                border: `1px solid ${activePageGradient.from}20`
                                            }}
                                        >
                                            {React.createElement(TAB_ICON_MAP[activePage] || BarChart3, {
                                                className: "w-6 h-6",
                                                style: { color: activePageGradient.from }
                                            })}
                                        </div>
                                        <div>
                                            <h3 className="text-base font-bold text-slate-800">{activePage} KPIs</h3>
                                            <p className="text-xs text-slate-400 font-medium">
                                                Showing KPIs configurable for <span className="font-bold text-slate-600 uppercase">{selectedDb}</span> {selectedUser && selectedUser !== 'all' ? `(User: ${selectedUser})` : '(All Users)'}
                                            </p>
                                        </div>
                                    </div>

                                    {/* Action Buttons */}
                                    <div className="flex items-center gap-2 flex-shrink-0">
                                        <button
                                            onClick={handleEnableAll}
                                            className="whitespace-nowrap px-3.5 py-2 bg-indigo-50 text-indigo-700 hover:bg-indigo-100 rounded-lg text-[10px] font-bold uppercase tracking-wider transition-colors"
                                        >
                                            Enable All
                                        </button>
                                        <button
                                            onClick={handleDisableAll}
                                            className="whitespace-nowrap px-3.5 py-2 bg-slate-100 text-slate-600 hover:bg-slate-200 rounded-lg text-[10px] font-bold uppercase tracking-wider transition-colors"
                                        >
                                            Disable All
                                        </button>
                                    </div>
                                </div>

                                {/* KPIs Grid */}
                                {selectedPageKpis.length > 0 ? (
                                    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4">
                                        {selectedPageKpis.map((kpi) => {
                                            const isEnabled = getKpiStatus(kpi.id);
                                            return (
                                                <div
                                                    key={kpi.id}
                                                    className={`bg-white border rounded-xl p-4 shadow-sm transition-all duration-300 relative flex items-center justify-between overflow-hidden ${
                                                        isEnabled 
                                                            ? "border-slate-200 hover:shadow-md hover:border-indigo-200" 
                                                            : "border-slate-100 opacity-60 bg-slate-50/50"
                                                    }`}
                                                >
                                                    {/* Gradient accent header */}
                                                    <div
                                                        className="absolute top-0 left-0 right-0 h-1"
                                                        style={{
                                                            background: isEnabled 
                                                                ? `linear-gradient(90deg, ${activePageGradient.from}, ${activePageGradient.to})`
                                                                : "#cbd5e1"
                                                        }}
                                                    />

                                                    {/* KPI Name */}
                                                    <span className="text-xs font-bold text-slate-800 capitalize leading-tight">
                                                        {kpi.label}
                                                    </span>

                                                    {/* Status Toggle Switch */}
                                                    <Switch
                                                        checked={isEnabled}
                                                        onChange={() => handleToggleKpi(kpi.id)}
                                                    />
                                                </div>
                                            );
                                        })}
                                    </div>
                                ) : (
                                    <div className="bg-white border border-slate-200 rounded-2xl p-12 text-center flex flex-col items-center justify-center gap-3">
                                        <BarChart3 className="w-8 h-8 text-slate-300" />
                                        <p className="text-xs font-bold text-slate-500">No KPIs defined for this tab</p>
                                        <p className="text-[10px] text-slate-400">KPI mapping for this dashboard module is currently under development.</p>
                                    </div>
                                )}
                            </motion.div>
                        ) : (
                            <div className="bg-white border border-slate-200 rounded-2xl p-12 text-center flex flex-col items-center justify-center gap-3 min-h-[400px]">
                                <Lock className="w-10 h-10 text-slate-300" />
                                <h3 className="text-sm font-bold text-slate-700">Access Restricted</h3>
                                <p className="text-xs text-slate-400 max-w-sm">
                                    Select an active page from the left rail to view and manage its component KPIs.
                                </p>
                            </div>
                        )}
                    </AnimatePresence>
                </div>

            </div>
        </div>
    );
};

export default ManageKpi;
