import React, { useState } from "react";
import {
  Drawer,
  Box,
  Typography,
  IconButton,
  Tabs,
  Tab,
  List,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  TextField,
  InputAdornment,
  Divider,
  Collapse,
} from "@mui/material";
import {
  Close as CloseIcon,
  Search as SearchIcon,
  Dashboard as DashboardIcon,
  Public as PublicIcon,
  ShoppingCart as ShoppingCartIcon,
  Visibility as VisibilityIcon,
  AutoGraph as AutoGraphIcon,
  PriceChange as PriceChangeIcon,
  AdsClick as AdsClickIcon,
  Article as ArticleIcon,
  Inventory as InventoryIcon,
  Schedule as ScheduleIcon,
  HelpOutline as HelpIcon,
  Add as AddIcon,
  Remove as RemoveIcon,
  TouchApp as UsageIcon,
  ErrorOutline as PitfallsIcon,
  Psychology as InterpretationIcon,
  EmojiObjects as ExampleIcon,
  Calculate as LogicIcon,
} from "@mui/icons-material";

import { useHelp } from "../../utils/HelpContext";

const HelpDrawer = ({ userDbName }) => {
  const { helpDrawerOpen, activeHelpMenu, closeHelp } = useHelp();
  const [activeTab, setActiveTab] = useState(0);
  const [activeMenu, setActiveMenu] = useState("Business Overview");
  const [expandedKpi, setExpandedKpi] = useState(null);
  const [searchQuery, setSearchQuery] = useState("");

  // Sync with context's activeHelpMenu when opening
  React.useEffect(() => {
    if (helpDrawerOpen && activeHelpMenu) {
      setActiveMenu(activeHelpMenu);
    }
  }, [helpDrawerOpen, activeHelpMenu]);

  const businessOverviewGlossary = [
    {
      kpi: "Offtake",
      definition: "The total sales value generated by a product or brand over a specified period.",
      usage: "Track demand and revenue generation.",
      interpretation: "Higher offtake → strong sales performance.",
      pitfalls: "Price vs volume confusion; double counting across SKUs.",
      example: "Brand sales = ₹5 Cr in last 30 days.",
      logic: "Sum(Sales Value)",
    },
    {
      kpi: "Availability",
      definition: "The proportion of stores or locations where a product is available for purchase at a given time.",
      usage: "Identify distribution gaps.",
      interpretation: "Higher availability → better reach.",
      pitfalls: "Ignoring OOS vs not listed; denominator issues.",
      example: "Available in 80 out of 100 stores → 80%.",
      logic: "(Available Stores ÷ Total Stores) × 100",
    },
    {
      kpi: "Share of Search (SOS)",
      definition: "The share of a brand’s presence within the top search results for relevant keywords or categories.",
      usage: "Measure digital shelf visibility.",
      interpretation: "Higher SOS → better discoverability.",
      pitfalls: "Not fixing shelf size; ignoring rank importance.",
      example: "4 SKUs in top 10 → 40%.",
      logic: "(Brand SKUs in Top N ÷ N) × 100",
    },
    {
      kpi: "Market Share",
      definition: "The percentage of total category sales contributed by a brand.",
      usage: "Track competitive position.",
      interpretation: "Higher share → stronger market presence.",
      pitfalls: "Crawl time variations.",
      example: "₹1 Cr / ₹5 Cr → 20%.",
      logic: "(Brand Sales ÷ Category Sales) × 100",
    },
    {
      kpi: "Promo",
      definition: "A price reduction or special offer applied to a product to encourage customer purchases.",
      usage: "Evaluate promo effectiveness.",
      interpretation: "High promo → deal-driven demand → High sales.",
      pitfalls: "Over-reliance reduces margins.",
      example: "₹2 Cr out of ₹5 Cr under discount.",
      logic: "(MRP - Selling Price)/ MRP",
    },
    {
      kpi: "Inorganic Sales",
      definition: "Sales generated through paid channels, including advertisements and sponsored placements.",
      usage: "Measure paid contribution.",
      interpretation: "High inorganic → dependency on ads.",
      pitfalls: "Depends upon keyword targeting",
      example: "₹1.5 Cr via ads.",
      logic: "Sum(Ad Sales Value)",
    },
    {
      kpi: "Conversion",
      definition: "The rate at which user interactions (such as clicks or views) result in a purchase.",
      usage: "Evaluate funnel efficiency.",
      interpretation: "Higher conversion → strong product appeal.",
      pitfalls: "",
      example: "500 orders from 10,000 clicks → 5%.",
      logic: "(Orders ÷ Clicks) × 100",
    },
    {
      kpi: "ROAS (Return on Ad Spend)",
      definition: "The revenue generated for every unit of advertising spend.",
      usage: "Measure ad efficiency.",
      interpretation: "Higher ROAS → profitable campaigns.",
      pitfalls: "",
      example: "₹5 revenue on ₹1 spend → ROAS = 5.",
      logic: "Revenue ÷ Ad Spend",
    },
    {
      kpi: "Orders",
      definition: "The total number of completed purchase transactions within a given period.",
      usage: "Track demand volume.",
      interpretation: "Higher orders → higher demand.",
      pitfalls: "Duplicate orders; cancellations not excluded.",
      example: "2,000 orders in a week.",
      logic: "Count of Orders",
    },
    {
      kpi: "Spend",
      definition: "The total investment made in advertising and promotional activities.",
      usage: "Budget tracking.",
      interpretation: "Higher spend → higher investment.",
      pitfalls: "",
      example: "₹50,000 ad spend.",
      logic: "Sum(Ad Spend)",
    },
    {
      kpi: "Category Size",
      definition: "The total sales value of all products within a specific category over a defined period.",
      usage: "Assess market opportunity.",
      interpretation: "Larger size → higher potential.",
      pitfalls: "Crawl time variations.",
      example: "₹10 Cr estimated category sales.",
      logic: "Total Category Sales",
    },
    {
      kpi: "Sponsored SOS",
      definition: "The proportion of a brand’s product visibility within sponsored or paid placements in search results.",
      usage: "Track effectiveness of paid visibility strategy.",
      interpretation: "Higher Sponsored SOS → strong paid dominance.",
      pitfalls: "",
      example: "Out of 4 slots, 2 are sponsored listings of brand → 50%.",
      logic: "Sponsored SOS = (Sponsored Brand Appearances ÷ N) × 100",
    },
    {
      kpi: "Organic SOS",
      definition: "The proportion of a brand’s product visibility within organic (non-paid) search results.",
      usage: "Measure natural ranking and SEO performance.",
      interpretation: "Higher Organic SOS → strong organic discoverability.",
      pitfalls: "",
      example: "Out of 6 slots, 2 organic brand listings → 33%.",
      logic: "Organic SOS = (Organic Brand Appearances ÷ N) × 100",
    },
    {
      kpi: "CPM (Cost per Mille)",
      definition: "The cost incurred to generate one thousand impressions.",
      usage: "Measure cost efficiency.",
      interpretation: "Lower CPM → cheaper reach.",
      pitfalls: "Not comparing across campaigns.",
      example: "₹200 for 10,000 impressions → CPM = ₹20.",
      logic: "(Spend ÷ Impressions) × 1000",
    },
    {
      kpi: "CPC (Cost per Click)",
      definition: "The cost incurred for each user click on an advertisement.",
      usage: "Measure traffic cost.",
      interpretation: "Lower CPC → efficient clicks.",
      pitfalls: "",
      example: "₹1,000 spend for 500 clicks → ₹2 CPC.",
      logic: "Spend ÷ Clicks",
    },
    {
      kpi: "Impressions",
      definition: "The total number of times a product or advertisement is displayed to users.",
      usage: "Measure reach.",
      interpretation: "Higher impressions → higher visibility.",
      pitfalls: "",
      example: "1,00,000 impressions.",
      logic: "Count of Impressions",
    },
    {
      kpi: "Clicks",
      definition: "The total number of times users interact with a product or advertisement by clicking on it.",
      usage: "Measure engagement.",
      interpretation: "Higher clicks → higher interest.",
      pitfalls: "Bot clicks.",
      example: "5,000 clicks.",
      logic: "Count of Clicks",
    },
    {
      kpi: "CTR (Click-Through Rate)",
      definition: "The percentage of impressions that result in user clicks.",
      usage: "Measure ad effectiveness.",
      interpretation: "Higher CTR → better creatives/targeting.",
      pitfalls: "High CTR but low conversion.",
      example: "5,000 clicks / 1,00,000 impressions = 5%.",
      logic: "(Clicks ÷ Impressions) × 100",
    },
  ];

  const indiaOverviewGlossary = [
    {
      kpi: "Wt. OSA (Weighted On-Shelf Availability)",
      definition: "Measures product availability weighted by its importance (e.g., sales contribution or store weight).",
      usage: "Identify availability gaps for high-impact SKUs.",
      interpretation: "Higher Wt. OSA → key products are consistently available; low → revenue loss risk.",
      pitfalls: "Treating all SKUs equally; ignoring SKU importance; wrong weighting logic.",
      example: "If top-selling SKUs (70% sales contribution) have 90% availability, Wt. OSA reflects higher availability impact vs low-selling SKUs.",
      logic: "Σ(Availability × Weight) ÷ Σ(Weight) (Weight = sales/store importance)",
    },
    {
      kpi: "Listing %",
      definition: "% of total possible SKUs that are listed on the platform/store.",
      usage: "Track distribution and assortment presence.",
      interpretation: "Higher listing → better product coverage.",
      pitfalls: "Counting inactive SKUs; mismatch in total SKU universe.",
      example: "80 listed SKUs out of 100 total → 80%.",
      logic: "(Listed SKUs ÷ Total Possible SKUs) × 100",
    },
    {
      kpi: "Market Share",
      definition: "The percentage of total category sales contributed by a brand.",
      usage: "Track competitive position.",
      interpretation: "Higher share → stronger market presence.",
      pitfalls: "Crawl time variations.",
      example: "₹1 Cr / ₹5 Cr → 20%.",
      logic: "(Brand Sales ÷ Category Size) × 100",
    },
    {
      kpi: "Sales",
      definition: "The total sales value generated by a product or brand over a specified period.",
      usage: "Track demand and revenue generation.",
      interpretation: "Higher offtake → strong sales performance.",
      pitfalls: "Price vs volume confusion; double counting across SKUs.",
      example: "Brand sales = ₹5 Cr in last 30 days.",
      logic: "Sum(Sales Value)",
    },
    {
      kpi: "Orders",
      definition: "The total number of completed purchase transactions within a given period.",
      usage: "Track demand volume.",
      interpretation: "Higher orders → higher demand.",
      pitfalls: "Duplicate orders; cancellations not excluded.",
      example: "2,000 orders in a week.",
      logic: "Count of Orders",
    },
  ];

  const availabilityAnalysisGlossary = [
    {
      kpi: "Stock Availability",
      definition: "The proportion of stores or locations where a product is available for purchase at a given time.",
      usage: "Identify distribution gaps.",
      interpretation: "Higher availability → better reach.",
      pitfalls: "Ignoring OOS vs not listed; denominator issues.",
      example: "Available in 80 out of 100 stores → 80%.",
      logic: "(Available Stores ÷ Total Stores) × 100",
    },
    {
      kpi: "Days of Inventory (DOI)",
      definition: "The number of days current inventory is expected to last based on the recent sales trend (last 30 days).",
      usage: "Monitor inventory health and plan replenishment.",
      interpretation: "Lower DOI indicates risk of stockout; higher DOI indicates excess inventory.",
      pitfalls: "Using incorrect time window; not updating sales data; division errors when sales = 0.",
      example: "Current Inventory = 3,000 units; Last 30 days sales = 1,500 units → DOI = 60 days.",
      logic: "DOI = (Current Inventory ÷ Last 30 Days Qty Sold) × 30",
    },
    {
      kpi: "Metro City Stock Availability",
      definition: "The proportion of stores or locations where a product is available for purchase at a given time for metro cities.",
      usage: "Identify distribution gaps in metro cities.",
      interpretation: "Higher availability → better reach.",
      pitfalls: "Ignoring OOS vs not listed; denominator issues.",
      example: "Available in 80 out of 100 stores → 80%.",
      logic: "(Available Stores ÷ Total Stores) × 100",
    },
    {
      kpi: "PSL (Potential Sales Loss)",
      definition: "The estimated sales loss due to unavailability, derived by comparing actual sales with expected sales adjusted for availability (OSA).",
      usage: "Identify sales loss caused by stockouts and availability gaps.",
      interpretation: "Higher PSL gap indicates greater loss due to poor availability; lower gap indicates efficient stock availability.",
      pitfalls: "Incorrect OSA calculation; division errors when OSA is very low; misinterpreting PSL as fulfilled demand.",
      example: "Sales = 1,000 units; Avg OSA = 80% → Expected Sales = 1,250 → PSL Loss = 250 units.",
      logic: "(Sales ÷ Avg OSA) − Sales",
    },
    {
      kpi: "SOH (Stock on Hand)",
      definition: "Total inventory available at a given point in time.",
      usage: "Monitor current inventory levels.",
      interpretation: "Higher SOH → more stock; too high → holding cost risk.",
      pitfalls: "Not excluding reserved/damaged stock; duplication across locations.",
      example: "8,000 units available in warehouse.",
      logic: "Sum of Current Inventory Units",
    },
    {
      kpi: "Wt. OSA% (Weighted On-Shelf Availability)",
      definition: "Measures product availability weighted by its importance (e.g., sales contribution or store weight).",
      usage: "Identify availability gaps for high-impact SKUs.",
      interpretation: "Higher Wt. OSA → key products are consistently available; low → revenue loss risk.",
      pitfalls: "Treating all SKUs equally; ignoring SKU importance; wrong weighting logic.",
      example: "If top-selling SKUs (70% sales contribution) have 90% availability, Wt. OSA reflects higher availability impact vs low-selling SKUs.",
      logic: "Σ(Availability × Weight) ÷ Σ(Weight) (Weight = sales/store importance)",
    },
    {
      kpi: "Offtake Share",
      definition: "Product/Category's contribution to total sales.",
      usage: "Track SKU performance within category/brand.",
      interpretation: "Higher share → strong consumer demand.",
      pitfalls: "",
      example: "Category sales ₹2 Cr out of ₹10 Cr brand → 20%.",
      logic: "(Brand Offtake ÷ Total Category Offtake) × 100",
    },
  ];

  const marketShareGlossary = [
    {
      kpi: "Category Size",
      definition: "The total sales value of all products within a specific category over a defined period.",
      usage: "Assess market opportunity.",
      interpretation: "Larger size → higher potential.",
      pitfalls: "Crawl time variations.",
      example: "₹10 Cr estimated category sales.",
      logic: "Total Category Sales",
    },
    {
      kpi: "Market Leader Sales",
      definition: "Total sales of the top-performing brand in the category from estimated sales.",
      usage: "Identify benchmark competitor and performance gap.",
      interpretation: "Higher leader sales → strong dominance.",
      pitfalls: "Incorrect leader identification due to time window/data gaps.",
      example: "Brand A has highest sales of ₹3 Cr in category.",
      logic: "Max(Brand Sales across category)",
    },
    {
      kpi: "Brand Estimated Sales",
      definition: "The total sales value generated by a product or brand from estimated sales.",
      usage: "Track demand and revenue generation.",
      interpretation: "Higher offtake → strong sales performance.",
      pitfalls: "Price vs volume confusion; double counting across SKUs.",
      example: "Brand sales = ₹5 Cr in last 30 days.",
      logic: "Sum(Sales Value)",
    },
    {
      kpi: "Market Share %",
      definition: "The percentage of total category sales contributed by a brand.",
      usage: "Track competitive position.",
      interpretation: "Higher share → stronger market presence.",
      pitfalls: "Crawl time variations.",
      example: "₹1 Cr / ₹5 Cr → 20%.",
      logic: "(Brand Sales ÷ Category Sales) × 100",
    },
    {
      kpi: "Overall Share of Visibility",
      definition: "The proportion of a brand’s product visibility within the top search results, including both organic and sponsored placements.",
      usage: "Measure overall digital shelf visibility across search results.",
      interpretation: "Higher SOS → strong overall presence; lower → poor discoverability.",
      pitfalls: "",
      example: "If 10 slots in top results and brand appears in 5 (3 organic + 2 sponsored) → SOS = 50%.",
      logic: "(Total Brand Appearances in Top N ÷ N) × 100",
    },
    {
      kpi: "Paid Share of Visibility",
      definition: "The proportion of a brand’s product visibility within sponsored or paid placements in search results.",
      usage: "Track effectiveness of paid visibility strategy.",
      interpretation: "Higher Sponsored SOS → strong paid dominance.",
      pitfalls: "",
      example: "Out of 4 slots, 2 are sponsored listings of brand → 50%.",
      logic: "(Sponsored Brand Appearances ÷ N) × 100",
    },
  ];

  const visibilityAnalysisGlossary = [
    {
      kpi: "Overall SOS (Share of Search)",
      definition: "The proportion of a brand’s product visibility within the top search results, including both organic and sponsored placements.",
      usage: "Measure overall digital shelf visibility across search results.",
      interpretation: "Higher SOS → strong overall presence; lower → poor discoverability.",
      pitfalls: "",
      example: "If 10 slots in top results and brand appears in 5 (3 organic + 2 sponsored) → SOS = 50%.",
      logic: "Overall SOS = (Total Brand Appearances in Top N ÷ N) × 100",
    },
    {
      kpi: "Sponsored SOS",
      definition: "The proportion of a brand’s product visibility within sponsored or paid placements in search results.",
      usage: "Track effectiveness of paid visibility strategy.",
      interpretation: "Higher Sponsored SOS → strong paid dominance.",
      pitfalls: "",
      example: "Out of 4 slots, 2 are sponsored listings of brand → 50%.",
      logic: "Sponsored SOS = (Sponsored Brand Appearances ÷ N) × 100",
    },
    {
      kpi: "Organic SOS",
      definition: "The proportion of a brand’s product visibility within organic (non-paid) search results.",
      usage: "Measure natural ranking and SEO performance.",
      interpretation: "Higher Organic SOS → strong organic discoverability.",
      pitfalls: "",
      example: "Out of 6 slots, 2 organic brand listings → 33%.",
      logic: "Organic SOS = (Organic Brand Appearances ÷ N) × 100",
    },
  ];

  const performanceMarketingGlossary = [
    {
      kpi: "Impressions",
      definition: "The total number of times a product or advertisement is displayed to users.",
      usage: "Measure reach.",
      interpretation: "Higher impressions → higher visibility.",
      pitfalls: "",
      example: "1,00,000 impressions.",
      logic: "Count of Impressions",
    },
    {
      kpi: "Conversion",
      definition: "The rate at which user interactions (such as clicks or views) result in a purchase.",
      usage: "Evaluate funnel efficiency.",
      interpretation: "Higher conversion → strong product appeal.",
      pitfalls: "",
      example: "500 orders from 10,000 clicks → 5%.",
      logic: "(Orders ÷ Clicks) × 100",
    },
    {
      kpi: "Spend",
      definition: "The total investment made in advertising and promotional activities.",
      usage: "Budget tracking.",
      interpretation: "Higher spend → higher investment.",
      pitfalls: "",
      example: "₹50,000 ad spend.",
      logic: "Sum(Ad Spend)",
    },
    {
      kpi: "ROAS",
      definition: "The revenue generated for every unit of advertising spend.",
      usage: "Measure ad efficiency.",
      interpretation: "Higher ROAS → profitable campaigns.",
      pitfalls: "",
      example: "₹5 revenue on ₹1 spend → ROAS = 5.",
      logic: "Revenue ÷ Ad Spend",
    },
    {
      kpi: "CPM",
      definition: "The cost incurred to generate one thousand impressions.",
      usage: "Measure cost efficiency.",
      interpretation: "Lower CPM → cheaper reach.",
      pitfalls: "Not comparing across campaigns.",
      example: "₹200 for 10,000 impressions → CPM = ₹20.",
      logic: "(Spend ÷ Impressions) × 1000",
    },
    {
      kpi: "Sales",
      definition: "The total sales value generated by a product or brand over a specified period.",
      usage: "Track demand and revenue generation.",
      interpretation: "Higher offtake → strong sales performance.",
      pitfalls: "Price vs volume confusion; double counting across SKUs.",
      example: "Brand sales = ₹5 Cr in last 30 days.",
      logic: "Sum(Sales Value)",
    },
    {
      kpi: "Inorganic Sales",
      definition: "Sales generated through paid channels, including advertisements and sponsored placements.",
      usage: "Measure paid contribution.",
      interpretation: "High inorganic → dependency on ads.",
      pitfalls: "Depends upon keyword targeting",
      example: "₹1.5 Cr via ads.",
      logic: "Sum(Ad Sales Value)",
    },
  ];

  const GlossarySection = ({ title, text, icon, bgColor, borderColor, textColor }) => {
    if (!text) return null;
    return (
      <Box
        sx={{
          p: 1.5,
          mb: 1.5,
          bgcolor: bgColor,
          borderRadius: "12px",
          border: `1px solid ${borderColor}`,
          display: "flex",
          gap: 1.5,
        }}
      >
        <Box sx={{ color: textColor, mt: 0.2 }}>{icon}</Box>
        <Box>
          <Typography variant="caption" fontWeight="700" sx={{ color: textColor, textTransform: "uppercase", display: "block", mb: 0.5 }}>
            {title}
          </Typography>
          <Typography variant="body2" sx={{ color: "#475569", fontSize: "0.775rem", lineHeight: 1.5 }}>
            {text}
          </Typography>
        </Box>
      </Box>
    );
  };

  const menuItems = [
    { label: "Business Overview", icon: <DashboardIcon sx={{ fontSize: "1.1rem" }} /> },
    { label: "India Overview", icon: <PublicIcon sx={{ fontSize: "1rem" }} /> },
    { label: "Availability Analysis", icon: <ShoppingCartIcon sx={{ fontSize: "1rem" }} /> },
    { label: "Visibility Analysis", icon: <VisibilityIcon sx={{ fontSize: "1rem" }} /> },
    { label: "Market Share", icon: <AutoGraphIcon sx={{ fontSize: "1rem" }} />, hideForDb: ["boat", "mars_petcare"] },
    { label: "Pricing Analysis", icon: <PriceChangeIcon sx={{ fontSize: "1rem" }} />, hideForDb: ["mamaearth"] },
    { label: "Performance Marketing", icon: <AdsClickIcon sx={{ fontSize: "1rem" }} />, hideForDb: ["mamaearth", "boat"] },
    { label: "Content Analysis", icon: <ArticleIcon sx={{ fontSize: "1rem" }} />, showOnlyForDb: ["mars"] },
    { label: "Inventory Analysis", icon: <InventoryIcon sx={{ fontSize: "1rem" }} />, hideForDb: ["mamaearth", "boat"] },
    { label: "Scheduled Reports", icon: <ScheduleIcon sx={{ fontSize: "1rem" }} /> },
  ];

  const filteredMenuItems = menuItems.filter((item) => {
    if (item.showOnlyForDb && !item.showOnlyForDb.includes(userDbName)) return false;
    if (item.hideForDb && item.hideForDb.includes(userDbName)) return false;
    return true;
  });

  const getGlossarySource = () => {
    switch (activeMenu) {
      case "India Overview":
        return indiaOverviewGlossary;
      case "Availability Analysis":
        return availabilityAnalysisGlossary;
      case "Market Share":
        return marketShareGlossary;
      case "Visibility Analysis":
        return visibilityAnalysisGlossary;
      case "Performance Marketing":
        return performanceMarketingGlossary;
      default:
        return businessOverviewGlossary;
    }
  };

  const filteredGlossary = getGlossarySource().filter((item) => {
    if (!searchQuery) return true;
    const q = searchQuery.toLowerCase();
    return (
      item.kpi.toLowerCase().includes(q) ||
      item.definition.toLowerCase().includes(q) ||
      (item.usage && item.usage.toLowerCase().includes(q)) ||
      (item.interpretation && item.interpretation.toLowerCase().includes(q))
    );
  });

  const handleTabChange = (event, newValue) => {
    setActiveTab(newValue);
  };

  return (
    <Drawer
      anchor="right"
      open={helpDrawerOpen}
      onClose={closeHelp}
      PaperProps={{
        sx: {
          width: { xs: "100%", sm: "70vw", md: "60vw", lg: "50vw" },
          bgcolor: "#f8fafc",
          borderLeft: "1px solid #e2e8f0",
          boxShadow: "-4px 0 20px rgba(0,0,0,0.05)",
        },
      }}
    >
      {/* Header */}
      <Box
        sx={{
          p: 2,
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          bgcolor: "#ffffff",
          borderBottom: "1px solid #e2e8f0",
          position: "sticky",
          top: 0,
          zIndex: 10,
        }}
      >
        <Box sx={{ display: "flex", alignItems: "center", gap: 1.5 }}>
          <Box
            sx={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              width: 36,
              height: 36,
              borderRadius: "10px",
              bgcolor: "rgba(37, 99, 235, 0.1)",
              color: "#2563eb",
            }}
          >
            <HelpIcon />
          </Box>
          <Typography variant="h6" fontWeight="700" sx={{ color: "#1e293b", fontSize: "1.0rem" }}>
            Let's Get Started
          </Typography>
        </Box>

        <Box sx={{ display: "flex", alignItems: "center", gap: 2 }}>
          <TextField
            size="small"
            placeholder="Search help..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            sx={{
              width: { xs: 150, sm: 250 },
              "& .MuiOutlinedInput-root": {
                borderRadius: "20px",
                bgcolor: "#f1f5f9",
                "& fieldset": { border: "none" },
              },
            }}
            InputProps={{
              startAdornment: (
                <InputAdornment position="start">
                  <SearchIcon sx={{ color: "#64748b", fontSize: "1.2rem" }} />
                </InputAdornment>
              ),
            }}
          />
          <IconButton onClick={closeHelp} size="small" sx={{ color: "#64748b", "&:hover": { bgcolor: "#f1f5f9" } }}>
            <CloseIcon />
          </IconButton>
        </Box>
      </Box>

      {/* Main Content Area */}
      <Box sx={{ display: "flex", flex: 1, overflow: "hidden" }}>
        {/* Help Sidebar */}
        <Box
          sx={{
            width: 210,
            borderRight: "1px solid #e2e8f0",
            bgcolor: "#ffffff",
            display: "flex",
            flexDirection: "column",
            overflowY: "auto",
          }}
        >
          <Box sx={{ p: 2, pb: 1 }}>
            <Typography
              variant="overline"
              sx={{ fontSize: "0.7rem", fontWeight: 700, color: "#94a3b8", letterSpacing: "0.05em" }}
            >
              MODULES
            </Typography>
          </Box>
          <List sx={{ px: 1 }}>
            {filteredMenuItems.map((item) => (
              <ListItemButton
                key={item.label}
                selected={activeMenu === item.label}
                onClick={() => setActiveMenu(item.label)}
                sx={{
                  borderRadius: "8px",
                  mb: 0.5,
                  py: 1,
                  "&.Mui-selected": {
                    bgcolor: "rgba(37, 99, 235, 0.08)",
                    color: "#2563eb",
                    "& .MuiListItemIcon-root": { color: "#2563eb" },
                    "&:hover": { bgcolor: "rgba(37, 99, 235, 0.12)" },
                  },
                }}
              >
                <ListItemIcon sx={{ minWidth: 36, color: "#64748b" }}>{item.icon}</ListItemIcon>
                <ListItemText
                  primary={item.label}
                  primaryTypographyProps={{
                    fontSize: "0.825rem",
                    fontWeight: activeMenu === item.label ? 600 : 500,
                  }}
                />
              </ListItemButton>
            ))}
          </List>
        </Box>

        {/* Content Tabs & View */}
        <Box sx={{ flex: 1, display: "flex", flexDirection: "column", bgcolor: "#f8fafc" }}>
          <Box sx={{ px: 3, bgcolor: "#ffffff", borderBottom: "1px solid #e2e8f0" }}>
            <Tabs
              value={activeTab}
              onChange={handleTabChange}
              sx={{
                "& .MuiTabs-indicator": { height: 3, borderRadius: "3px 3px 0 0", bgcolor: "#2563eb" },
              }}
            >
              <Tab
                label="Glossary"
                sx={{
                  textTransform: "none",
                  fontWeight: 600,
                  fontSize: "0.875rem",
                  minWidth: 100,
                  color: "#64748b",
                  "&.Mui-selected": { color: "#2563eb" },
                }}
              />
            </Tabs>
          </Box>

          <Box sx={{ flex: 1, p: 3, overflowY: "auto" }}>
            <Box>
              <Box sx={{ display: 'grid', gap: 2 }}>
                {["Business Overview", "India Overview", "Availability Analysis", "Market Share", "Visibility Analysis", "Performance Marketing"].includes(activeMenu) ? (
                  filteredGlossary.map((item) => {
                    const isExpanded = expandedKpi === item.kpi;
                    return (
                      <Box
                        key={item.kpi}
                        sx={{
                          bgcolor: "#ffffff",
                          borderRadius: "12px",
                          border: `1px solid ${isExpanded ? "#2563eb" : "#e2e8f0"}`,
                          boxShadow: isExpanded ? "0 4px 12px rgba(37, 99, 235, 0.06)" : "0 1px 3px rgba(0,0,0,0.02)",
                          transition: "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
                          overflow: "hidden",
                          "&:hover": {
                            borderColor: "#cbd5e1",
                            boxShadow: "0 4px 12px rgba(0,0,0,0.04)"
                          }
                        }}
                      >
                        <ListItemButton
                          onClick={() => setExpandedKpi(isExpanded ? null : item.kpi)}
                          sx={{
                            p: 2,
                            alignItems: "flex-start",
                            gap: 2,
                            "&:hover .kpi-title": {
                              color: "#2563eb",
                              transform: "translateX(4px)"
                            }
                          }}
                        >
                          <Box sx={{ flex: 1 }}>
                            <Typography
                              className="kpi-title"
                              fontWeight="700"
                              sx={{
                                color: isExpanded ? "#2563eb" : "#1e293b",
                                fontSize: "0.95rem",
                                mb: 0.5,
                                transition: "all 0.2s ease"
                              }}
                            >
                              {item.kpi}
                            </Typography>
                            <Typography variant="body2" sx={{ color: "#64748b", fontSize: "0.825rem", lineHeight: 1.5 }}>
                              {item.definition}
                            </Typography>
                          </Box>
                          <Box sx={{ color: "#2563eb", mt: 0.5 }}>
                            {isExpanded ? <RemoveIcon /> : <AddIcon />}
                          </Box>
                        </ListItemButton>

                        <Collapse in={isExpanded}>
                          <Box sx={{ p: 2, pt: 0 }}>
                            <GlossarySection
                              title="Usage"
                              text={item.usage}
                              icon={<UsageIcon fontSize="small" />}
                              bgColor="#f0f9ff"
                              borderColor="#bae6fd"
                              textColor="#0369a1"
                            />
                            <GlossarySection
                              title="Common Pitfalls"
                              text={item.pitfalls}
                              icon={<PitfallsIcon fontSize="small" />}
                              bgColor="#fef2f2"
                              borderColor="#fecaca"
                              textColor="#b91c1c"
                            />
                            <GlossarySection
                              title="Interpretation"
                              text={item.interpretation}
                              icon={<InterpretationIcon fontSize="small" />}
                              bgColor="#faf5ff"
                              borderColor="#e9d5ff"
                              textColor="#7e22ce"
                            />
                            <GlossarySection
                              title="Example"
                              text={item.example}
                              icon={<ExampleIcon fontSize="small" />}
                              bgColor="#fffbeb"
                              borderColor="#fef3c7"
                              textColor="#b45309"
                            />
                            <GlossarySection
                              title="Logic / Calculation"
                              text={item.logic}
                              icon={<LogicIcon fontSize="small" />}
                              bgColor="#f0fdf4"
                              borderColor="#bbf7d0"
                              textColor="#15803d"
                            />
                          </Box>
                        </Collapse>
                      </Box>
                    );
                  })
                ) : (
                  <Box sx={{ textAlign: 'center', py: 8 }}>
                    <Typography sx={{ color: "#64748b" }}>
                      Glossary content for {activeMenu} is coming soon.
                    </Typography>
                  </Box>
                )}
              </Box>
            </Box>
          </Box>
        </Box>
      </Box>
    </Drawer>
  );
};

export default HelpDrawer;
