export const datasets = {
    visibility: {
        label: "Visibility Analysis",
        fields: [
            { key: "platform", label: "Platform", type: "dimension", description: "E-commerce Platform" },
            { key: "city", label: "City", type: "dimension", description: "Metro City" },
            { key: "category", label: "Category", type: "dimension", description: "Product Category" },
            { key: "brand", label: "Brand", type: "dimension", description: "Brand Name" },
            { key: "sos_weighted", label: "Weighted SOS", type: "measure", description: "Share of Shelf (Weighted)" },
            { key: "facings", label: "Total Facings", type: "measure", description: "Number of visual facings" },
            { key: "compliance", label: "Compliance Score", type: "measure", description: "Planogram Compliance" },
        ],
        initialConfig: {
            rows: ["city", "platform"],
            columns: ["brand"],
            values: [
                { id: "sos-avg", key: "sos_weighted", label: "Avg SOS %", agg: "avg", format: "percent" },
                { id: "facings-sum", key: "facings", label: "Total Facings", agg: "sum", format: "compact" },
            ],
            filters: {},
        },
        data: [
            { platform: "Blinkit", city: "Mumbai", category: "Ice Cream", brand: "Kwality Wall's", sos_weighted: 0.45, facings: 120, compliance: 92 },
            { platform: "Blinkit", city: "Mumbai", category: "Ice Cream", brand: "Amul", sos_weighted: 0.30, facings: 80, compliance: 85 },
            { platform: "Blinkit", city: "Mumbai", category: "Ice Cream", brand: "Vadilal", sos_weighted: 0.15, facings: 40, compliance: 78 },
            { platform: "Blinkit", city: "Delhi", category: "Ice Cream", brand: "Kwality Wall's", sos_weighted: 0.42, facings: 110, compliance: 88 },
            { platform: "Zepto", city: "Bangalore", category: "Snacks", brand: "Lays", sos_weighted: 0.55, facings: 200, compliance: 98 },
            { platform: "Swiggy Instamart", city: "Hyderabad", category: "Beverages", brand: "Pepsi", sos_weighted: 0.40, facings: 150, compliance: 90 },
            { platform: "Amazon", city: "Pune", category: "Pantry", brand: "Fortune", sos_weighted: 0.20, facings: 50, compliance: 80 },
            { platform: "Bigbasket", city: "Chennai", category: "Dairy", brand: "Amul", sos_weighted: 0.60, facings: 300, compliance: 95 },
            { platform: "Blinkit", city: "Kolkata", category: "Personal Care", brand: "Dove", sos_weighted: 0.25, facings: 60, compliance: 88 },
        ],
    },
    availability: {
        label: "Availability Analysis",
        fields: [
            { key: "platform", label: "Platform", type: "dimension", description: "Platform Name" },
            { key: "zone", label: "Zone", type: "dimension", description: "Geographic Zone" },
            { key: "sku", label: "SKU Name", type: "dimension", description: "Product SKU" },
            { key: "time_slot", label: "Time Slot", type: "dimension", description: "Time of Day" },
            { key: "total_pings", label: "Total Checks", type: "measure", description: "Availability Pings" },
            { key: "available_pings", label: "Available Pings", type: "measure", description: "Successful Pings" },
            { key: "lost_revenue", label: "Lost Revenue", type: "measure", description: "Revenue Opportunity Lost" },
        ],
        initialConfig: {
            rows: ["platform", "sku"],
            columns: ["zone"],
            values: [
                {
                    id: "osa-calc",
                    key: "available_pings",
                    denominatorKey: "total_pings",
                    label: "OSA % (Calc)",
                    agg: "sum",
                    calc: "ratio",
                },
                { id: "lost_revenue-sum", key: "lost_revenue", label: "Lost Revenue", agg: "sum", format: "currency" },
            ],
            filters: {},
        },
        data: [
            { platform: "Blinkit", zone: "North", sku: "Cornetto Double Choc", time_slot: "Morning", total_pings: 100, available_pings: 98, lost_revenue: 500 },
            { platform: "Blinkit", zone: "North", sku: "Cornetto Double Choc", time_slot: "Evening", total_pings: 100, available_pings: 85, lost_revenue: 2500 },
            { platform: "Zepto", zone: "West", sku: "Magnum Classic", time_slot: "Morning", total_pings: 100, available_pings: 95, lost_revenue: 0 },
            { platform: "Instamart", zone: "South", sku: "Tubs Vanilla", time_slot: "Afternoon", total_pings: 100, available_pings: 92, lost_revenue: 1200 },
        ],
    },
    sales: {
        label: "Sales Data",
        fields: [
            { key: "platform", label: "Platform", type: "dimension", description: "Sales Channel" },
            { key: "city", label: "City", type: "dimension", description: "City" },
            { key: "category", label: "Category", type: "dimension", description: "Product Category" },
            { key: "mtd_sales", label: "MTD Sales", type: "measure", description: "Month to Date Sales (INR)" },
            { key: "target", label: "Target Sales", type: "measure", description: "Sales Target" },
        ],
        initialConfig: {
            rows: ["platform", "city"],
            columns: ["category"],
            values: [
                { id: "mtd_sales-sum", key: "mtd_sales", label: "MTD Sales", agg: "sum", format: "compact" },
                {
                    id: "achievement-calc",
                    key: "mtd_sales",
                    denominatorKey: "target",
                    label: "Achievement",
                    agg: "sum",
                    calc: "ratio",
                },
            ],
            filters: {},
        },
        data: [
            { platform: "Flipkart", city: "Delhi", category: "Electronics", mtd_sales: 1500000, target: 1200000 },
            { platform: "Amazon", city: "Mumbai", category: "Home", mtd_sales: 1200000, target: 1500000 },
            { platform: "Zepto", city: "Mumbai", category: "Grocery", mtd_sales: 500000, target: 450000 },
            { platform: "Blinkit", city: "Gurgaon", category: "Grocery", mtd_sales: 800000, target: 700000 },
        ],
    },
    inventory: {
        label: "Inventory Management",
        fields: [
            { key: "warehouse", label: "Warehouse", type: "dimension", description: "Warehouse Location" },
            { key: "stock_status", label: "Stock Status", type: "dimension", description: "Availability Status" },
            { key: "stock_value", label: "Stock Value", type: "measure", description: "Value of Stock (INR)" },
            { key: "sku_id", label: "SKU ID", type: "dimension", description: "Unique Product ID" },
        ],
        initialConfig: {
            rows: ["warehouse"],
            columns: ["stock_status"],
            values: [
                { id: "stock_value-sum", key: "stock_value", label: "Total Value", agg: "sum", format: "currency" },
                { id: "sku-unique", key: "sku_id", label: "Unique SKUs", agg: "distinctCount", format: "number" },
            ],
            filters: {},
        },
        data: [
            { warehouse: "WH-Bhiwandi", stock_status: "Available", stock_value: 5000000, sku_id: "SKU-001" },
            { warehouse: "WH-Bhiwandi", stock_status: "Available", stock_value: 2000000, sku_id: "SKU-002" },
            { warehouse: "WH-Bhiwandi", stock_status: "Reserved", stock_value: 1000000, sku_id: "SKU-003" },
            { warehouse: "WH-Bilaspur", stock_status: "Available", stock_value: 8000000, sku_id: "SKU-001" },
            { warehouse: "WH-Bilaspur", stock_status: "Available", stock_value: 8000000, sku_id: "SKU-004" },
        ],
    },
    performanceMarketing: {
        label: "Performance Marketing",
        fields: [
            { key: "platform", label: "Platform", type: "dimension", description: "Ad Platform" },
            { key: "campaign", label: "Campaign", type: "dimension", description: "Campaign Name" },
            { key: "spend", label: "Spend", type: "measure", description: "Ad Spend" },
            { key: "revenue", label: "Revenue", type: "measure", description: "Ad Revenue" },
            { key: "clicks", label: "Clicks", type: "measure", description: "Ad Clicks" },
            { key: "impressions", label: "Impressions", type: "measure", description: "Ad Impressions" },
            { key: "order_id", label: "Order ID", type: "dimension", description: "Unique Order" },
        ],
        initialConfig: {
            rows: ["platform", "campaign"],
            columns: [],
            values: [
                { id: "spend-sum", key: "spend", label: "Spend", agg: "sum", format: "currency" },
                {
                    id: "roas-calc",
                    key: "revenue",
                    denominatorKey: "spend",
                    label: "ROAS",
                    agg: "sum",
                    calc: "ratio",
                },
                { id: "orders-unique", key: "order_id", label: "Distinct Orders", agg: "distinctCount", format: "number" },
            ],
            filters: {},
        },
        data: [
            { platform: "Google", campaign: "Brand Search", spend: 50000, revenue: 260000, clicks: 15000, impressions: 200000, order_id: "ORD-101" },
            { platform: "Google", campaign: "Brand Search", spend: 50000, revenue: 260000, clicks: 15000, impressions: 200000, order_id: "ORD-102" },
            { platform: "Meta", campaign: "Retargeting", spend: 40000, revenue: 192000, clicks: 8000, impressions: 300000, order_id: "ORD-201" },
        ],
    },
};
