// DataRcaKwalityWalls.jsx
// Sample realistic RCA data for Kwality Walls across ecom and quick commerce

export const KPI_HEADERS = [
  "Offtakes",
  "Spend",
  "ROAS",
  "Inorg Sales",
  "A2c",
  "Availability",
  "SOS",
  "Market Share",
  "Promo My Brand",
  "Promo Compete",
  "CPM",
  "CPC",
];

const v = ({
  offtakes,
  spend,
  roas,
  inorgSales,
  a2c,
  availability,
  sos,
  marketShare,
  promoMyBrand,
  promoCompete,
  cpm,
  cpc,
}) => [
  offtakes,
  spend,
  roas,
  inorgSales,
  a2c,
  availability,
  sos,
  marketShare,
  promoMyBrand,
  promoCompete,
  cpm,
  cpc,
];

/* ======================================================================
   TOP 5 GAINERS - KWALITY WALLS
   Each row is a segment of the portfolio
   Brand, city and SKU nested under children
====================================================================== */

const gainersRows = [
  {
    label: "KW - Cornettos and Cones",
    values: v({
      offtakes: 78000,
      spend: 220000,
      roas: 4.8,
      inorgSales: 178000,
      a2c: "4.2%",
      availability: "98%",
      sos: "16%",
      marketShare: "19%",
      promoMyBrand: "68%",
      promoCompete: "32%",
      cpm: 102,
      cpc: 4.6,
    }),
    children: [
      {
        label: "Kwality Walls",
        values: v({
          offtakes: 78000,
          spend: 220000,
          roas: 4.8,
          inorgSales: 178000,
          a2c: "4.2%",
          availability: "98%",
          sos: "16%",
          marketShare: "19%",
          promoMyBrand: "68%",
          promoCompete: "32%",
          cpm: 102,
          cpc: 4.6,
        }),
        children: [
          {
            label: "Delhi NCR",
            values: v({
              offtakes: 42000,
              spend: 115000,
              roas: 5.0,
              inorgSales: 96000,
              a2c: "4.5%",
              availability: "99%",
              sos: "18%",
              marketShare: "21%",
              promoMyBrand: "70%",
              promoCompete: "30%",
              cpm: 100,
              cpc: 4.4,
            }),
            children: [
              {
                label: "Cornetto Double Chocolate 110 ml",
                values: v({
                  offtakes: 23000,
                  spend: 61000,
                  roas: 5.2,
                  inorgSales: 52000,
                  a2c: "4.9%",
                  availability: "99%",
                  sos: "9%",
                  marketShare: "11%",
                  promoMyBrand: "71%",
                  promoCompete: "29%",
                  cpm: 98,
                  cpc: 4.1,
                }),
              },
              {
                label: "Cornetto Oreo 110 ml",
                values: v({
                  offtakes: 19000,
                  spend: 54000,
                  roas: 4.8,
                  inorgSales: 44000,
                  a2c: "4.2%",
                  availability: "99%",
                  sos: "9%",
                  marketShare: "10%",
                  promoMyBrand: "69%",
                  promoCompete: "31%",
                  cpm: 102,
                  cpc: 4.6,
                }),
              },
            ],
          },
          {
            label: "Mumbai",
            values: v({
              offtakes: 36000,
              spend: 105000,
              roas: 4.6,
              inorgSales: 82000,
              a2c: "3.9%",
              availability: "97%",
              sos: "14%",
              marketShare: "17%",
              promoMyBrand: "66%",
              promoCompete: "34%",
              cpm: 104,
              cpc: 4.9,
            }),
            children: [
              {
                label: "Cornetto Double Chocolate 110 ml",
                values: v({
                  offtakes: 19000,
                  spend: 56000,
                  roas: 4.9,
                  inorgSales: 46000,
                  a2c: "4.0%",
                  availability: "98%",
                  sos: "7%",
                  marketShare: "9%",
                  promoMyBrand: "67%",
                  promoCompete: "33%",
                  cpm: 103,
                  cpc: 4.7,
                }),
              },
              {
                label: "Cornetto Strawberry 100 ml",
                values: v({
                  offtakes: 17000,
                  spend: 49000,
                  roas: 4.3,
                  inorgSales: 36000,
                  a2c: "3.8%",
                  availability: "96%",
                  sos: "7%",
                  marketShare: "8%",
                  promoMyBrand: "64%",
                  promoCompete: "36%",
                  cpm: 106,
                  cpc: 5.1,
                }),
              },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "KW - Magnum Range",
    values: v({
      offtakes: 46000,
      spend: 210000,
      roas: 5.5,
      inorgSales: 182000,
      a2c: "3.9%",
      availability: "99%",
      sos: "11%",
      marketShare: "14%",
      promoMyBrand: "72%",
      promoCompete: "28%",
      cpm: 118,
      cpc: 5.4,
    }),
    children: [
      {
        label: "Kwality Walls",
        values: v({
          offtakes: 46000,
          spend: 210000,
          roas: 5.5,
          inorgSales: 182000,
          a2c: "3.9%",
          availability: "99%",
          sos: "11%",
          marketShare: "14%",
          promoMyBrand: "72%",
          promoCompete: "28%",
          cpm: 118,
          cpc: 5.4,
        }),
        children: [
          {
            label: "Delhi NCR",
            values: v({
              offtakes: 25000,
              spend: 110000,
              roas: 5.8,
              inorgSales: 103000,
              a2c: "4.1%",
              availability: "99%",
              sos: "6%",
              marketShare: "8%",
              promoMyBrand: "73%",
              promoCompete: "27%",
              cpm: 120,
              cpc: 5.6,
            }),
            children: [
              {
                label: "Magnum Almond 80 ml",
                values: v({
                  offtakes: 13000,
                  spend: 58000,
                  roas: 6.0,
                  inorgSales: 62000,
                  a2c: "4.3%",
                  availability: "99%",
                  sos: "3%",
                  marketShare: "4%",
                  promoMyBrand: "74%",
                  promoCompete: "26%",
                  cpm: 118,
                  cpc: 5.3,
                }),
              },
              {
                label: "Magnum Classic 80 ml",
                values: v({
                  offtakes: 12000,
                  spend: 52000,
                  roas: 5.6,
                  inorgSales: 41000,
                  a2c: "4.0%",
                  availability: "99%",
                  sos: "3%",
                  marketShare: "4%",
                  promoMyBrand: "72%",
                  promoCompete: "28%",
                  cpm: 122,
                  cpc: 5.8,
                }),
              },
            ],
          },
          {
            label: "Bengaluru",
            values: v({
              offtakes: 21000,
              spend: 100000,
              roas: 5.1,
              inorgSales: 79000,
              a2c: "3.7%",
              availability: "98%",
              sos: "5%",
              marketShare: "6%",
              promoMyBrand: "71%",
              promoCompete: "29%",
              cpm: 116,
              cpc: 5.2,
            }),
            children: [
              {
                label: "Magnum Truffle 80 ml",
                values: v({
                  offtakes: 11000,
                  spend: 52000,
                  roas: 5.2,
                  inorgSales: 45000,
                  a2c: "3.8%",
                  availability: "98%",
                  sos: "3%",
                  marketShare: "3%",
                  promoMyBrand: "71%",
                  promoCompete: "29%",
                  cpm: 115,
                  cpc: 5.1,
                }),
              },
              {
                label: "Magnum Brownie 80 ml",
                values: v({
                  offtakes: 10000,
                  spend: 48000,
                  roas: 5.0,
                  inorgSales: 34000,
                  a2c: "3.6%",
                  availability: "98%",
                  sos: "2%",
                  marketShare: "3%",
                  promoMyBrand: "70%",
                  promoCompete: "30%",
                  cpm: 118,
                  cpc: 5.3,
                }),
              },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "KW - Party Packs and Family Tubs",
    values: v({
      offtakes: 68000,
      spend: 185000,
      roas: 4.2,
      inorgSales: 210000,
      a2c: "3.4%",
      availability: "97%",
      sos: "19%",
      marketShare: "23%",
      promoMyBrand: "62%",
      promoCompete: "38%",
      cpm: 96,
      cpc: 4.3,
    }),
    children: [
      {
        label: "Kwality Walls",
        values: v({
          offtakes: 68000,
          spend: 185000,
          roas: 4.2,
          inorgSales: 210000,
          a2c: "3.4%",
          availability: "97%",
          sos: "19%",
          marketShare: "23%",
          promoMyBrand: "62%",
          promoCompete: "38%",
          cpm: 96,
          cpc: 4.3,
        }),
        children: [
          {
            label: "Delhi NCR",
            values: v({
              offtakes: 35000,
              spend: 98000,
              roas: 4.5,
              inorgSales: 115000,
              a2c: "3.5%",
              availability: "97%",
              sos: "11%",
              marketShare: "13%",
              promoMyBrand: "63%",
              promoCompete: "37%",
              cpm: 94,
              cpc: 4.1,
            }),
            children: [
              {
                label: "Party Pack Butterscotch 700 ml",
                values: v({
                  offtakes: 18000,
                  spend: 50000,
                  roas: 4.6,
                  inorgSales: 62000,
                  a2c: "3.6%",
                  availability: "97%",
                  sos: "5%",
                  marketShare: "7%",
                  promoMyBrand: "64%",
                  promoCompete: "36%",
                  cpm: 92,
                  cpc: 4.0,
                }),
              },
              {
                label: "Family Tub Vanilla 700 ml",
                values: v({
                  offtakes: 17000,
                  spend: 48000,
                  roas: 4.4,
                  inorgSales: 53000,
                  a2c: "3.4%",
                  availability: "97%",
                  sos: "6%",
                  marketShare: "6%",
                  promoMyBrand: "62%",
                  promoCompete: "38%",
                  cpm: 96,
                  cpc: 4.3,
                }),
              },
            ],
          },
          {
            label: "Mumbai",
            values: v({
              offtakes: 33000,
              spend: 87000,
              roas: 3.9,
              inorgSales: 95000,
              a2c: "3.3%",
              availability: "96%",
              sos: "8%",
              marketShare: "10%",
              promoMyBrand: "61%",
              promoCompete: "39%",
              cpm: 99,
              cpc: 4.5,
            }),
            children: [
              {
                label: "Party Pack Choco Brownie 750 ml",
                values: v({
                  offtakes: 17000,
                  spend: 46000,
                  roas: 4.0,
                  inorgSales: 52000,
                  a2c: "3.4%",
                  availability: "96%",
                  sos: "4%",
                  marketShare: "5%",
                  promoMyBrand: "62%",
                  promoCompete: "38%",
                  cpm: 97,
                  cpc: 4.4,
                }),
              },
              {
                label: "Family Tub Strawberry 700 ml",
                values: v({
                  offtakes: 16000,
                  spend: 41000,
                  roas: 3.8,
                  inorgSales: 43000,
                  a2c: "3.1%",
                  availability: "96%",
                  sos: "4%",
                  marketShare: "5%",
                  promoMyBrand: "60%",
                  promoCompete: "40%",
                  cpm: 101,
                  cpc: 4.8,
                }),
              },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "KW - Feast Bars and Sticks",
    values: v({
      offtakes: 52000,
      spend: 145000,
      roas: 4.0,
      inorgSales: 158000,
      a2c: "4.8%",
      availability: "96%",
      sos: "12%",
      marketShare: "14%",
      promoMyBrand: "65%",
      promoCompete: "35%",
      cpm: 90,
      cpc: 4.0,
    }),
    children: [
      {
        label: "Kwality Walls",
        values: v({
          offtakes: 52000,
          spend: 145000,
          roas: 4.0,
          inorgSales: 158000,
          a2c: "4.8%",
          availability: "96%",
          sos: "12%",
          marketShare: "14%",
          promoMyBrand: "65%",
          promoCompete: "35%",
          cpm: 90,
          cpc: 4.0,
        }),
        children: [
          {
            label: "Delhi NCR",
            values: v({
              offtakes: 28000,
              spend: 78000,
              roas: 4.1,
              inorgSales: 84000,
              a2c: "4.9%",
              availability: "97%",
              sos: "7%",
              marketShare: "8%",
              promoMyBrand: "66%",
              promoCompete: "34%",
              cpm: 88,
              cpc: 3.9,
            }),
            children: [
              {
                label: "Feast Chocolate Stick 90 ml",
                values: v({
                  offtakes: 15000,
                  spend: 41000,
                  roas: 4.2,
                  inorgSales: 46000,
                  a2c: "5.1%",
                  availability: "97%",
                  sos: "4%",
                  marketShare: "5%",
                  promoMyBrand: "67%",
                  promoCompete: "33%",
                  cpm: 86,
                  cpc: 3.8,
                }),
              },
              {
                label: "Chocobar Stick 60 ml",
                values: v({
                  offtakes: 13000,
                  spend: 37000,
                  roas: 4.0,
                  inorgSales: 38000,
                  a2c: "4.8%",
                  availability: "97%",
                  sos: "3%",
                  marketShare: "3%",
                  promoMyBrand: "65%",
                  promoCompete: "35%",
                  cpm: 90,
                  cpc: 4.0,
                }),
              },
            ],
          },
          {
            label: "Bengaluru",
            values: v({
              offtakes: 24000,
              spend: 67000,
              roas: 3.8,
              inorgSales: 74000,
              a2c: "4.6%",
              availability: "95%",
              sos: "5%",
              marketShare: "6%",
              promoMyBrand: "64%",
              promoCompete: "36%",
              cpm: 93,
              cpc: 4.2,
            }),
            children: [
              {
                label: "Feast Chocolate Stick 90 ml",
                values: v({
                  offtakes: 13000,
                  spend: 36000,
                  roas: 3.9,
                  inorgSales: 40000,
                  a2c: "4.7%",
                  availability: "95%",
                  sos: "3%",
                  marketShare: "3%",
                  promoMyBrand: "64%",
                  promoCompete: "36%",
                  cpm: 92,
                  cpc: 4.1,
                }),
              },
              {
                label: "Butterscotch Crunch Stick 90 ml",
                values: v({
                  offtakes: 11000,
                  spend: 31000,
                  roas: 3.7,
                  inorgSales: 34000,
                  a2c: "4.5%",
                  availability: "95%",
                  sos: "2%",
                  marketShare: "3%",
                  promoMyBrand: "63%",
                  promoCompete: "37%",
                  cpm: 95,
                  cpc: 4.3,
                }),
              },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "KW - Sandwich and Innovative SKUs",
    values: v({
      offtakes: 31000,
      spend: 98000,
      roas: 3.9,
      inorgSales: 112000,
      a2c: "3.8%",
      availability: "97%",
      sos: "8%",
      marketShare: "9%",
      promoMyBrand: "60%",
      promoCompete: "40%",
      cpm: 101,
      cpc: 4.7,
    }),
    children: [
      {
        label: "Kwality Walls",
        values: v({
          offtakes: 31000,
          spend: 98000,
          roas: 3.9,
          inorgSales: 112000,
          a2c: "3.8%",
          availability: "97%",
          sos: "8%",
          marketShare: "9%",
          promoMyBrand: "60%",
          promoCompete: "40%",
          cpm: 101,
          cpc: 4.7,
        }),
        children: [
          {
            label: "Mumbai",
            values: v({
              offtakes: 17000,
              spend: 52000,
              roas: 4.0,
              inorgSales: 61000,
              a2c: "3.9%",
              availability: "97%",
              sos: "4%",
              marketShare: "5%",
              promoMyBrand: "61%",
              promoCompete: "39%",
              cpm: 99,
              cpc: 4.6,
            }),
            children: [
              {
                label: "Sandwich Vanilla 60 ml",
                values: v({
                  offtakes: 9000,
                  spend: 28000,
                  roas: 4.1,
                  inorgSales: 32000,
                  a2c: "4.0%",
                  availability: "97%",
                  sos: "2%",
                  marketShare: "3%",
                  promoMyBrand: "61%",
                  promoCompete: "39%",
                  cpm: 97,
                  cpc: 4.4,
                }),
              },
              {
                label: "Sandwich Choco 60 ml",
                values: v({
                  offtakes: 8000,
                  spend: 24000,
                  roas: 3.9,
                  inorgSales: 29000,
                  a2c: "3.8%",
                  availability: "97%",
                  sos: "2%",
                  marketShare: "2%",
                  promoMyBrand: "60%",
                  promoCompete: "40%",
                  cpm: 101,
                  cpc: 4.8,
                }),
              },
            ],
          },
          {
            label: "Delhi NCR",
            values: v({
              offtakes: 14000,
              spend: 46000,
              roas: 3.7,
              inorgSales: 51000,
              a2c: "3.7%",
              availability: "96%",
              sos: "4%",
              marketShare: "4%",
              promoMyBrand: "59%",
              promoCompete: "41%",
              cpm: 103,
              cpc: 4.9,
            }),
            children: [
              {
                label: "Sandwich Butterscotch 60 ml",
                values: v({
                  offtakes: 7000,
                  spend: 24000,
                  roas: 3.8,
                  inorgSales: 26000,
                  a2c: "3.8%",
                  availability: "96%",
                  sos: "2%",
                  marketShare: "2%",
                  promoMyBrand: "59%",
                  promoCompete: "41%",
                  cpm: 104,
                  cpc: 5.1,
                }),
              },
              {
                label: "Sandwich Red Velvet 60 ml",
                values: v({
                  offtakes: 7000,
                  spend: 22000,
                  roas: 3.6,
                  inorgSales: 25000,
                  a2c: "3.6%",
                  availability: "96%",
                  sos: "2%",
                  marketShare: "2%",
                  promoMyBrand: "58%",
                  promoCompete: "42%",
                  cpm: 102,
                  cpc: 4.8,
                }),
              },
            ],
          },
        ],
      },
    ],
  },
];

/* ======================================================================
   TOP 5 DRAINERS - KWALITY WALLS
   Segments with weak growth or efficiency
====================================================================== */

const drainersRows = [
  {
    label: "KW - High Discount Family Tubs",
    values: v({
      offtakes: 41000,
      spend: 175000,
      roas: 2.4,
      inorgSales: 132000,
      a2c: "2.6%",
      availability: "93%",
      sos: "17%",
      marketShare: "15%",
      promoMyBrand: "82%",
      promoCompete: "18%",
      cpm: 138,
      cpc: 7.2,
    }),
    children: [
      {
        label: "Kwality Walls",
        values: v({
          offtakes: 41000,
          spend: 175000,
          roas: 2.4,
          inorgSales: 132000,
          a2c: "2.6%",
          availability: "93%",
          sos: "17%",
          marketShare: "15%",
          promoMyBrand: "82%",
          promoCompete: "18%",
          cpm: 138,
          cpc: 7.2,
        }),
        children: [
          {
            label: "Delhi NCR",
            values: v({
              offtakes: 22000,
              spend: 98000,
              roas: 2.3,
              inorgSales: 72000,
              a2c: "2.7%",
              availability: "92%",
              sos: "9%",
              marketShare: "8%",
              promoMyBrand: "84%",
              promoCompete: "16%",
              cpm: 141,
              cpc: 7.5,
            }),
            children: [
              {
                label: "Family Tub Choco Fudge 1 L",
                values: v({
                  offtakes: 11000,
                  spend: 52000,
                  roas: 2.2,
                  inorgSales: 39000,
                  a2c: "2.8%",
                  availability: "92%",
                  sos: "5%",
                  marketShare: "4%",
                  promoMyBrand: "85%",
                  promoCompete: "15%",
                  cpm: 143,
                  cpc: 7.8,
                }),
              },
              {
                label: "Family Tub Butterscotch 1 L",
                values: v({
                  offtakes: 11000,
                  spend: 46000,
                  roas: 2.4,
                  inorgSales: 33000,
                  a2c: "2.6%",
                  availability: "92%",
                  sos: "4%",
                  marketShare: "4%",
                  promoMyBrand: "83%",
                  promoCompete: "17%",
                  cpm: 139,
                  cpc: 7.3,
                }),
              },
            ],
          },
          {
            label: "Lucknow",
            values: v({
              offtakes: 19000,
              spend: 77000,
              roas: 2.5,
              inorgSales: 60000,
              a2c: "2.4%",
              availability: "94%",
              sos: "8%",
              marketShare: "7%",
              promoMyBrand: "80%",
              promoCompete: "20%",
              cpm: 135,
              cpc: 7.0,
            }),
            children: [
              {
                label: "Family Tub Strawberry 1 L",
                values: v({
                  offtakes: 9000,
                  spend: 39000,
                  roas: 2.4,
                  inorgSales: 31000,
                  a2c: "2.5%",
                  availability: "94%",
                  sos: "4%",
                  marketShare: "3%",
                  promoMyBrand: "81%",
                  promoCompete: "19%",
                  cpm: 136,
                  cpc: 7.1,
                }),
              },
              {
                label: "Family Tub Vanilla 1 L",
                values: v({
                  offtakes: 10000,
                  spend: 38000,
                  roas: 2.6,
                  inorgSales: 29000,
                  a2c: "2.3%",
                  availability: "94%",
                  sos: "4%",
                  marketShare: "3%",
                  promoMyBrand: "79%",
                  promoCompete: "21%",
                  cpm: 134,
                  cpc: 6.9,
                }),
              },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "KW - Overbid Magnum Experiments",
    values: v({
      offtakes: 21000,
      spend: 145000,
      roas: 1.9,
      inorgSales: 92000,
      a2c: "2.1%",
      availability: "96%",
      sos: "7%",
      marketShare: "6%",
      promoMyBrand: "76%",
      promoCompete: "24%",
      cpm: 182,
      cpc: 8.9,
    }),
    children: [
      {
        label: "Kwality Walls",
        values: v({
          offtakes: 21000,
          spend: 145000,
          roas: 1.9,
          inorgSales: 92000,
          a2c: "2.1%",
          availability: "96%",
          sos: "7%",
          marketShare: "6%",
          promoMyBrand: "76%",
          promoCompete: "24%",
          cpm: 182,
          cpc: 8.9,
        }),
        children: [
          {
            label: "Mumbai",
            values: v({
              offtakes: 12000,
              spend: 82000,
              roas: 1.8,
              inorgSales: 52000,
              a2c: "2.2%",
              availability: "96%",
              sos: "4%",
              marketShare: "3%",
              promoMyBrand: "77%",
              promoCompete: "23%",
              cpm: 188,
              cpc: 9.1,
            }),
            children: [
              {
                label: "Magnum Ruby 80 ml",
                values: v({
                  offtakes: 6000,
                  spend: 43000,
                  roas: 1.7,
                  inorgSales: 26000,
                  a2c: "2.3%",
                  availability: "96%",
                  sos: "2%",
                  marketShare: "2%",
                  promoMyBrand: "78%",
                  promoCompete: "22%",
                  cpm: 190,
                  cpc: 9.4,
                }),
              },
              {
                label: "Magnum Mint 80 ml",
                values: v({
                  offtakes: 6000,
                  spend: 39000,
                  roas: 1.9,
                  inorgSales: 26000,
                  a2c: "2.1%",
                  availability: "96%",
                  sos: "2%",
                  marketShare: "2%",
                  promoMyBrand: "76%",
                  promoCompete: "24%",
                  cpm: 186,
                  cpc: 8.8,
                }),
              },
            ],
          },
          {
            label: "Bengaluru",
            values: v({
              offtakes: 9000,
              spend: 63000,
              roas: 2.0,
              inorgSales: 40000,
              a2c: "2.0%",
              availability: "95%",
              sos: "3%",
              marketShare: "3%",
              promoMyBrand: "75%",
              promoCompete: "25%",
              cpm: 176,
              cpc: 8.6,
            }),
            children: [
              {
                label: "Magnum Coffee 80 ml",
                values: v({
                  offtakes: 4500,
                  spend: 34000,
                  roas: 2.0,
                  inorgSales: 23000,
                  a2c: "2.1%",
                  availability: "95%",
                  sos: "2%",
                  marketShare: "2%",
                  promoMyBrand: "75%",
                  promoCompete: "25%",
                  cpm: 178,
                  cpc: 8.9,
                }),
              },
              {
                label: "Magnum Hazelnut 80 ml",
                values: v({
                  offtakes: 4500,
                  spend: 29000,
                  roas: 2.0,
                  inorgSales: 17000,
                  a2c: "1.9%",
                  availability: "95%",
                  sos: "1%",
                  marketShare: "1%",
                  promoMyBrand: "74%",
                  promoCompete: "26%",
                  cpm: 173,
                  cpc: 8.3,
                }),
              },
            ],
          },
        ],
      },
    ],
  },
  {
    label: "KW - Low Reach Cornetto On Flipkart",
    values: v({
      offtakes: 16000,
      spend: 72000,
      roas: 2.1,
      inorgSales: 52000,
      a2c: "2.4%",
      availability: "89%",
      sos: "3%",
      marketShare: "3%",
      promoMyBrand: "63%",
      promoCompete: "37%",
      cpm: 154,
      cpc: 7.8,
    }),
    children: [
      {
        label: "Flipkart Grocery",
        values: v({
          offtakes: 16000,
          spend: 72000,
          roas: 2.1,
          inorgSales: 52000,
          a2c: "2.4%",
          availability: "89%",
          sos: "3%",
          marketShare: "3%",
          promoMyBrand: "63%",
          promoCompete: "37%",
          cpm: 154,
          cpc: 7.8,
        }),
        children: [
          {
            label: "Ahmedabad",
            values: v({
              offtakes: 8000,
              spend: 38000,
              roas: 2.0,
              inorgSales: 26000,
              a2c: "2.6%",
              availability: "88%",
              sos: "2%",
              marketShare: "2%",
              promoMyBrand: "64%",
              promoCompete: "36%",
              cpm: 158,
              cpc: 8.0,
            }),
            children: [
              {
                label: "Cornetto Double Chocolate 110 ml",
                values: v({
                  offtakes: 4000,
                  spend: 20000,
                  roas: 2.0,
                  inorgSales: 14000,
                  a2c: "2.7%",
                  availability: "88%",
                  sos: "1%",
                  marketShare: "1%",
                  promoMyBrand: "65%",
                  promoCompete: "35%",
                  cpm: 160,
                  cpc: 8.1,
                }),
              },
              {
                label: "Cornetto Strawberry 100 ml",
                values: v({
                  offtakes: 4000,
                  spend: 18000,
                  roas: 2.0,
                  inorgSales: 12000,
                  a2c: "2.5%",
                  availability: "88%",
                  sos: "1%",
                  marketShare: "1%",
                  promoMyBrand: "63%",
                  promoCompete: "37%",
                  cpm: 156,
                  cpc: 7.8,
                }),
              },
            ],
          },
          {
            label: "Vadodara",
            values: v({
              offtakes: 8000,
              spend: 34000,
              roas: 2.2,
              inorgSales: 26000,
              a2c: "2.3%",
              availability: "90%",
              sos: "1%",
              marketShare: "1%",
              promoMyBrand: "62%",
              promoCompete: "38%",
              cpm: 150,
              cpc: 7.5,
            }),
          },
        ],
      },
    ],
  },
  {
    label: "KW - Underperforming Sandwich SKUs",
    values: v({
      offtakes: 19000,
      spend: 69000,
      roas: 2.3,
      inorgSales: 52000,
      a2c: "2.9%",
      availability: "91%",
      sos: "4%",
      marketShare: "3%",
      promoMyBrand: "66%",
      promoCompete: "34%",
      cpm: 132,
      cpc: 6.9,
    }),
    children: [
      {
        label: "Kwality Walls",
        values: v({
          offtakes: 19000,
          spend: 69000,
          roas: 2.3,
          inorgSales: 52000,
          a2c: "2.9%",
          availability: "91%",
          sos: "4%",
          marketShare: "3%",
          promoMyBrand: "66%",
          promoCompete: "34%",
          cpm: 132,
          cpc: 6.9,
        }),
        children: [
          {
            label: "Blinkit North",
            values: v({
              offtakes: 9000,
              spend: 36000,
              roas: 2.1,
              inorgSales: 25000,
              a2c: "3.1%",
              availability: "90%",
              sos: "2%",
              marketShare: "1%",
              promoMyBrand: "67%",
              promoCompete: "33%",
              cpm: 134,
              cpc: 7.0,
            }),
          },
          {
            label: "Zepto West",
            values: v({
              offtakes: 10000,
              spend: 33000,
              roas: 2.4,
              inorgSales: 27000,
              a2c: "2.7%",
              availability: "92%",
              sos: "2%",
              marketShare: "2%",
              promoMyBrand: "65%",
              promoCompete: "35%",
              cpm: 129,
              cpc: 6.8,
            }),
          },
        ],
      },
    ],
  },
  {
    label: "KW - Low ROAS Seasonal Packs",
    values: v({
      offtakes: 14000,
      spend: 62000,
      roas: 2.0,
      inorgSales: 41000,
      a2c: "2.2%",
      availability: "92%",
      sos: "3%",
      marketShare: "2%",
      promoMyBrand: "70%",
      promoCompete: "30%",
      cpm: 146,
      cpc: 8.0,
    }),
    children: [
      {
        label: "Instamart All India",
        values: v({
          offtakes: 14000,
          spend: 62000,
          roas: 2.0,
          inorgSales: 41000,
          a2c: "2.2%",
          availability: "92%",
          sos: "3%",
          marketShare: "2%",
          promoMyBrand: "70%",
          promoCompete: "30%",
          cpm: 146,
          cpc: 8.0,
        }),
      },
    ],
  },
];

/* ======================================================================
   LOW PERFORMING KEYWORDS - KWALITY WALLS
   Simple flat list, 5 rows
====================================================================== */

const lowKeywordsRows = [
  {
    label: "Blinkit | Delhi NCR | kwality walls party pack",
    values: v({
      offtakes: 1800,
      spend: 26000,
      roas: 1.7,
      inorgSales: 18000,
      a2c: "2.0%",
      availability: "94%",
      sos: "2%",
      marketShare: "1%",
      promoMyBrand: "55%",
      promoCompete: "45%",
      cpm: 152,
      cpc: 8.4,
    }),
  },
  {
    label: "Zepto | Mumbai | magnum ice cream price",
    values: v({
      offtakes: 1300,
      spend: 24000,
      roas: 1.8,
      inorgSales: 17000,
      a2c: "1.9%",
      availability: "95%",
      sos: "1%",
      marketShare: "1%",
      promoMyBrand: "58%",
      promoCompete: "42%",
      cpm: 148,
      cpc: 8.0,
    }),
  },
  {
    label: "Instamart | Bengaluru | choco bar ice cream",
    values: v({
      offtakes: 900,
      spend: 18500,
      roas: 1.6,
      inorgSales: 12500,
      a2c: "1.8%",
      availability: "93%",
      sos: "1%",
      marketShare: "1%",
      promoMyBrand: "52%",
      promoCompete: "48%",
      cpm: 140,
      cpc: 7.5,
    }),
  },
  {
    label: "Flipkart | Ahmedabad | cone ice cream",
    values: v({
      offtakes: 750,
      spend: 17000,
      roas: 1.5,
      inorgSales: 11200,
      a2c: "1.7%",
      availability: "90%",
      sos: "1%",
      marketShare: "1%",
      promoMyBrand: "50%",
      promoCompete: "50%",
      cpm: 144,
      cpc: 7.9,
    }),
  },
  {
    label: "Blinkit | Pune | vanilla family tub",
    values: v({
      offtakes: 600,
      spend: 15000,
      roas: 1.4,
      inorgSales: 9800,
      a2c: "1.6%",
      availability: "91%",
      sos: "1%",
      marketShare: "1%",
      promoMyBrand: "53%",
      promoCompete: "47%",
      cpm: 138,
      cpc: 7.3,
    }),
  },
];

/* ======================================================================
   LOW PERFORMING CAMPAIGNS - KWALITY WALLS
   Simple flat list, 5 rows
====================================================================== */

const lowCampaignsRows = [
  {
    label: "Blinkit | KW Magnum Awareness Burst",
    values: v({
      offtakes: 5200,
      spend: 98000,
      roas: 1.9,
      inorgSales: 72000,
      a2c: "2.3%",
      availability: "96%",
      sos: "4%",
      marketShare: "3%",
      promoMyBrand: "78%",
      promoCompete: "22%",
      cpm: 164,
      cpc: 8.2,
    }),
  },
  {
    label: "Zepto | KW Family Tub Combo Sale",
    values: v({
      offtakes: 6100,
      spend: 112000,
      roas: 1.8,
      inorgSales: 81000,
      a2c: "2.4%",
      availability: "93%",
      sos: "5%",
      marketShare: "4%",
      promoMyBrand: "80%",
      promoCompete: "20%",
      cpm: 170,
      cpc: 8.9,
    }),
  },
  {
    label: "Instamart | KW Party Pack Weekend Blast",
    values: v({
      offtakes: 4500,
      spend: 89000,
      roas: 1.7,
      inorgSales: 64000,
      a2c: "2.1%",
      availability: "92%",
      sos: "3%",
      marketShare: "3%",
      promoMyBrand: "77%",
      promoCompete: "23%",
      cpm: 160,
      cpc: 8.1,
    }),
  },
  {
    label: "Flipkart | KW Cornetto Combo Ads",
    values: v({
      offtakes: 3800,
      spend: 76000,
      roas: 1.8,
      inorgSales: 55000,
      a2c: "2.0%",
      availability: "90%",
      sos: "2%",
      marketShare: "2%",
      promoMyBrand: "74%",
      promoCompete: "26%",
      cpm: 158,
      cpc: 7.9,
    }),
  },
  {
    label: "Blinkit | KW Sandwich and Stick Push",
    values: v({
      offtakes: 4100,
      spend: 82000,
      roas: 1.7,
      inorgSales: 59000,
      a2c: "2.2%",
      availability: "91%",
      sos: "3%",
      marketShare: "3%",
      promoMyBrand: "72%",
      promoCompete: "28%",
      cpm: 162,
      cpc: 8.3,
    }),
  },
];

/* For now reuse gainers and drainers for availability views,
   you can replace with separate arrays if needed later
*/

const availabilityDropRows = drainersRows;
const availabilityGainRows = gainersRows;

export const kpiDrillDataByTab = {
  gainers: {
    key: "gainers",
    title: "Top 5 Gainers - Kwality Walls",
    subtitle: "Kwality Walls segments with strongest growth vs previous period",
    rows: gainersRows,
  },
  drainers: {
    key: "drainers",
    title: "Top 5 Drainers - Kwality Walls",
    subtitle: "Kwality Walls segments dragging performance",
    rows: drainersRows,
  },
  availabilityDrop: {
    key: "availabilityDrop",
    title: "Availability Drops - Kwality Walls",
    subtitle: "Segments where availability declined for Kwality Walls",
    rows: availabilityDropRows,
  },
  availabilityGain: {
    key: "availabilityGain",
    title: "Availability Gains - Kwality Walls",
    subtitle: "Segments where availability improved for Kwality Walls",
    rows: availabilityGainRows,
  },
  lowKeywords: {
    key: "lowKeywords",
    title: "Low Performing Keywords - Kwality Walls",
    subtitle: "Keyword clusters with weak performance for Kwality Walls",
    rows: availabilityDropRows,
  },
  lowCampaigns: {
    key: "lowCampaigns",
    title: "Low Performing Campaigns - Kwality Walls",
    subtitle: "Campaigns with low ROAS or high CPC for Kwality Walls",
    rows: gainersRows,
  },
};

export const TABS_META = [
  { key: "gainers", label: "Top 5 Gainers" },
  { key: "drainers", label: "Top 5 Drainers" },
  { key: "availabilityDrop", label: "Avail. Drops" },
  { key: "availabilityGain", label: "Avail. Gains" },
  { key: "lowKeywords", label: "Low Perf. Keywords" },
  { key: "lowCampaigns", label: "Low Perf. Campaigns" },
];
