const monthLogos = {
  jan: "https://img.icons8.com/fluency/96/january.png",
  feb: "https://img.icons8.com/fluency/96/february.png",
  mar: "https://img.icons8.com/fluency/96/march.png",
  apr: "https://img.icons8.com/fluency/96/april.png",
  may: "https://img.icons8.com/fluency/96/may.png",
  jun: "https://img.icons8.com/fluency/96/june.png",
  jul: "https://img.icons8.com/fluency/96/july.png",
  aug: "https://img.icons8.com/fluency/96/august.png",
  sep: "https://img.icons8.com/fluency/96/september.png",
  oct: "https://img.icons8.com/fluency/96/october.png",
  nov: "https://img.icons8.com/fluency/96/november.png",
  dec: "https://img.icons8.com/fluency/96/december.png",
};
const categoryLogo = "https://cdn-icons-png.flaticon.com/512/711/711284.png";

export const defaultPlatforms = [
  {
    key: "all",
    label: "All",
    type: "Overall",
    logo: "https://cdn-icons-png.flaticon.com/512/711/711284.png",
    columns: [
      {
        title: "Offtake",
        value: "₹9.0 Cr",
        change: { text: "▲3.2% (₹28.8 lac)", positive: true },
        meta: { units: "4.9 lac", change: "▲2.4%" },
      },
      {
        title: "Est. Category Share",
        value: "35.0%",
        change: { text: "▲0.4% (+0.1 pp)", positive: true },
        meta: { units: "4.9 lac", change: "▲2.4%" },
      },
      {
        title: "Category Size",
        value: "₹25.7 Cr",
        change: { text: "▲2.9% (₹72.5 lac)", positive: true },
        meta: { units: "4.9 lac", change: "▲2.4%" },
      },
      {
        title: "Wt. OSA%",
        value: "78.6%",
        change: { text: "▼9.4% (-8.2 pp)", positive: false },
        meta: { units: "4.9 lac", change: "▲2.4%" },
      },
      {
        title: "Wt. Disc %",
        value: "26.5%",
        change: { text: "▲6.2% (+1.6 pp)", positive: true },
        meta: { units: "4.9 lac", change: "▲2.4%" },
      },
    ],
  },

  // BLINKIT
  {
    key: "blinkit",
    label: "Blinkit",
    type: "Q-commerce",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Blinkit-yellow-rounded.svg",
    columns: [
      {
        title: "Offtake",
        value: "₹2.1 Cr",
        change: { text: "▲3.0% (₹6.1 lac)", positive: true },
        meta: { units: "1.1 lac", change: "▲1.8%" },
      },
      {
        title: "Est. Category Share",
        value: "38.3%",
        change: { text: "▲0.6% (+0.2 pp)", positive: true },
        meta: { units: "1.1 lac", change: "▲1.8%" },
      },
      {
        title: "Category Size",
        value: "₹5.48 Cr",
        change: { text: "▲2.2% (₹11.9 lac)", positive: true },
        meta: { units: "1.1 lac", change: "▲1.8%" },
      },
      {
        title: "Wt. OSA%",
        value: "75.4%",
        change: { text: "▼15.5% (-13.9 pp)", positive: false },
        meta: { units: "1.1 lac", change: "▲1.8%" },
      },
      {
        title: "Wt. Disc %",
        value: "24.0%",
        change: { text: "▲7.4% (+1.7 pp)", positive: true },
        meta: { units: "1.1 lac", change: "▲1.8%" },
      },
    ],
  },

  // ZEPTO
  {
    key: "zepto",
    label: "Zepto",
    type: "Q-commerce",
    logo: "https://upload.wikimedia.org/wikipedia/en/7/7d/Logo_of_Zepto.png",
    columns: [
      {
        title: "Offtake",
        value: "₹1.6 Cr",
        change: { text: "▲3.6% (₹5.6 lac)", positive: true },
        meta: { units: "0.9 lac", change: "▲1.2%" },
      },
      {
        title: "Est. Category Share",
        value: "36.4%",
        change: { text: "▲0.4% (+0.1 pp)", positive: true },
        meta: { units: "0.9 lac", change: "▲1.2%" },
      },
      {
        title: "Category Size",
        value: "₹4.40 Cr",
        change: { text: "▲1.9% (₹8.3 lac)", positive: true },
        meta: { units: "0.9 lac", change: "▲1.2%" },
      },
      {
        title: "Wt. OSA%",
        value: "79.7%",
        change: { text: "▼4.7% (-3.9 pp)", positive: false },
        meta: { units: "0.9 lac", change: "▲1.2%" },
      },
      {
        title: "Wt. Disc %",
        value: "29.9%",
        change: { text: "▲6.3% (+1.8 pp)", positive: true },
        meta: { units: "0.9 lac", change: "▲1.2%" },
      },
    ],
  },

  // SWIGGY
  {
    key: "swiggy",
    label: "Swiggy",
    type: "Marketplace",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Swiggy_Logo_2024.webp",
    columns: [
      {
        title: "Offtake",
        value: "₹1.1 Cr",
        change: { text: "▲2.5% (₹2.8 lac)", positive: true },
        meta: { units: "0.7 lac", change: "▲0.8%" },
      },
      {
        title: "Est. Category Share",
        value: "30.5%",
        change: { text: "▲0.2% (+0.1 pp)", positive: true },
        meta: { units: "0.7 lac", change: "▲0.8%" },
      },
      {
        title: "Category Size",
        value: "₹3.61 Cr",
        change: { text: "▲1.7% (₹6.1 lac)", positive: true },
        meta: { units: "0.7 lac", change: "▲0.8%" },
      },
      {
        title: "Wt. OSA%",
        value: "83.3%",
        change: { text: "▼2.8% (-2.4 pp)", positive: false },
        meta: { units: "0.7 lac", change: "▲0.8%" },
      },
      {
        title: "Wt. Disc %",
        value: "27.3%",
        change: { text: "▲4.4% (+1.1 pp)", positive: true },
        meta: { units: "0.7 lac", change: "▲0.8%" },
      },
    ],
  },

  // AMAZON
  {
    key: "amazon",
    label: "Amazon",
    type: "Marketplace",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
    columns: [
      {
        title: "Offtake",
        value: "₹2.2 Cr",
        change: { text: "▲3.1% (₹6.6 lac)", positive: true },
        meta: { units: "1.1 lac", change: "▲2.0%" },
      },
      {
        title: "Est. Category Share",
        value: "33.5%",
        change: { text: "▲0.3% (+0.1 pp)", positive: true },
        meta: { units: "1.1 lac", change: "▲2.0%" },
      },
      {
        title: "Category Size",
        value: "₹6.57 Cr",
        change: { text: "▲2.5% (₹16.0 lac)", positive: true },
        meta: { units: "1.1 lac", change: "▲2.0%" },
      },
      {
        title: "Wt. OSA%",
        value: "81.2%",
        change: { text: "▼3.1% (-2.6 pp)", positive: false },
        meta: { units: "1.1 lac", change: "▲2.0%" },
      },
      {
        title: "Wt. Disc %",
        value: "25.5%",
        change: { text: "▲3.6% (+0.9 pp)", positive: true },
        meta: { units: "1.1 lac", change: "▲2.0%" },
      },
    ],
  },
];

export const defaultMonths = [
  // ---------- JAN ----------
  {
    key: "jan",
    label: "Jan",
    logo: monthLogos["jan"],
    columns: [
      {
        title: "Offtake",
        value: "₹7.8 Cr",
        change: { text: "▲1.2% (+₹9.3 lac)", positive: true },
        meta: { units: "4.0 lac", change: "▲0.8%" },
      },
      {
        title: "Est. Category Share",
        value: "33.2%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "33.2%", change: "▲0.2 pp" },
      },
      {
        title: "Category Size",
        value: "₹23.5 Cr",
        change: { text: "▲1.9% (+₹43.7 lac)", positive: true },
        meta: { units: "2350 lac", change: "▲1.9%" },
      },
      {
        title: "Wt. OSA%",
        value: "80.5%",
        change: { text: "▼1.5 pp", positive: false },
        meta: { units: "80.5%", change: "▼1.5 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "24.7%",
        change: { text: "▲0.9 pp", positive: true },
        meta: { units: "24.7%", change: "▲0.9 pp" },
      },
    ],
  },

  // ---------- FEB ----------
  {
    key: "feb",
    label: "Feb",
    logo: monthLogos["feb"],
    columns: [
      {
        title: "Offtake",
        value: "₹8.4 Cr",
        change: { text: "▲1.8% (+₹15.1 lac)", positive: true },
        meta: { units: "4.3 lac", change: "▲1.0%" },
      },
      {
        title: "Est. Category Share",
        value: "34.1%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "34.1%", change: "▲0.3 pp" },
      },
      {
        title: "Category Size",
        value: "₹24.6 Cr",
        change: { text: "▲2.2% (+₹53.3 lac)", positive: true },
        meta: { units: "2460 lac", change: "▲2.2%" },
      },
      {
        title: "Wt. OSA%",
        value: "81.0%",
        change: { text: "▼1.1 pp", positive: false },
        meta: { units: "81.0%", change: "▼1.1 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "25.3%",
        change: { text: "▲1.1 pp", positive: true },
        meta: { units: "25.3%", change: "▲1.1 pp" },
      },
    ],
  },

  // ---------- MAR ----------
  {
    key: "mar",
    label: "Mar",
    logo: monthLogos["mar"],
    columns: [
      {
        title: "Offtake",
        value: "₹8.9 Cr",
        change: { text: "▲2.5% (+₹22.3 lac)", positive: true },
        meta: { units: "4.6 lac", change: "▲1.4%" },
      },
      {
        title: "Est. Category Share",
        value: "35.0%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "35.0%", change: "▲0.4 pp" },
      },
      {
        title: "Category Size",
        value: "₹25.0 Cr",
        change: { text: "▲2.1% (+₹51.2 lac)", positive: true },
        meta: { units: "2500 lac", change: "▲2.1%" },
      },
      {
        title: "Wt. OSA%",
        value: "79.8%",
        change: { text: "▼1.6 pp", positive: false },
        meta: { units: "79.8%", change: "▼1.6 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "26.0%",
        change: { text: "▲1.2 pp", positive: true },
        meta: { units: "26.0%", change: "▲1.2 pp" },
      },
    ],
  },

  // ---------- APR ----------
  {
    key: "apr",
    label: "Apr",
    logo: monthLogos["apr"],
    columns: [
      {
        title: "Offtake",
        value: "₹9.4 Cr",
        change: { text: "▲3.1% (+₹28.9 lac)", positive: true },
        meta: { units: "4.8 lac", change: "▲1.7%" },
      },
      {
        title: "Est. Category Share",
        value: "35.4%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "35.4%", change: "▲0.2 pp" },
      },
      {
        title: "Category Size",
        value: "₹25.6 Cr",
        change: { text: "▲2.4% (+₹59.9 lac)", positive: true },
        meta: { units: "2560 lac", change: "▲2.4%" },
      },
      {
        title: "Wt. OSA%",
        value: "78.6%",
        change: { text: "▼2.3 pp", positive: false },
        meta: { units: "78.6%", change: "▼2.3 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "26.4%",
        change: { text: "▲1.3 pp", positive: true },
        meta: { units: "26.4%", change: "▲1.3 pp" },
      },
    ],
  },

  // ---------- MAY ----------
  {
    key: "may",
    label: "May",
    logo: monthLogos["may"],
    columns: [
      {
        title: "Offtake",
        value: "₹10.1 Cr",
        change: { text: "▲3.5% (+₹34.8 lac)", positive: true },
        meta: { units: "5.2 lac", change: "▲2.0%" },
      },
      {
        title: "Est. Category Share",
        value: "36.1%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "36.1%", change: "▲0.3 pp" },
      },
      {
        title: "Category Size",
        value: "₹26.3 Cr",
        change: { text: "▲2.8% (+₹71.4 lac)", positive: true },
        meta: { units: "2630 lac", change: "▲2.8%" },
      },
      {
        title: "Wt. OSA%",
        value: "77.4%",
        change: { text: "▼1.8 pp", positive: false },
        meta: { units: "77.4%", change: "▼1.8 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "27.0%",
        change: { text: "▲0.9 pp", positive: true },
        meta: { units: "27.0%", change: "▲0.9 pp" },
      },
    ],
  },

  // ---------- JUN ----------
  {
    key: "jun",
    label: "Jun",
    logo: monthLogos["jun"],
    columns: [
      {
        title: "Offtake",
        value: "₹10.6 Cr",
        change: { text: "▲2.9% (+₹29.3 lac)", positive: true },
        meta: { units: "5.5 lac", change: "▲1.3%" },
      },
      {
        title: "Est. Category Share",
        value: "36.6%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "36.6%", change: "▲0.3 pp" },
      },
      {
        title: "Category Size",
        value: "₹26.9 Cr",
        change: { text: "▲2.1% (+₹55.9 lac)", positive: true },
        meta: { units: "2690 lac", change: "▲2.1%" },
      },
      {
        title: "Wt. OSA%",
        value: "76.2%",
        change: { text: "▼2.1 pp", positive: false },
        meta: { units: "76.2%", change: "▼2.1 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "27.4%",
        change: { text: "▲0.6 pp", positive: true },
        meta: { units: "27.4%", change: "▲0.6 pp" },
      },
    ],
  },

  // ---------- JUL ----------
  {
    key: "jul",
    label: "Jul",
    logo: monthLogos["jul"],
    columns: [
      {
        title: "Offtake",
        value: "₹11.0 Cr",
        change: { text: "▲2.4% (+₹26.4 lac)", positive: true },
        meta: { units: "5.7 lac", change: "▲1.1%" },
      },
      {
        title: "Est. Category Share",
        value: "37.1%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "37.1%", change: "▲0.2 pp" },
      },
      {
        title: "Category Size",
        value: "₹27.5 Cr",
        change: { text: "▲1.9% (+₹51.9 lac)", positive: true },
        meta: { units: "2750 lac", change: "▲1.9%" },
      },
      {
        title: "Wt. OSA%",
        value: "75.8%",
        change: { text: "▼1.2 pp", positive: false },
        meta: { units: "75.8%", change: "▼1.2 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "27.8%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "27.8%", change: "▲0.5 pp" },
      },
    ],
  },

  // ---------- AUG ----------
  {
    key: "aug",
    label: "Aug",
    logo: monthLogos["aug"],
    columns: [
      {
        title: "Offtake",
        value: "₹11.4 Cr",
        change: { text: "▲2.9% (+₹32.1 lac)", positive: true },
        meta: { units: "5.9 lac", change: "▲1.5%" },
      },
      {
        title: "Est. Category Share",
        value: "37.6%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "37.6%", change: "▲0.3 pp" },
      },
      {
        title: "Category Size",
        value: "₹28.0 Cr",
        change: { text: "▲2.0% (+₹54.9 lac)", positive: true },
        meta: { units: "2800 lac", change: "▲2.0%" },
      },
      {
        title: "Wt. OSA%",
        value: "75.1%",
        change: { text: "▼1.4 pp", positive: false },
        meta: { units: "75.1%", change: "▼1.4 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "28.2%",
        change: { text: "▲0.6 pp", positive: true },
        meta: { units: "28.2%", change: "▲0.6 pp" },
      },
    ],
  },

  // ---------- SEP ----------
  {
    key: "sep",
    label: "Sep",
    logo: monthLogos["sep"],
    columns: [
      {
        title: "Offtake",
        value: "₹11.2 Cr",
        change: { text: "▼1.5% (-₹16.8 lac)", positive: false },
        meta: { units: "5.6 lac", change: "▼1.2%" },
      },
      {
        title: "Est. Category Share",
        value: "36.9%",
        change: { text: "▼0.4 pp", positive: false },
        meta: { units: "36.9%", change: "▼0.4 pp" },
      },
      {
        title: "Category Size",
        value: "₹28.4 Cr",
        change: { text: "▲1.4% (+₹39.6 lac)", positive: true },
        meta: { units: "2840 lac", change: "▲1.4%" },
      },
      {
        title: "Wt. OSA%",
        value: "74.3%",
        change: { text: "▼1.8 pp", positive: false },
        meta: { units: "74.3%", change: "▼1.8 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "28.0%",
        change: { text: "▼0.2 pp", positive: false },
        meta: { units: "28.0%", change: "▼0.2 pp" },
      },
    ],
  },

  // ---------- OCT ----------
  {
    key: "oct",
    label: "Oct",
    logo: monthLogos["oct"],
    columns: [
      {
        title: "Offtake",
        value: "₹12.1 Cr",
        change: { text: "▲4.1% (+₹47.2 lac)", positive: true },
        meta: { units: "6.1 lac", change: "▲2.4%" },
      },
      {
        title: "Est. Category Share",
        value: "38.0%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "38.0%", change: "▲0.5 pp" },
      },
      {
        title: "Category Size",
        value: "₹29.0 Cr",
        change: { text: "▲2.1% (+₹59.2 lac)", positive: true },
        meta: { units: "2900 lac", change: "▲2.1%" },
      },
      {
        title: "Wt. OSA%",
        value: "75.6%",
        change: { text: "▲1.3 pp", positive: true },
        meta: { units: "75.6%", change: "▲1.3 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "28.5%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "28.5%", change: "▲0.5 pp" },
      },
    ],
  },

  // ---------- NOV ----------
  {
    key: "nov",
    label: "Nov",
    logo: monthLogos["nov"],
    columns: [
      {
        title: "Offtake",
        value: "₹12.4 Cr",
        change: { text: "▲2.1% (+₹26.0 lac)", positive: true },
        meta: { units: "6.2 lac", change: "▲1.0%" },
      },
      {
        title: "Est. Category Share",
        value: "38.5%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "38.5%", change: "▲0.3 pp" },
      },
      {
        title: "Category Size",
        value: "₹29.4 Cr",
        change: { text: "▲1.7% (+₹49.0 lac)", positive: true },
        meta: { units: "2940 lac", change: "▲1.7%" },
      },
      {
        title: "Wt. OSA%",
        value: "76.0%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "76.0%", change: "▲0.4 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "28.7%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "28.7%", change: "▲0.2 pp" },
      },
    ],
  },

  // ---------- DEC ----------
  {
    key: "dec",
    label: "Dec",
    logo: monthLogos["dec"],
    columns: [
      {
        title: "Offtake",
        value: "₹13.0 Cr",
        change: { text: "▲3.8% (+₹47.4 lac)", positive: true },
        meta: { units: "6.5 lac", change: "▲2.2%" },
      },
      {
        title: "Est. Category Share",
        value: "39.1%",
        change: { text: "▲0.6 pp", positive: true },
        meta: { units: "39.1%", change: "▲0.6 pp" },
      },
      {
        title: "Category Size",
        value: "₹29.9 Cr",
        change: { text: "▲1.9% (+₹55.0 lac)", positive: true },
        meta: { units: "2990 lac", change: "▲1.9%" },
      },
      {
        title: "Wt. OSA%",
        value: "76.4%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "76.4%", change: "▲0.4 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "29.1%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "29.1%", change: "▲0.4 pp" },
      },
    ],
  },
];

export const defaultCategory = [
  {
    key: "cassata",
    label: "Cassata",
    logo: categoryLogo,
    columns: [
      {
        title: "Offtake",
        value: "₹1.2 Cr",
        change: { text: "▲2.8% (+₹3.3 lac)", positive: true },
        meta: { units: "0.62 lac", change: "▲1.5%" },
      },
      {
        title: "Est. Category Share",
        value: "7.8%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "7.8%", change: "▲0.2 pp" },
      },
      {
        title: "Category Size",
        value: "₹15.4 Cr",
        change: { text: "▲2.1% (+₹31.5 lac)", positive: true },
        meta: { units: "1540 lac", change: "▲2.1%" },
      },
      {
        title: "Wt. OSA%",
        value: "82.5%",
        change: { text: "▼3.2 pp", positive: false },
        meta: { units: "82.5%", change: "▼3.2 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "21.4%",
        change: { text: "▲1.1 pp", positive: true },
        meta: { units: "21.4%", change: "▲1.1 pp" },
      },
    ],
  },

  {
    key: "coreTub",
    label: "Core Tub",
    logo: categoryLogo,
    columns: [
      {
        title: "Offtake",
        value: "₹2.9 Cr",
        change: { text: "▲3.5% (+₹9.9 lac)", positive: true },
        meta: { units: "1.45 lac", change: "▲2.2%" },
      },
      {
        title: "Est. Category Share",
        value: "21.2%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "21.2%", change: "▲0.3 pp" },
      },
      {
        title: "Category Size",
        value: "₹13.7 Cr",
        change: { text: "▲2.4% (+₹32.9 lac)", positive: true },
        meta: { units: "1370 lac", change: "▲2.4%" },
      },
      {
        title: "Wt. OSA%",
        value: "77.1%",
        change: { text: "▼2.1 pp", positive: false },
        meta: { units: "77.1%", change: "▼2.1 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "24.6%",
        change: { text: "▲1.4 pp", positive: true },
        meta: { units: "24.6%", change: "▲1.4 pp" },
      },
    ],
  },

  {
    key: "cornetto",
    label: "Cornetto",
    logo: categoryLogo,
    columns: [
      {
        title: "Offtake",
        value: "₹3.7 Cr",
        change: { text: "▲4.1% (+₹14.8 lac)", positive: true },
        meta: { units: "1.93 lac", change: "▲3.0%" },
      },
      {
        title: "Est. Category Share",
        value: "26.5%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "26.5%", change: "▲0.4 pp" },
      },
      {
        title: "Category Size",
        value: "₹14.1 Cr",
        change: { text: "▲2.6% (+₹35.7 lac)", positive: true },
        meta: { units: "1410 lac", change: "▲2.6%" },
      },
      {
        title: "Wt. OSA%",
        value: "80.2%",
        change: { text: "▼1.8 pp", positive: false },
        meta: { units: "80.2%", change: "▼1.8 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "26.1%",
        change: { text: "▲1.8 pp", positive: true },
        meta: { units: "26.1%", change: "▲1.8 pp" },
      },
    ],
  },

  {
    key: "cup",
    label: "Cup",
    logo: categoryLogo,
    columns: [
      {
        title: "Offtake",
        value: "₹1.8 Cr",
        change: { text: "▲2.2% (+₹3.9 lac)", positive: true },
        meta: { units: "0.98 lac", change: "▲1.0%" },
      },
      {
        title: "Est. Category Share",
        value: "12.8%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "12.8%", change: "▲0.1 pp" },
      },
      {
        title: "Category Size",
        value: "₹14.2 Cr",
        change: { text: "▲2.5% (+₹34.8 lac)", positive: true },
        meta: { units: "1420 lac", change: "▲2.5%" },
      },
      {
        title: "Wt. OSA%",
        value: "83.0%",
        change: { text: "▼1.2 pp", positive: false },
        meta: { units: "83.0%", change: "▼1.2 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "23.7%",
        change: { text: "▲0.8 pp", positive: true },
        meta: { units: "23.7%", change: "▲0.8 pp" },
      },
    ],
  },

  {
    key: "kwSticks",
    label: "KW Sticks",
    logo: categoryLogo,
    columns: [
      {
        title: "Offtake",
        value: "₹2.4 Cr",
        change: { text: "▲3.0% (+₹7.1 lac)", positive: true },
        meta: { units: "1.22 lac", change: "▲1.8%" },
      },
      {
        title: "Est. Category Share",
        value: "17.4%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "17.4%", change: "▲0.3 pp" },
      },
      {
        title: "Category Size",
        value: "₹13.9 Cr",
        change: { text: "▲2.3% (+₹31.9 lac)", positive: true },
        meta: { units: "1390 lac", change: "▲2.3%" },
      },
      {
        title: "Wt. OSA%",
        value: "79.4%",
        change: { text: "▼2.7 pp", positive: false },
        meta: { units: "79.4%", change: "▼2.7 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "27.2%",
        change: { text: "▲1.6 pp", positive: true },
        meta: { units: "27.2%", change: "▲1.6 pp" },
      },
    ],
  },

  {
    key: "magnum",
    label: "Magnum",
    logo: categoryLogo,
    columns: [
      {
        title: "Offtake",
        value: "₹1.4 Cr",
        change: { text: "▲2.9% (+₹4.1 lac)", positive: true },
        meta: { units: "0.73 lac", change: "▲1.6%" },
      },
      {
        title: "Est. Category Share",
        value: "10.1%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "10.1%", change: "▲0.2 pp" },
      },
      {
        title: "Category Size",
        value: "₹13.8 Cr",
        change: { text: "▲2.4% (+₹32.4 lac)", positive: true },
        meta: { units: "1380 lac", change: "▲2.4%" },
      },
      {
        title: "Wt. OSA%",
        value: "81.8%",
        change: { text: "▼1.5 pp", positive: false },
        meta: { units: "81.8%", change: "▼1.5 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "25.4%",
        change: { text: "▲0.9 pp", positive: true },
        meta: { units: "25.4%", change: "▲0.9 pp" },
      },
    ],
  },

  {
    key: "others",
    label: "Others",
    logo: categoryLogo,
    columns: [
      {
        title: "Offtake",
        value: "₹0.95 Cr",
        change: { text: "▲1.7% (+₹1.6 lac)", positive: true },
        meta: { units: "0.51 lac", change: "▲0.7%" },
      },
      {
        title: "Est. Category Share",
        value: "4.0%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "4.0%", change: "▲0.1 pp" },
      },
      {
        title: "Category Size",
        value: "₹13.9 Cr",
        change: { text: "▲2.4% (+₹32.8 lac)", positive: true },
        meta: { units: "1390 lac", change: "▲2.4%" },
      },
      {
        title: "Wt. OSA%",
        value: "78.2%",
        change: { text: "▼1.9 pp", positive: false },
        meta: { units: "78.2%", change: "▼1.9 pp" },
      },
      {
        title: "Wt. Disc %",
        value: "22.5%",
        change: { text: "▲0.6 pp", positive: true },
        meta: { units: "22.5%", change: "▲0.6 pp" },
      },
    ],
  },
];

export const allCategories = [
  {
    name: "Fresheners",
    all: {
      offtake: "₹3.15 Cr",
      offtake_change: "+2.3%",
      category_share: "35%",
      category_share_change: "+1.1%",
      category_size: "₹9.0 Cr",
      category_size_change: "+3.2%",
      wt_osa: "92.1%",
      wt_osa_change: "+0.8%",
      wt_disc: "6.8%",
      wt_disc_change: "-0.3%",
      overall_sov: "27.4%",
      overall_sov_change: "+2.2%",
      impressions: "4.2 Cr",
      impressions_change: "+4.1%",
      clicks: "6.4 L",
      clicks_change: "+3.5%",
      ctr: "1.52%",
      ctr_change: "-0.2%",
      cvr: "3.9%",
      cvr_change: "+0.5%",
      orders: "24.6K",
      orders_change: "+1.9%",
      ad_spends: "₹38.6L",
      ad_spends_change: "+4.2%",
      roas: "4.8x",
      roas_change: "-1.3%",
    },
    blinkit: {
      offtake: "₹1.05 Cr",
      offtake_change: "+3.1%",
      category_share: "33%",
      category_share_change: "+1.0%",
      category_size: "₹3.2 Cr",
      category_size_change: "+2.8%",
      wt_osa: "91.5%",
      wt_osa_change: "+0.7%",
      wt_disc: "6.2%",
      wt_disc_change: "-0.2%",
      overall_sov: "26.8%",
      overall_sov_change: "+1.9%",
      impressions: "1.4 Cr",
      impressions_change: "+3.8%",
      clicks: "2.2 L",
      clicks_change: "+3.0%",
      ctr: "1.57%",
      ctr_change: "-0.1%",
      cvr: "4.0%",
      cvr_change: "+0.6%",
      orders: "8.4K",
      orders_change: "+2.0%",
      ad_spends: "₹12.3L",
      ad_spends_change: "+3.9%",
      roas: "4.9x",
      roas_change: "-1.0%",
    },
    zepto: {
      offtake: "₹0.82 Cr",
      offtake_change: "+2.7%",
      category_share: "26%",
      category_share_change: "+0.9%",
      category_size: "₹2.5 Cr",
      category_size_change: "+3.0%",
      wt_osa: "92.0%",
      wt_osa_change: "+0.6%",
      wt_disc: "5.9%",
      wt_disc_change: "-0.3%",
      overall_sov: "25.3%",
      overall_sov_change: "+1.8%",
      impressions: "1.1 Cr",
      impressions_change: "+3.2%",
      clicks: "1.6 L",
      clicks_change: "+2.5%",
      ctr: "1.45%",
      ctr_change: "-0.2%",
      cvr: "3.8%",
      cvr_change: "+0.5%",
      orders: "6.3K",
      orders_change: "+1.6%",
      ad_spends: "₹9.8L",
      ad_spends_change: "+3.1%",
      roas: "4.7x",
      roas_change: "-0.9%",
    },
    swiggy: {
      offtake: "₹0.64 Cr",
      offtake_change: "+2.1%",
      category_share: "20%",
      category_share_change: "+0.8%",
      category_size: "₹2.0 Cr",
      category_size_change: "+2.9%",
      wt_osa: "90.8%",
      wt_osa_change: "+0.5%",
      wt_disc: "6.1%",
      wt_disc_change: "-0.3%",
      overall_sov: "23.5%",
      overall_sov_change: "+1.6%",
      impressions: "0.9 Cr",
      impressions_change: "+3.0%",
      clicks: "1.3 L",
      clicks_change: "+2.2%",
      ctr: "1.44%",
      ctr_change: "-0.1%",
      cvr: "3.7%",
      cvr_change: "+0.4%",
      orders: "5.1K",
      orders_change: "+1.5%",
      ad_spends: "₹8.2L",
      ad_spends_change: "+2.8%",
      roas: "4.6x",
      roas_change: "-0.7%",
    },
    amazon: {
      offtake: "₹0.35 Cr",
      offtake_change: "+3.4%",
      category_share: "10%",
      category_share_change: "+1.0%",
      category_size: "₹1.2 Cr",
      category_size_change: "+3.1%",
      wt_osa: "89.9%",
      wt_osa_change: "+0.5%",
      wt_disc: "6.3%",
      wt_disc_change: "-0.2%",
      overall_sov: "21.7%",
      overall_sov_change: "+1.5%",
      impressions: "0.6 Cr",
      impressions_change: "+2.9%",
      clicks: "0.8 L",
      clicks_change: "+2.1%",
      ctr: "1.33%",
      ctr_change: "-0.1%",
      cvr: "3.6%",
      cvr_change: "+0.4%",
      orders: "3.4K",
      orders_change: "+1.3%",
      ad_spends: "₹6.3L",
      ad_spends_change: "+2.4%",
      roas: "4.5x",
      roas_change: "-0.6%",
    },
    flipkart: {
      offtake: "₹0.29 Cr",
      offtake_change: "+1.9%",
      category_share: "8%",
      category_share_change: "+0.7%",
      category_size: "₹1.0 Cr",
      category_size_change: "+3.0%",
      wt_osa: "89.5%",
      wt_osa_change: "+0.4%",
      wt_disc: "6.4%",
      wt_disc_change: "-0.2%",
      overall_sov: "20.4%",
      overall_sov_change: "+1.2%",
      impressions: "0.5 Cr",
      impressions_change: "+2.8%",
      clicks: "0.6 L",
      clicks_change: "+2.0%",
      ctr: "1.30%",
      ctr_change: "-0.1%",
      cvr: "3.5%",
      cvr_change: "+0.4%",
      orders: "2.8K",
      orders_change: "+1.2%",
      ad_spends: "₹5.7L",
      ad_spends_change: "+2.1%",
      roas: "4.4x",
      roas_change: "-0.5%",
    },
  },
  {
    name: "Gel",
    all: {
      offtake: "₹2.25 Cr",
      offtake_change: "-1.5%",
      category_share: "25%",
      category_share_change: "-0.7%",
      category_size: "₹9.0 Cr",
      category_size_change: "+3.2%",
      wt_osa: "88.4%",
      wt_osa_change: "+0.4%",
      wt_disc: "5.2%",
      wt_disc_change: "+0.2%",
      overall_sov: "22.8%",
      overall_sov_change: "-1.5%",
      impressions: "3.1 Cr",
      impressions_change: "-2.1%",
      clicks: "4.8 L",
      clicks_change: "-1.4%",
      ctr: "1.55%",
      ctr_change: "+0.3%",
      cvr: "4.1%",
      cvr_change: "-0.6%",
      orders: "19.4K",
      orders_change: "-0.9%",
      ad_spends: "₹31.8L",
      ad_spends_change: "-1.1%",
      roas: "4.3x",
      roas_change: "-0.8%",
    },
    blinkit: {
      offtake: "₹0.75 Cr",
      offtake_change: "-0.9%",
      category_share: "30%",
      category_share_change: "-0.5%",
      category_size: "₹2.6 Cr",
      category_size_change: "+2.7%",
      wt_osa: "87.5%",
      wt_osa_change: "+0.3%",
      wt_disc: "5.4%",
      wt_disc_change: "+0.2%",
      overall_sov: "21.9%",
      overall_sov_change: "-1.3%",
      impressions: "1.0 Cr",
      impressions_change: "-1.7%",
      clicks: "1.6 L",
      clicks_change: "-1.0%",
      ctr: "1.60%",
      ctr_change: "+0.2%",
      cvr: "4.0%",
      cvr_change: "-0.5%",
      orders: "6.3K",
      orders_change: "-0.7%",
      ad_spends: "₹10.4L",
      ad_spends_change: "-0.8%",
      roas: "4.4x",
      roas_change: "-0.7%",
    },
    zepto: {
      offtake: "₹0.57 Cr",
      offtake_change: "-1.2%",
      category_share: "25%",
      category_share_change: "-0.6%",
      category_size: "₹2.2 Cr",
      category_size_change: "+2.8%",
      wt_osa: "88.0%",
      wt_osa_change: "+0.4%",
      wt_disc: "5.1%",
      wt_disc_change: "+0.1%",
      overall_sov: "22.1%",
      overall_sov_change: "-1.4%",
      impressions: "0.8 Cr",
      impressions_change: "-1.6%",
      clicks: "1.3 L",
      clicks_change: "-0.9%",
      ctr: "1.58%",
      ctr_change: "+0.2%",
      cvr: "4.1%",
      cvr_change: "-0.4%",
      orders: "5.0K",
      orders_change: "-0.8%",
      ad_spends: "₹8.9L",
      ad_spends_change: "-0.9%",
      roas: "4.3x",
      roas_change: "-0.6%",
    },
    swiggy: {
      offtake: "₹0.46 Cr",
      offtake_change: "-1.0%",
      category_share: "20%",
      category_share_change: "-0.4%",
      category_size: "₹1.8 Cr",
      category_size_change: "+2.9%",
      wt_osa: "87.8%",
      wt_osa_change: "+0.3%",
      wt_disc: "5.3%",
      wt_disc_change: "+0.1%",
      overall_sov: "22.4%",
      overall_sov_change: "-1.2%",
      impressions: "0.7 Cr",
      impressions_change: "-1.5%",
      clicks: "1.0 L",
      clicks_change: "-0.8%",
      ctr: "1.52%",
      ctr_change: "+0.2%",
      cvr: "4.0%",
      cvr_change: "-0.5%",
      orders: "4.1K",
      orders_change: "-0.6%",
      ad_spends: "₹7.8L",
      ad_spends_change: "-0.7%",
      roas: "4.2x",
      roas_change: "-0.5%",
    },
    amazon: {
      offtake: "₹0.27 Cr",
      offtake_change: "-0.6%",
      category_share: "12%",
      category_share_change: "-0.3%",
      category_size: "₹1.2 Cr",
      category_size_change: "+2.8%",
      wt_osa: "86.9%",
      wt_osa_change: "+0.3%",
      wt_disc: "5.2%",
      wt_disc_change: "+0.2%",
      overall_sov: "21.8%",
      overall_sov_change: "-1.0%",
      impressions: "0.5 Cr",
      impressions_change: "-1.3%",
      clicks: "0.7 L",
      clicks_change: "-0.7%",
      ctr: "1.40%",
      ctr_change: "+0.1%",
      cvr: "3.9%",
      cvr_change: "-0.4%",
      orders: "3.0K",
      orders_change: "-0.5%",
      ad_spends: "₹6.2L",
      ad_spends_change: "-0.6%",
      roas: "4.1x",
      roas_change: "-0.4%",
    },
    flipkart: {
      offtake: "₹0.20 Cr",
      offtake_change: "-0.8%",
      category_share: "8%",
      category_share_change: "-0.2%",
      category_size: "₹1.0 Cr",
      category_size_change: "+2.7%",
      wt_osa: "86.5%",
      wt_osa_change: "+0.2%",
      wt_disc: "5.3%",
      wt_disc_change: "+0.1%",
      overall_sov: "21.2%",
      overall_sov_change: "-0.9%",
      impressions: "0.4 Cr",
      impressions_change: "-1.2%",
      clicks: "0.6 L",
      clicks_change: "-0.6%",
      ctr: "1.35%",
      ctr_change: "+0.1%",
      cvr: "3.8%",
      cvr_change: "-0.3%",
      orders: "2.4K",
      orders_change: "-0.4%",
      ad_spends: "₹5.1L",
      ad_spends_change: "-0.5%",
      roas: "4.0x",
      roas_change: "-0.3%",
    },
  },
  {
    name: "Detergent",
    all: {
      offtake: "₹2.25 Cr",
      offtake_change: "+1.1%",
      category_share: "25%",
      category_share_change: "+0.5%",
      category_size: "₹9.0 Cr",
      category_size_change: "+3.2%",
      wt_osa: "89.6%",
      wt_osa_change: "+0.7%",
      wt_disc: "4.9%",
      wt_disc_change: "-0.4%",
      overall_sov: "25.6%",
      overall_sov_change: "+1.2%",
      impressions: "3.3 Cr",
      impressions_change: "+1.7%",
      clicks: "5.0 L",
      clicks_change: "+2.3%",
      ctr: "1.51%",
      ctr_change: "-0.1%",
      cvr: "3.8%",
      cvr_change: "+0.4%",
      orders: "20.1K",
      orders_change: "+1.5%",
      ad_spends: "₹33.4L",
      ad_spends_change: "+2.1%",
      roas: "4.6x",
      roas_change: "+0.9%",
    },
    blinkit: {
      offtake: "₹0.75 Cr",
      offtake_change: "+1.6%",
      category_share: "30%",
      category_share_change: "+0.8%",
      category_size: "₹2.5 Cr",
      category_size_change: "+2.9%",
      wt_osa: "89.0%",
      wt_osa_change: "+0.6%",
      wt_disc: "4.7%",
      wt_disc_change: "-0.3%",
      overall_sov: "24.9%",
      overall_sov_change: "+1.1%",
      impressions: "1.1 Cr",
      impressions_change: "+1.5%",
      clicks: "1.6 L",
      clicks_change: "+2.0%",
      ctr: "1.45%",
      ctr_change: "-0.1%",
      cvr: "3.8%",
      cvr_change: "+0.4%",
      orders: "6.4K",
      orders_change: "+1.3%",
      ad_spends: "₹10.2L",
      ad_spends_change: "+1.7%",
      roas: "4.6x",
      roas_change: "+0.8%",
    },
    zepto: {
      offtake: "₹0.57 Cr",
      offtake_change: "+0.8%",
      category_share: "25%",
      category_share_change: "+0.6%",
      category_size: "₹2.1 Cr",
      category_size_change: "+2.8%",
      wt_osa: "89.4%",
      wt_osa_change: "+0.5%",
      wt_disc: "4.8%",
      wt_disc_change: "-0.2%",
      overall_sov: "25.0%",
      overall_sov_change: "+1.0%",
      impressions: "0.9 Cr",
      impressions_change: "+1.4%",
      clicks: "1.3 L",
      clicks_change: "+1.8%",
      ctr: "1.44%",
      ctr_change: "-0.1%",
      cvr: "3.7%",
      cvr_change: "+0.3%",
      orders: "5.0K",
      orders_change: "+1.2%",
      ad_spends: "₹8.7L",
      ad_spends_change: "+1.5%",
      roas: "4.5x",
      roas_change: "+0.7%",
    },
    swiggy: {
      offtake: "₹0.52 Cr",
      offtake_change: "+0.9%",
      category_share: "22%",
      category_share_change: "+0.5%",
      category_size: "₹2.0 Cr",
      category_size_change: "+2.7%",
      wt_osa: "89.1%",
      wt_osa_change: "+0.5%",
      wt_disc: "4.9%",
      wt_disc_change: "-0.2%",
      overall_sov: "24.6%",
      overall_sov_change: "+0.9%",
      impressions: "0.8 Cr",
      impressions_change: "+1.3%",
      clicks: "1.1 L",
      clicks_change: "+1.7%",
      ctr: "1.43%",
      ctr_change: "-0.1%",
      cvr: "3.7%",
      cvr_change: "+0.3%",
      orders: "4.2K",
      orders_change: "+1.1%",
      ad_spends: "₹7.6L",
      ad_spends_change: "+1.4%",
      roas: "4.4x",
      roas_change: "+0.6%",
    },
    amazon: {
      offtake: "₹0.28 Cr",
      offtake_change: "+0.7%",
      category_share: "12%",
      category_share_change: "+0.4%",
      category_size: "₹1.2 Cr",
      category_size_change: "+2.6%",
      wt_osa: "88.5%",
      wt_osa_change: "+0.4%",
      wt_disc: "4.8%",
      wt_disc_change: "-0.2%",
      overall_sov: "23.9%",
      overall_sov_change: "+0.8%",
      impressions: "0.5 Cr",
      impressions_change: "+1.1%",
      clicks: "0.7 L",
      clicks_change: "+1.5%",
      ctr: "1.40%",
      ctr_change: "-0.1%",
      cvr: "3.6%",
      cvr_change: "+0.2%",
      orders: "2.8K",
      orders_change: "+1.0%",
      ad_spends: "₹6.1L",
      ad_spends_change: "+1.3%",
      roas: "4.3x",
      roas_change: "+0.5%",
    },
    flipkart: {
      offtake: "₹0.20 Cr",
      offtake_change: "+0.5%",
      category_share: "8%",
      category_share_change: "+0.3%",
      category_size: "₹1.0 Cr",
      category_size_change: "+2.6%",
      wt_osa: "88.2%",
      wt_osa_change: "+0.3%",
      wt_disc: "4.9%",
      wt_disc_change: "-0.2%",
      overall_sov: "23.4%",
      overall_sov_change: "+0.7%",
      impressions: "0.4 Cr",
      impressions_change: "+1.0%",
      clicks: "0.6 L",
      clicks_change: "+1.4%",
      ctr: "1.38%",
      ctr_change: "-0.1%",
      cvr: "3.5%",
      cvr_change: "+0.2%",
      orders: "2.1K",
      orders_change: "+0.9%",
      ad_spends: "₹5.2L",
      ad_spends_change: "+1.2%",
      roas: "4.2x",
      roas_change: "+0.4%",
    },
  },
  {
    name: "Soap",
    all: {
      offtake: "₹1.35 Cr",
      offtake_change: "-0.8%",
      category_share: "15%",
      category_share_change: "-0.5%",
      category_size: "₹9.0 Cr",
      category_size_change: "+2.7%",
      wt_osa: "88.7%",
      wt_osa_change: "-0.4%",
      wt_disc: "5.2%",
      wt_disc_change: "+0.3%",
      overall_sov: "18.3%",
      overall_sov_change: "-0.6%",
      impressions: "2.2 Cr",
      impressions_change: "-1.1%",
      clicks: "3.1 L",
      clicks_change: "-1.4%",
      ctr: "1.41%",
      ctr_change: "-0.2%",
      cvr: "3.4%",
      cvr_change: "-0.3%",
      orders: "10.5K",
      orders_change: "-1.0%",
      ad_spends: "₹22.6L",
      ad_spends_change: "-0.8%",
      roas: "4.1x",
      roas_change: "-0.5%",
    },
    blinkit: {
      offtake: "₹0.47 Cr",
      offtake_change: "-0.6%",
      category_share: "35%",
      category_share_change: "-0.4%",
      category_size: "₹1.9 Cr",
      category_size_change: "+2.4%",
      wt_osa: "88.5%",
      wt_osa_change: "-0.3%",
      wt_disc: "5.3%",
      wt_disc_change: "+0.3%",
      overall_sov: "18.1%",
      overall_sov_change: "-0.5%",
      impressions: "0.7 Cr",
      impressions_change: "-1.0%",
      clicks: "1.0 L",
      clicks_change: "-1.3%",
      ctr: "1.42%",
      ctr_change: "-0.2%",
      cvr: "3.5%",
      cvr_change: "-0.2%",
      orders: "3.7K",
      orders_change: "-0.9%",
      ad_spends: "₹7.5L",
      ad_spends_change: "-0.7%",
      roas: "4.2x",
      roas_change: "-0.4%",
    },
    zepto: {
      offtake: "₹0.34 Cr",
      offtake_change: "-0.7%",
      category_share: "25%",
      category_share_change: "-0.5%",
      category_size: "₹1.5 Cr",
      category_size_change: "+2.3%",
      wt_osa: "88.6%",
      wt_osa_change: "-0.3%",
      wt_disc: "5.2%",
      wt_disc_change: "+0.2%",
      overall_sov: "18.2%",
      overall_sov_change: "-0.5%",
      impressions: "0.5 Cr",
      impressions_change: "-1.1%",
      clicks: "0.7 L",
      clicks_change: "-1.4%",
      ctr: "1.41%",
      ctr_change: "-0.2%",
      cvr: "3.4%",
      cvr_change: "-0.3%",
      orders: "2.9K",
      orders_change: "-1.0%",
      ad_spends: "₹6.2L",
      ad_spends_change: "-0.8%",
      roas: "4.1x",
      roas_change: "-0.5%",
    },
    swiggy: {
      offtake: "₹0.27 Cr",
      offtake_change: "-0.8%",
      category_share: "20%",
      category_share_change: "-0.6%",
      category_size: "₹1.3 Cr",
      category_size_change: "+2.3%",
      wt_osa: "88.4%",
      wt_osa_change: "-0.3%",
      wt_disc: "5.2%",
      wt_disc_change: "+0.2%",
      overall_sov: "18.3%",
      overall_sov_change: "-0.5%",
      impressions: "0.4 Cr",
      impressions_change: "-1.1%",
      clicks: "0.6 L",
      clicks_change: "-1.4%",
      ctr: "1.40%",
      ctr_change: "-0.2%",
      cvr: "3.3%",
      cvr_change: "-0.3%",
      orders: "2.3K",
      orders_change: "-1.0%",
      ad_spends: "₹5.3L",
      ad_spends_change: "-0.8%",
      roas: "4.0x",
      roas_change: "-0.5%",
    },
    amazon: {
      offtake: "₹0.16 Cr",
      offtake_change: "-0.9%",
      category_share: "12%",
      category_share_change: "-0.6%",
      category_size: "₹1.1 Cr",
      category_size_change: "+2.2%",
      wt_osa: "88.2%",
      wt_osa_change: "-0.4%",
      wt_disc: "5.1%",
      wt_disc_change: "+0.2%",
      overall_sov: "18.4%",
      overall_sov_change: "-0.5%",
      impressions: "0.3 Cr",
      impressions_change: "-1.1%",
      clicks: "0.4 L",
      clicks_change: "-1.3%",
      ctr: "1.39%",
      ctr_change: "-0.2%",
      cvr: "3.3%",
      cvr_change: "-0.3%",
      orders: "1.6K",
      orders_change: "-1.0%",
      ad_spends: "₹4.5L",
      ad_spends_change: "-0.8%",
      roas: "4.0x",
      roas_change: "-0.5%",
    },
    flipkart: {
      offtake: "₹0.11 Cr",
      offtake_change: "-1.0%",
      category_share: "8%",
      category_share_change: "-0.6%",
      category_size: "₹1.0 Cr",
      category_size_change: "+2.2%",
      wt_osa: "88.1%",
      wt_osa_change: "-0.4%",
      wt_disc: "5.0%",
      wt_disc_change: "+0.2%",
      overall_sov: "18.5%",
      overall_sov_change: "-0.5%",
      impressions: "0.2 Cr",
      impressions_change: "-1.1%",
      clicks: "0.3 L",
      clicks_change: "-1.3%",
      ctr: "1.38%",
      ctr_change: "-0.2%",
      cvr: "3.2%",
      cvr_change: "-0.3%",
      orders: "1.1K",
      orders_change: "-1.0%",
      ad_spends: "₹3.9L",
      ad_spends_change: "-0.8%",
      roas: "3.9x",
      roas_change: "-0.5%",
    },
  },
];

export const allProducts = [
  {
    name: "Colgate Visible White 02 Whitening Toothpaste - 100g",
    all: {
      offtake: "₹3.42 Cr",
      offtake_change: "+3.1%",
      category_share: "37%",
      category_share_change: "+1.4%",
      category_size: "₹9.3 Cr",
      category_size_change: "+3.8%",
      wt_osa: "93.4%",
      wt_osa_change: "+1.1%",
      wt_disc: "6.1%",
      wt_disc_change: "-0.4%",
      overall_sov: "28.2%",
      overall_sov_change: "+2.5%",
      impressions: "4.5 Cr",
      impressions_change: "+4.4%",
      clicks: "6.9 L",
      clicks_change: "+3.9%",
      ctr: "1.54%",
      ctr_change: "-0.1%",
      cvr: "4.2%",
      cvr_change: "+0.7%",
      orders: "26.3K",
      orders_change: "+2.4%",
      ad_spends: "₹39.8L",
      ad_spends_change: "+4.6%",
      roas: "5.1x",
      roas_change: "-1.0%",
    },
    blinkit: {
      offtake: "₹1.18 Cr",
      offtake_change: "+3.8%",
      category_share: "34%",
      category_share_change: "+1.3%",
      category_size: "₹3.4 Cr",
      category_size_change: "+3.1%",
      wt_osa: "92.7%",
      wt_osa_change: "+0.8%",
      wt_disc: "5.8%",
      wt_disc_change: "-0.3%",
      overall_sov: "27.6%",
      overall_sov_change: "+2.1%",
      impressions: "1.5 Cr",
      impressions_change: "+4.0%",
      clicks: "2.4 L",
      clicks_change: "+3.3%",
      ctr: "1.60%",
      ctr_change: "-0.1%",
      cvr: "4.3%",
      cvr_change: "+0.7%",
      orders: "9.1K",
      orders_change: "+2.4%",
      ad_spends: "₹12.9L",
      ad_spends_change: "+4.1%",
      roas: "5.2x",
      roas_change: "-0.8%",
    },
    zepto: {
      offtake: "₹0.90 Cr",
      offtake_change: "+3.0%",
      category_share: "27%",
      category_share_change: "+1.0%",
      category_size: "₹2.6 Cr",
      category_size_change: "+3.5%",
      wt_osa: "93.0%",
      wt_osa_change: "+0.9%",
      wt_disc: "5.6%",
      wt_disc_change: "-0.2%",
      overall_sov: "26.1%",
      overall_sov_change: "+1.9%",
      impressions: "1.2 Cr",
      impressions_change: "+3.5%",
      clicks: "1.7 L",
      clicks_change: "+2.8%",
      ctr: "1.47%",
      ctr_change: "-0.1%",
      cvr: "4.0%",
      cvr_change: "+0.6%",
      orders: "6.9K",
      orders_change: "+1.9%",
      ad_spends: "₹10.2L",
      ad_spends_change: "+3.3%",
      roas: "4.9x",
      roas_change: "-0.7%",
    },
    swiggy: {
      offtake: "₹0.70 Cr",
      offtake_change: "+2.8%",
      category_share: "21%",
      category_share_change: "+0.9%",
      category_size: "₹2.1 Cr",
      category_size_change: "+3.2%",
      wt_osa: "91.8%",
      wt_osa_change: "+0.6%",
      wt_disc: "5.9%",
      wt_disc_change: "-0.2%",
      overall_sov: "24.3%",
      overall_sov_change: "+1.7%",
      impressions: "1.0 Cr",
      impressions_change: "+3.2%",
      clicks: "1.5 L",
      clicks_change: "+2.4%",
      ctr: "1.46%",
      ctr_change: "-0.1%",
      cvr: "3.9%",
      cvr_change: "+0.4%",
      orders: "5.7K",
      orders_change: "+1.6%",
      ad_spends: "₹8.8L",
      ad_spends_change: "+3.0%",
      roas: "4.7x",
      roas_change: "-0.6%",
    },
    amazon: {
      offtake: "₹0.38 Cr",
      offtake_change: "+3.6%",
      category_share: "11%",
      category_share_change: "+1.1%",
      category_size: "₹1.3 Cr",
      category_size_change: "+3.3%",
      wt_osa: "90.7%",
      wt_osa_change: "+0.6%",
      wt_disc: "6.0%",
      wt_disc_change: "-0.2%",
      overall_sov: "22.4%",
      overall_sov_change: "+1.6%",
      impressions: "0.7 Cr",
      impressions_change: "+3.1%",
      clicks: "0.9 L",
      clicks_change: "+2.3%",
      ctr: "1.35%",
      ctr_change: "-0.1%",
      cvr: "3.8%",
      cvr_change: "+0.4%",
      orders: "3.7K",
      orders_change: "+1.4%",
      ad_spends: "₹6.6L",
      ad_spends_change: "+2.6%",
      roas: "4.6x",
      roas_change: "-0.5%",
    },
    flipkart: {
      offtake: "₹0.32 Cr",
      offtake_change: "+2.3%",
      category_share: "8%",
      category_share_change: "+0.8%",
      category_size: "₹1.1 Cr",
      category_size_change: "+3.1%",
      wt_osa: "90.1%",
      wt_osa_change: "+0.5%",
      wt_disc: "6.2%",
      wt_disc_change: "-0.2%",
      overall_sov: "21.1%",
      overall_sov_change: "+1.3%",
      impressions: "0.6 Cr",
      impressions_change: "+2.9%",
      clicks: "0.7 L",
      clicks_change: "+2.1%",
      ctr: "1.32%",
      ctr_change: "-0.1%",
      cvr: "3.6%",
      cvr_change: "+0.3%",
      orders: "3.0K",
      orders_change: "+1.1%",
      ad_spends: "₹5.9L",
      ad_spends_change: "+2.3%",
      roas: "4.5x",
      roas_change: "-0.4%",
    },
  },

  /* -------------------------------------------------- */
  /* --------------- SECOND PRODUCT --------------------*/
  /* -------------------------------------------------- */

  {
    name: "Colgate Sensitive Toothbrush (Ultra Soft) - 4 units",
    all: {
      offtake: "₹2.41 Cr",
      offtake_change: "-1.1%",
      category_share: "26%",
      category_share_change: "-0.5%",
      category_size: "₹9.3 Cr",
      category_size_change: "+3.2%",
      wt_osa: "89.2%",
      wt_osa_change: "+0.5%",
      wt_disc: "5.4%",
      wt_disc_change: "+0.1%",
      overall_sov: "23.1%",
      overall_sov_change: "-1.3%",
      impressions: "3.4 Cr",
      impressions_change: "-1.8%",
      clicks: "5.1 L",
      clicks_change: "-1.2%",
      ctr: "1.50%",
      ctr_change: "+0.2%",
      cvr: "4.2%",
      cvr_change: "-0.5%",
      orders: "20.2K",
      orders_change: "-0.8%",
      ad_spends: "₹32.7L",
      ad_spends_change: "-0.6%",
      roas: "4.4x",
      roas_change: "-0.7%",
    },
    blinkit: {
      offtake: "₹0.82 Cr",
      offtake_change: "-0.7%",
      category_share: "31%",
      category_share_change: "-0.4%",
      category_size: "₹2.7 Cr",
      category_size_change: "+2.8%",
      wt_osa: "88.7%",
      wt_osa_change: "+0.3%",
      wt_disc: "5.5%",
      wt_disc_change: "+0.2%",
      overall_sov: "22.4%",
      overall_sov_change: "-1.1%",
      impressions: "1.1 Cr",
      impressions_change: "-1.5%",
      clicks: "1.7 L",
      clicks_change: "-0.9%",
      ctr: "1.57%",
      ctr_change: "+0.2%",
      cvr: "4.1%",
      cvr_change: "-0.4%",
      orders: "6.8K",
      orders_change: "-0.6%",
      ad_spends: "₹10.8L",
      ad_spends_change: "-0.5%",
      roas: "4.5x",
      roas_change: "-0.6%",
    },
    zepto: {
      offtake: "₹0.61 Cr",
      offtake_change: "-1.0%",
      category_share: "26%",
      category_share_change: "-0.5%",
      category_size: "₹2.3 Cr",
      category_size_change: "+2.7%",
      wt_osa: "89.0%",
      wt_osa_change: "+0.4%",
      wt_disc: "5.3%",
      wt_disc_change: "+0.1%",
      overall_sov: "22.6%",
      overall_sov_change: "-1.2%",
      impressions: "0.9 Cr",
      impressions_change: "-1.4%",
      clicks: "1.4 L",
      clicks_change: "-0.8%",
      ctr: "1.55%",
      ctr_change: "+0.2%",
      cvr: "4.0%",
      cvr_change: "-0.4%",
      orders: "5.4K",
      orders_change: "-0.7%",
      ad_spends: "₹9.2L",
      ad_spends_change: "-0.7%",
      roas: "4.4x",
      roas_change: "-0.5%",
    },
    swiggy: {
      offtake: "₹0.50 Cr",
      offtake_change: "-0.9%",
      category_share: "21%",
      category_share_change: "-0.4%",
      category_size: "₹1.9 Cr",
      category_size_change: "+2.6%",
      wt_osa: "88.8%",
      wt_osa_change: "+0.3%",
      wt_disc: "5.4%",
      wt_disc_change: "+0.1%",
      overall_sov: "22.2%",
      overall_sov_change: "-1.0%",
      impressions: "0.8 Cr",
      impressions_change: "-1.3%",
      clicks: "1.1 L",
      clicks_change: "-0.7%",
      ctr: "1.53%",
      ctr_change: "+0.2%",
      cvr: "3.9%",
      cvr_change: "-0.3%",
      orders: "4.4K",
      orders_change: "-0.6%",
      ad_spends: "₹8.1L",
      ad_spends_change: "-0.6%",
      roas: "4.2x",
      roas_change: "-0.4%",
    },
    amazon: {
      offtake: "₹0.29 Cr",
      offtake_change: "-0.5%",
      category_share: "13%",
      category_share_change: "-0.3%",
      category_size: "₹1.3 Cr",
      category_size_change: "+2.6%",
      wt_osa: "88.1%",
      wt_osa_change: "+0.3%",
      wt_disc: "5.3%",
      wt_disc_change: "+0.1%",
      overall_sov: "21.7%",
      overall_sov_change: "-0.8%",
      impressions: "0.6 Cr",
      impressions_change: "-1.2%",
      clicks: "0.8 L",
      clicks_change: "-0.6%",
      ctr: "1.44%",
      ctr_change: "+0.1%",
      cvr: "3.8%",
      cvr_change: "-0.3%",
      orders: "3.2K",
      orders_change: "-0.5%",
      ad_spends: "₹6.5L",
      ad_spends_change: "-0.5%",
      roas: "4.1x",
      roas_change: "-0.3%",
    },
    flipkart: {
      offtake: "₹0.23 Cr",
      offtake_change: "-0.6%",
      category_share: "9%",
      category_share_change: "-0.2%",
      category_size: "₹1.1 Cr",
      category_size_change: "+2.5%",
      wt_osa: "87.9%",
      wt_osa_change: "+0.2%",
      wt_disc: "5.2%",
      wt_disc_change: "+0.1%",
      overall_sov: "21.0%",
      overall_sov_change: "-0.7%",
      impressions: "0.5 Cr",
      impressions_change: "-1.1%",
      clicks: "0.7 L",
      clicks_change: "-0.5%",
      ctr: "1.39%",
      ctr_change: "+0.1%",
      cvr: "3.7%",
      cvr_change: "-0.2%",
      orders: "2.6K",
      orders_change: "-0.4%",
      ad_spends: "₹5.4L",
      ad_spends_change: "-0.4%",
      roas: "4.0x",
      roas_change: "-0.3%",
    },
  },

  /* -------------------------------------------------- */
  /* --------------- THIRD PRODUCT ---------------------*/
  /* -------------------------------------------------- */

  {
    name: "Colgate Gentle Sensitive Soft Bristles Toothbrush - 1 piece",
    all: {
      offtake: "₹2.48 Cr",
      offtake_change: "+1.3%",
      category_share: "27%",
      category_share_change: "+0.6%",
      category_size: "₹9.4 Cr",
      category_size_change: "+3.4%",
      wt_osa: "90.2%",
      wt_osa_change: "+0.8%",
      wt_disc: "4.7%",
      wt_disc_change: "-0.3%",
      overall_sov: "26.1%",
      overall_sov_change: "+1.3%",
      impressions: "3.5 Cr",
      impressions_change: "+1.9%",
      clicks: "5.4 L",
      clicks_change: "+2.5%",
      ctr: "1.54%",
      ctr_change: "-0.1%",
      cvr: "3.9%",
      cvr_change: "+0.5%",
      orders: "21.4K",
      orders_change: "+1.7%",
      ad_spends: "₹34.2L",
      ad_spends_change: "+2.3%",
      roas: "4.8x",
      roas_change: "+0.8%",
    },
    blinkit: {
      offtake: "₹0.82 Cr",
      offtake_change: "+1.8%",
      category_share: "31%",
      category_share_change: "+0.9%",
      category_size: "₹2.6 Cr",
      category_size_change: "+3.0%",
      wt_osa: "89.7%",
      wt_osa_change: "+0.7%",
      wt_disc: "4.6%",
      wt_disc_change: "-0.3%",
      overall_sov: "25.4%",
      overall_sov_change: "+1.2%",
      impressions: "1.2 Cr",
      impressions_change: "+1.7%",
      clicks: "1.8 L",
      clicks_change: "+2.2%",
      ctr: "1.46%",
      ctr_change: "-0.1%",
      cvr: "3.9%",
      cvr_change: "+0.4%",
      orders: "6.9K",
      orders_change: "+1.5%",
      ad_spends: "₹10.6L",
      ad_spends_change: "+1.9%",
      roas: "4.8x",
      roas_change: "+0.7%",
    },
    zepto: {
      offtake: "₹0.61 Cr",
      offtake_change: "+1.1%",
      category_share: "26%",
      category_share_change: "+0.7%",
      category_size: "₹2.2 Cr",
      category_size_change: "+2.9%",
      wt_osa: "90.0%",
      wt_osa_change: "+0.6%",
      wt_disc: "4.7%",
      wt_disc_change: "-0.2%",
      overall_sov: "25.5%",
      overall_sov_change: "+1.1%",
      impressions: "1.0 Cr",
      impressions_change: "+1.6%",
      clicks: "1.4 L",
      clicks_change: "+2.0%",
      ctr: "1.45%",
      ctr_change: "-0.1%",
      cvr: "3.8%",
      cvr_change: "+0.3%",
      orders: "5.3K",
      orders_change: "+1.4%",
      ad_spends: "₹9.1L",
      ad_spends_change: "+1.7%",
      roas: "4.6x",
      roas_change: "+0.6%",
    },
    swiggy: {
      offtake: "₹0.55 Cr",
      offtake_change: "+1.0%",
      category_share: "22%",
      category_share_change: "+0.4%",
      category_size: "₹2.1 Cr",
      category_size_change: "+2.7%",
      wt_osa: "89.6%",
      wt_osa_change: "+0.6%",
      wt_disc: "4.8%",
      wt_disc_change: "-0.2%",
      overall_sov: "24.9%",
      overall_sov_change: "+1.0%",
      impressions: "0.9 Cr",
      impressions_change: "+1.5%",
      clicks: "1.2 L",
      clicks_change: "+1.9%",
      ctr: "1.43%",
      ctr_change: "-0.1%",
      cvr: "3.7%",
      cvr_change: "+0.3%",
      orders: "4.5K",
      orders_change: "+1.3%",
      ad_spends: "₹7.8L",
      ad_spends_change: "+1.6%",
      roas: "4.5x",
      roas_change: "+0.5%",
    },
    amazon: {
      offtake: "₹0.30 Cr",
      offtake_change: "+0.9%",
      category_share: "12%",
      category_share_change: "+0.3%",
      category_size: "₹1.3 Cr",
      category_size_change: "+2.6%",
      wt_osa: "89.0%",
      wt_osa_change: "+0.5%",
      wt_disc: "4.7%",
      wt_disc_change: "-0.2%",
      overall_sov: "24.2%",
      overall_sov_change: "+0.9%",
      impressions: "0.6 Cr",
      impressions_change: "+1.3%",
      clicks: "0.8 L",
      clicks_change: "+1.7%",
      ctr: "1.41%",
      ctr_change: "-0.1%",
      cvr: "3.6%",
      cvr_change: "+0.2%",
      orders: "3.0K",
      orders_change: "+1.1%",
      ad_spends: "₹6.4L",
      ad_spends_change: "+1.5%",
      roas: "4.4x",
      roas_change: "+0.5%",
    },
    flipkart: {
      offtake: "₹0.22 Cr",
      offtake_change: "+0.7%",
      category_share: "8%",
      category_share_change: "+0.2%",
      category_size: "₹1.1 Cr",
      category_size_change: "+2.5%",
      wt_osa: "88.7%",
      wt_osa_change: "+0.4%",
      wt_disc: "4.8%",
      wt_disc_change: "-0.1%",
      overall_sov: "23.6%",
      overall_sov_change: "+0.8%",
      impressions: "0.5 Cr",
      impressions_change: "+1.2%",
      clicks: "0.6 L",
      clicks_change: "+1.6%",
      ctr: "1.39%",
      ctr_change: "-0.1%",
      cvr: "3.5%",
      cvr_change: "+0.2%",
      orders: "2.3K",
      orders_change: "+0.9%",
      ad_spends: "₹5.3L",
      ad_spends_change: "+1.4%",
      roas: "4.3x",
      roas_change: "+0.4%",
    },
  },

  /* -------------------------------------------------- */
  /* --------------- FOURTH PRODUCT --------------------*/
  /* -------------------------------------------------- */

  {
    name: "Colgate Gentle Sensitive Soft Bristles Toothbrush - 67 piece",
    all: {
      offtake: "₹1.48 Cr",
      offtake_change: "-0.5%",
      category_share: "16%",
      category_share_change: "-0.4%",
      category_size: "₹9.1 Cr",
      category_size_change: "+2.9%",
      wt_osa: "89.3%",
      wt_osa_change: "-0.3%",
      wt_disc: "5.4%",
      wt_disc_change: "+0.2%",
      overall_sov: "19.1%",
      overall_sov_change: "-0.4%",
      impressions: "2.4 Cr",
      impressions_change: "-0.9%",
      clicks: "3.4 L",
      clicks_change: "-1.0%",
      ctr: "1.40%",
      ctr_change: "-0.1%",
      cvr: "3.5%",
      cvr_change: "-0.2%",
      orders: "11.2K",
      orders_change: "-0.7%",
      ad_spends: "₹23.9L",
      ad_spends_change: "-0.5%",
      roas: "4.2x",
      roas_change: "-0.4%",
    },
    blinkit: {
      offtake: "₹0.53 Cr",
      offtake_change: "-0.4%",
      category_share: "36%",
      category_share_change: "-0.3%",
      category_size: "₹2.0 Cr",
      category_size_change: "+2.6%",
      wt_osa: "89.0%",
      wt_osa_change: "-0.2%",
      wt_disc: "5.5%",
      wt_disc_change: "+0.2%",
      overall_sov: "18.9%",
      overall_sov_change: "-0.4%",
      impressions: "0.8 Cr",
      impressions_change: "-0.8%",
      clicks: "1.2 L",
      clicks_change: "-1.0%",
      ctr: "1.41%",
      ctr_change: "-0.1%",
      cvr: "3.6%",
      cvr_change: "-0.1%",
      orders: "4.1K",
      orders_change: "-0.6%",
      ad_spends: "₹7.9L",
      ad_spends_change: "-0.6%",
      roas: "4.3x",
      roas_change: "-0.4%",
    },
    zepto: {
      offtake: "₹0.38 Cr",
      offtake_change: "-0.6%",
      category_share: "26%",
      category_share_change: "-0.4%",
      category_size: "₹1.6 Cr",
      category_size_change: "+2.4%",
      wt_osa: "89.1%",
      wt_osa_change: "-0.2%",
      wt_disc: "5.4%",
      wt_disc_change: "+0.2%",
      overall_sov: "19.0%",
      overall_sov_change: "-0.4%",
      impressions: "0.6 Cr",
      impressions_change: "-0.9%",
      clicks: "0.8 L",
      clicks_change: "-1.1%",
      ctr: "1.40%",
      ctr_change: "-0.1%",
      cvr: "3.5%",
      cvr_change: "-0.2%",
      orders: "3.2K",
      orders_change: "-0.7%",
      ad_spends: "₹6.5L",
      ad_spends_change: "-0.6%",
      roas: "4.2x",
      roas_change: "-0.4%",
    },
    swiggy: {
      offtake: "₹0.30 Cr",
      offtake_change: "-0.7%",
      category_share: "21%",
      category_share_change: "-0.5%",
      category_size: "₹1.4 Cr",
      category_size_change: "+2.3%",
      wt_osa: "88.9%",
      wt_osa_change: "-0.3%",
      wt_disc: "5.3%",
      wt_disc_change: "+0.1%",
      overall_sov: "19.1%",
      overall_sov_change: "-0.3%",
      impressions: "0.5 Cr",
      impressions_change: "-1.0%",
      clicks: "0.7 L",
      clicks_change: "-1.2%",
      ctr: "1.38%",
      ctr_change: "-0.1%",
      cvr: "3.4%",
      cvr_change: "-0.2%",
      orders: "2.6K",
      orders_change: "-0.7%",
      ad_spends: "₹5.6L",
      ad_spends_change: "-0.5%",
      roas: "4.1x",
      roas_change: "-0.3%",
    },
    amazon: {
      offtake: "₹0.18 Cr",
      offtake_change: "-0.8%",
      category_share: "12%",
      category_share_change: "-0.5%",
      category_size: "₹1.2 Cr",
      category_size_change: "+2.2%",
      wt_osa: "88.7%",
      wt_osa_change: "-0.3%",
      wt_disc: "5.2%",
      wt_disc_change: "+0.2%",
      overall_sov: "19.2%",
      overall_sov_change: "-0.3%",
      impressions: "0.3 Cr",
      impressions_change: "-0.9%",
      clicks: "0.5 L",
      clicks_change: "-1.0%",
      ctr: "1.37%",
      ctr_change: "-0.1%",
      cvr: "3.3%",
      cvr_change: "-0.2%",
      orders: "1.8K",
      orders_change: "-0.6%",
      ad_spends: "₹4.7L",
      ad_spends_change: "-0.5%",
      roas: "4.0x",
      roas_change: "-0.3%",
    },
    flipkart: {
      offtake: "₹0.12 Cr",
      offtake_change: "-0.9%",
      category_share: "9%",
      category_share_change: "-0.3%",
      category_size: "₹1.0 Cr",
      category_size_change: "+2.2%",
      wt_osa: "88.6%",
      wt_osa_change: "-0.4%",
      wt_disc: "5.1%",
      wt_disc_change: "+0.2%",
      overall_sov: "19.3%",
      overall_sov_change: "-0.3%",
      impressions: "0.2 Cr",
      impressions_change: "-0.8%",
      clicks: "0.3 L",
      clicks_change: "-0.9%",
      ctr: "1.36%",
      ctr_change: "-0.1%",
      cvr: "3.2%",
      cvr_change: "-0.2%",
      orders: "1.2K",
      orders_change: "-0.6%",
      ad_spends: "₹4.0L",
      ad_spends_change: "-0.4%",
      roas: "3.9x",
      roas_change: "-0.2%",
    },
  },
];
