const monthLogos = {
  jan: "https://img.icons8.com/fluency/96/january.png",
  feb: "https://img.icons8.com/fluency/96/february.png",
  mar: "https://img.icons8.com/fluency/96/march.png",
  apr: "https://img.icons8.com/fluency/96/april.png",
  may: "https://img.icons8.com/fluency/96/may.png",
  jun: "https://img.icons8.com/fluency/96/june.png",
  jul: "https://img.icons8.com/fluency/96/july.png",
  aug: "https://img.icons8.com/fluency/96/august.png",
  sep: "https://img.icons8.com/fluency/96/september.png",
  oct: "https://img.icons8.com/fluency/96/october.png",
  nov: "https://img.icons8.com/fluency/96/november.png",
  dec: "https://img.icons8.com/fluency/96/december.png",
};
const categoryLogo = "https://cdn-icons-png.flaticon.com/512/711/711284.png";

export const defaultPlatforms = [
  // ---------------- ALL ----------------
  {
    key: "all",
    label: "All",
    type: "Overall",
    logo: "https://cdn-icons-png.flaticon.com/512/711/711284.png",
    columns: [
      {
        title: "Offtakes",
        value: "₹11.8 Cr",
        change: { text: "▲3.4% (+₹38.9 lac)", positive: true },
        meta: { units: "5.7 lac units", change: "▲2.1%" },
      },
      {
        title: "Spend",
        value: "₹1.32 Cr",
        change: { text: "▲2.2% (+₹2.8 lac)", positive: true },
        meta: { units: "₹1.32 Cr", change: "▲2.2%" },
      },
      {
        title: "ROAS",
        value: "8.9x",
        change: { text: "▲0.4% (+0.03x)", positive: true },
        meta: { units: "₹10.9 Cr return", change: "▲0.4%" },
      },
      {
        title: "Inorg Sales",
        value: "₹2.42 Cr",
        change: { text: "▲1.9% (+₹4.5 lac)", positive: true },
        meta: { units: "1.54 lac units", change: "▲1.9%" },
      },
      {
        title: "Conversion",
        value: "4.6%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "1.21 lac conversions", change: "▲0.2 pp" },
      },
      {
        title: "Availability",
        value: "96.2%",
        change: { text: "▲0.6 pp", positive: true },
        meta: { units: "10,780 stores", change: "▲0.6 pp" },
      },
      {
        title: "SOS",
        value: "34.8%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "Shelf share index 34.8", change: "▲0.3 pp" },
      },
      {
        title: "Market Share",
        value: "36.4%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "Category: ₹32.4 Cr", change: "▲0.4 pp" },
      },
      {
        title: "Promo My Brand",
        value: "21.1%",
        change: { text: "▲0.6 pp", positive: true },
        meta: { units: "Avg depth 21.1%", change: "▲0.6 pp" },
      },
      {
        title: "Promo Compete",
        value: "28.9%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "Avg depth 28.9%", change: "▲0.4 pp" },
      },
      {
        title: "CPM",
        value: "₹128",
        change: { text: "▲1.7% (+₹2.1)", positive: true },
        meta: { units: "1.62 Cr impressions", change: "▲1.7%" },
      },
      {
        title: "CPC",
        value: "₹7.8",
        change: { text: "▲1.3% (+₹0.10)", positive: true },
        meta: { units: "10.8 lac clicks", change: "▲1.3%" },
      },
    ],
  },

  // ---------------- BLINKIT ----------------
  {
    key: "blinkit",
    label: "Blinkit",
    type: "Q-commerce",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/Blinkit-yellow-rounded.svg",
    columns: [
      {
        title: "Offtakes",
        value: "₹2.46 Cr",
        change: { text: "▲3.2% (+₹7.6 lac)", positive: true },
        meta: { units: "1.24 lac units", change: "▲1.8%" },
      },
      {
        title: "Spend",
        value: "₹0.34 Cr",
        change: { text: "▲1.6% (+₹0.5 lac)", positive: true },
        meta: { units: "₹34 lac", change: "▲1.6%" },
      },
      {
        title: "ROAS",
        value: "7.2x",
        change: { text: "▲0.3% (+0.02x)", positive: true },
        meta: { units: "₹2.44 Cr return", change: "▲0.3%" },
      },
      {
        title: "Inorg Sales",
        value: "₹0.48 Cr",
        change: { text: "▲2.1% (+₹1.0 lac)", positive: true },
        meta: { units: "0.33 lac units", change: "▲2.1%" },
      },
      {
        title: "Conversion",
        value: "3.9%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "34.1k conversions", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "92.4%",
        change: { text: "▼1.4 pp", positive: false },
        meta: { units: "1,920 stores", change: "▼1.4 pp" },
      },
      {
        title: "SOS",
        value: "32.1%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "Shelf index 32.1", change: "▲0.2 pp" },
      },
      {
        title: "Market Share",
        value: "38.8%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "Category: ₹6.33 Cr", change: "▲0.3 pp" },
      },
      {
        title: "Promo My Brand",
        value: "23.6%",
        change: { text: "▲0.8 pp", positive: true },
        meta: { units: "Depth 23.6%", change: "▲0.8 pp" },
      },
      {
        title: "Promo Compete",
        value: "31.2%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "Depth 31.2%", change: "▲0.5 pp" },
      },
      {
        title: "CPM",
        value: "₹142",
        change: { text: "▲2.1% (+₹2.9)", positive: true },
        meta: { units: "43.1 lac impressions", change: "▲2.1%" },
      },
      {
        title: "CPC",
        value: "₹8.4",
        change: { text: "▲1.5% (+₹0.12)", positive: true },
        meta: { units: "3.9 lac clicks", change: "▲1.5%" },
      },
    ],
  },

  // ---------------- ZEPTO ----------------
  {
    key: "zepto",
    label: "Zepto",
    type: "Q-commerce",
    logo: "https://upload.wikimedia.org/wikipedia/en/7/7d/Logo_of_Zepto.png",
    columns: [
      {
        title: "Offtakes",
        value: "₹1.88 Cr",
        change: { text: "▲3.4% (+₹6.1 lac)", positive: true },
        meta: { units: "0.98 lac units", change: "▲1.9%" },
      },
      {
        title: "Spend",
        value: "₹0.28 Cr",
        change: { text: "▲1.4% (+₹0.4 lac)", positive: true },
        meta: { units: "₹28 lac", change: "▲1.4%" },
      },
      {
        title: "ROAS",
        value: "6.8x",
        change: { text: "▲0.4% (+0.03x)", positive: true },
        meta: { units: "₹1.90 Cr return", change: "▲0.4%" },
      },
      {
        title: "Inorg Sales",
        value: "₹0.36 Cr",
        change: { text: "▲1.7% (+₹0.6 lac)", positive: true },
        meta: { units: "0.27 lac units", change: "▲1.7%" },
      },
      {
        title: "Conversion",
        value: "4.1%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "28.8k conversions", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "94.7%",
        change: { text: "▼0.9 pp", positive: false },
        meta: { units: "1,570 stores", change: "▼0.9 pp" },
      },
      {
        title: "SOS",
        value: "33.8%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "Shelf index 33.8", change: "▲0.3 pp" },
      },
      {
        title: "Market Share",
        value: "36.9%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "Category: ₹5.08 Cr", change: "▲0.3 pp" },
      },
      {
        title: "Promo My Brand",
        value: "22.8%",
        change: { text: "▲0.7 pp", positive: true },
        meta: { units: "Depth 22.8%", change: "▲0.7 pp" },
      },
      {
        title: "Promo Compete",
        value: "30.4%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "Depth 30.4%", change: "▲0.4 pp" },
      },
      {
        title: "CPM",
        value: "₹138",
        change: { text: "▲1.9% (+₹2.6)", positive: true },
        meta: { units: "38.0 lac impressions", change: "▲1.9%" },
      },
      {
        title: "CPC",
        value: "₹8.1",
        change: { text: "▲1.2% (+₹0.10)", positive: true },
        meta: { units: "3.2 lac clicks", change: "▲1.2%" },
      },
    ],
  },

  // ---------------- SWIGGY ----------------
  {
    key: "swiggy",
    label: "Swiggy",
    type: "Marketplace",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Swiggy_Logo_2024.webp",
    columns: [
      {
        title: "Offtakes",
        value: "₹1.42 Cr",
        change: { text: "▲2.4% (+₹3.3 lac)", positive: true },
        meta: { units: "0.74 lac units", change: "▲1.2%" },
      },
      {
        title: "Spend",
        value: "₹0.22 Cr",
        change: { text: "▲1.3% (+₹0.3 lac)", positive: true },
        meta: { units: "₹22 lac", change: "▲1.3%" },
      },
      {
        title: "ROAS",
        value: "6.2x",
        change: { text: "▲0.3% (+0.02x)", positive: true },
        meta: { units: "₹1.36 Cr return", change: "▲0.3%" },
      },
      {
        title: "Inorg Sales",
        value: "₹0.29 Cr",
        change: { text: "▲1.5% (+₹0.4 lac)", positive: true },
        meta: { units: "0.21 lac units", change: "▲1.5%" },
      },
      {
        title: "Conversion",
        value: "3.3%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "19.3k conversions", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "97.2%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "2,710 stores", change: "▲0.4 pp" },
      },
      {
        title: "SOS",
        value: "31.4%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "Shelf index 31.4", change: "▲0.2 pp" },
      },
      {
        title: "Market Share",
        value: "30.9%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "Category: ₹4.63 Cr", change: "▲0.2 pp" },
      },
      {
        title: "Promo My Brand",
        value: "18.2%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "Depth 18.2%", change: "▲0.4 pp" },
      },
      {
        title: "Promo Compete",
        value: "25.8%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "Depth 25.8%", change: "▲0.3 pp" },
      },
      {
        title: "CPM",
        value: "₹110",
        change: { text: "▲1.5% (+₹1.6)", positive: true },
        meta: { units: "26.9 lac impressions", change: "▲1.5%" },
      },
      {
        title: "CPC",
        value: "₹6.2",
        change: { text: "▲1.1% (+₹0.07)", positive: true },
        meta: { units: "2.1 lac clicks", change: "▲1.1%" },
      },
    ],
  },

  // ---------------- AMAZON ----------------
  {
    key: "amazon",
    label: "Amazon",
    type: "Marketplace",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
    columns: [
      {
        title: "Offtakes",
        value: "₹2.68 Cr",
        change: { text: "▲2.8% (+₹7.3 lac)", positive: true },
        meta: { units: "1.38 lac units", change: "▲1.9%" },
      },
      {
        title: "Spend",
        value: "₹0.41 Cr",
        change: { text: "▲1.4% (+₹0.6 lac)", positive: true },
        meta: { units: "₹41 lac", change: "▲1.4%" },
      },
      {
        title: "ROAS",
        value: "7.9x",
        change: { text: "▲0.5% (+0.04x)", positive: true },
        meta: { units: "₹3.24 Cr return", change: "▲0.5%" },
      },
      {
        title: "Inorg Sales",
        value: "₹0.58 Cr",
        change: { text: "▲1.8% (+₹1.0 lac)", positive: true },
        meta: { units: "0.41 lac units", change: "▲1.8%" },
      },
      {
        title: "Conversion",
        value: "4.4%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "41.3k conversions", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "93.8%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "4,520 stores", change: "▲0.5 pp" },
      },
      {
        title: "SOS",
        value: "33.0%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "Shelf index 33.0", change: "▲0.2 pp" },
      },
      {
        title: "Market Share",
        value: "34.7%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "Category: ₹7.72 Cr", change: "▲0.3 pp" },
      },
      {
        title: "Promo My Brand",
        value: "20.1%",
        change: { text: "▲0.6 pp", positive: true },
        meta: { units: "Depth 20.1%", change: "▲0.6 pp" },
      },
      {
        title: "Promo Compete",
        value: "27.0%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "Depth 27.0%", change: "▲0.4 pp" },
      },
      {
        title: "CPM",
        value: "₹134",
        change: { text: "▲1.7% (+₹2.3)", positive: true },
        meta: { units: "49.5 lac impressions", change: "▲1.7%" },
      },
      {
        title: "CPC",
        value: "₹7.4",
        change: { text: "▲1.2% (+₹0.09)", positive: true },
        meta: { units: "4.7 lac clicks", change: "▲1.2%" },
      },
    ],
  },
];

export const defaultMonths = [
  /* -------------------- JAN -------------------- */
  {
    key: "jan",
    label: "Jan",
    logo: monthLogos["jan"],
    columns: [
      {
        title: "Offtakes",
        value: "₹7.2 Cr",
        change: { text: "▲1.1% (+₹7.8 lac)", positive: true },
        meta: { units: "3.5 lac", change: "▲0.6%" },
      },
      {
        title: "Spend",
        value: "₹0.82 Cr",
        change: { text: "▲0.9% (+₹0.7 lac)", positive: true },
        meta: { units: "—", change: "▲0.9%" },
      },
      {
        title: "ROAS",
        value: "7.1x",
        change: { text: "▲0.5% (+0.03x)", positive: true },
        meta: { units: "—", change: "▲0.5%" },
      },
      {
        title: "Inorg Sales",
        value: "₹1.62 Cr",
        change: { text: "▲0.7% (+₹1.1 lac)", positive: true },
        meta: { units: "1.1 lac", change: "▲0.4%" },
      },
      {
        title: "Conversion",
        value: "3.7%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "—", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "94.8%",
        change: { text: "▼0.6 pp", positive: false },
        meta: { units: "—", change: "▼0.6 pp" },
      },
      {
        title: "SOS",
        value: "33.4%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "—", change: "▲0.1 pp" },
      },
      {
        title: "Market Share",
        value: "31.6%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "—", change: "▲0.2 pp" },
      },
      {
        title: "Promo My Brand",
        value: "18.9%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "Promo Compete",
        value: "27.2%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "—", change: "▲0.4 pp" },
      },
      {
        title: "CPM",
        value: "₹115",
        change: { text: "▲1.2% (+₹1.4)", positive: true },
        meta: { units: "—", change: "▲1.2%" },
      },
      {
        title: "CPC",
        value: "₹6.6",
        change: { text: "▲1.1% (+₹0.07)", positive: true },
        meta: { units: "—", change: "▲1.1%" },
      },
    ],
  },

  /* -------------------- FEB -------------------- */
  {
    key: "feb",
    label: "Feb",
    logo: monthLogos["feb"],
    columns: [
      {
        title: "Offtakes",
        value: "₹7.9 Cr",
        change: { text: "▲1.6% (+₹12.5 lac)", positive: true },
        meta: { units: "3.8 lac", change: "▲0.8%" },
      },
      {
        title: "Spend",
        value: "₹0.87 Cr",
        change: { text: "▲1.1% (+₹1.0 lac)", positive: true },
        meta: { units: "—", change: "▲1.1%" },
      },
      {
        title: "ROAS",
        value: "7.3x",
        change: { text: "▲0.6% (+0.04x)", positive: true },
        meta: { units: "—", change: "▲0.6%" },
      },
      {
        title: "Inorg Sales",
        value: "₹1.78 Cr",
        change: { text: "▲1.0% (+₹1.7 lac)", positive: true },
        meta: { units: "1.15 lac", change: "▲0.8%" },
      },
      {
        title: "Conversion",
        value: "3.9%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "—", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "95.3%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "—", change: "▲0.5 pp" },
      },
      {
        title: "SOS",
        value: "34.1%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "—", change: "▲0.2 pp" },
      },
      {
        title: "Market Share",
        value: "32.4%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "Promo My Brand",
        value: "19.3%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "—", change: "▲0.4 pp" },
      },
      {
        title: "Promo Compete",
        value: "27.4%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "—", change: "▲0.2 pp" },
      },
      {
        title: "CPM",
        value: "₹118",
        change: { text: "▲1.4% (+₹1.6)", positive: true },
        meta: { units: "—", change: "▲1.4%" },
      },
      {
        title: "CPC",
        value: "₹6.7",
        change: { text: "▲1.3% (+₹0.08)", positive: true },
        meta: { units: "—", change: "▲1.3%" },
      },
    ],
  },

  /* -------------------- MAR -------------------- */
  {
    key: "mar",
    label: "Mar",
    logo: monthLogos["mar"],
    columns: [
      {
        title: "Offtakes",
        value: "₹8.6 Cr",
        change: { text: "▲2.1% (+₹17.8 lac)", positive: true },
        meta: { units: "4.1 lac", change: "▲1.1%" },
      },
      {
        title: "Spend",
        value: "₹0.91 Cr",
        change: { text: "▲1.3% (+₹1.2 lac)", positive: true },
        meta: { units: "—", change: "▲1.3%" },
      },
      {
        title: "ROAS",
        value: "7.5x",
        change: { text: "▲0.9% (+0.07x)", positive: true },
        meta: { units: "—", change: "▲0.9%" },
      },
      {
        title: "Inorg Sales",
        value: "₹1.92 Cr",
        change: { text: "▲1.2% (+₹2.2 lac)", positive: true },
        meta: { units: "1.24 lac", change: "▲0.9%" },
      },
      {
        title: "Conversion",
        value: "4.0%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "—", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "95.8%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "—", change: "▲0.5 pp" },
      },
      {
        title: "SOS",
        value: "35.0%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "Market Share",
        value: "33.2%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "—", change: "▲0.4 pp" },
      },
      {
        title: "Promo My Brand",
        value: "19.9%",
        change: { text: "▲0.6 pp", positive: true },
        meta: { units: "—", change: "▲0.6 pp" },
      },
      {
        title: "Promo Compete",
        value: "27.8%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "—", change: "▲0.4 pp" },
      },
      {
        title: "CPM",
        value: "₹122",
        change: { text: "▲1.8% (+₹2.1)", positive: true },
        meta: { units: "—", change: "▲1.8%" },
      },
      {
        title: "CPC",
        value: "₹6.9",
        change: { text: "▲1.4% (+₹0.09)", positive: true },
        meta: { units: "—", change: "▲1.4%" },
      },
    ],
  },

  /* -------------------- APR -------------------- */
  {
    key: "apr",
    label: "Apr",
    logo: monthLogos["apr"],
    columns: [
      {
        title: "Offtakes",
        value: "₹9.3 Cr",
        change: { text: "▲2.6% (+₹23.5 lac)", positive: true },
        meta: { units: "4.5 lac", change: "▲1.3%" },
      },
      {
        title: "Spend",
        value: "₹0.96 Cr",
        change: { text: "▲1.4% (+₹1.3 lac)", positive: true },
        meta: { units: "—", change: "▲1.4%" },
      },
      {
        title: "ROAS",
        value: "7.7x",
        change: { text: "▲1.1% (+0.08x)", positive: true },
        meta: { units: "—", change: "▲1.1%" },
      },
      {
        title: "Inorg Sales",
        value: "₹2.05 Cr",
        change: { text: "▲1.4% (+₹2.8 lac)", positive: true },
        meta: { units: "1.32 lac", change: "▲1.0%" },
      },
      {
        title: "Conversion",
        value: "4.2%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "—", change: "▲0.2 pp" },
      },
      {
        title: "Availability",
        value: "96.3%",
        change: { text: "▲0.7 pp", positive: true },
        meta: { units: "—", change: "▲0.7 pp" },
      },
      {
        title: "SOS",
        value: "35.8%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "—", change: "▲0.4 pp" },
      },
      {
        title: "Market Share",
        value: "34.0%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "—", change: "▲0.4 pp" },
      },
      {
        title: "Promo My Brand",
        value: "20.3%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "—", change: "▲0.4 pp" },
      },
      {
        title: "Promo Compete",
        value: "28.1%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "CPM",
        value: "₹125",
        change: { text: "▲1.9% (+₹2.3)", positive: true },
        meta: { units: "—", change: "▲1.9%" },
      },
      {
        title: "CPC",
        value: "₹7.1",
        change: { text: "▲1.7% (+₹0.12)", positive: true },
        meta: { units: "—", change: "▲1.7%" },
      },
    ],
  },

  /* -------------------- MAY -------------------- */
  {
    key: "may",
    label: "May",
    logo: monthLogos["may"],
    columns: [
      {
        title: "Offtakes",
        value: "₹10.0 Cr",
        change: { text: "▲3.3% (+₹32.1 lac)", positive: true },
        meta: { units: "4.9 lac", change: "▲1.8%" },
      },
      {
        title: "Spend",
        value: "₹1.02 Cr",
        change: { text: "▲1.9% (+₹1.9 lac)", positive: true },
        meta: { units: "—", change: "▲1.9%" },
      },
      {
        title: "ROAS",
        value: "7.9x",
        change: { text: "▲1.2% (+0.09x)", positive: true },
        meta: { units: "—", change: "▲1.2%" },
      },
      {
        title: "Inorg Sales",
        value: "₹2.21 Cr",
        change: { text: "▲1.6% (+₹3.4 lac)", positive: true },
        meta: { units: "1.41 lac", change: "▲1.2%" },
      },
      {
        title: "Conversion",
        value: "4.3%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "—", change: "▲0.2 pp" },
      },
      {
        title: "Availability",
        value: "96.7%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "—", change: "▲0.4 pp" },
      },
      {
        title: "SOS",
        value: "36.6%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "—", change: "▲0.4 pp" },
      },
      {
        title: "Market Share",
        value: "34.9%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "—", change: "▲0.5 pp" },
      },
      {
        title: "Promo My Brand",
        value: "20.8%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "—", change: "▲0.5 pp" },
      },
      {
        title: "Promo Compete",
        value: "28.4%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "CPM",
        value: "₹129",
        change: { text: "▲2.2% (+₹2.8)", positive: true },
        meta: { units: "—", change: "▲2.2%" },
      },
      {
        title: "CPC",
        value: "₹7.3",
        change: { text: "▲1.8% (+₹0.13)", positive: true },
        meta: { units: "—", change: "▲1.8%" },
      },
    ],
  },

  /* -------------------- JUN -------------------- */
  {
    key: "jun",
    label: "Jun",
    logo: monthLogos["jun"],
    columns: [
      {
        title: "Offtakes",
        value: "₹10.7 Cr",
        change: { text: "▲2.9% (+₹30.4 lac)", positive: true },
        meta: { units: "5.2 lac", change: "▲1.3%" },
      },
      {
        title: "Spend",
        value: "₹1.08 Cr",
        change: { text: "▲2.1% (+₹2.2 lac)", positive: true },
        meta: { units: "—", change: "▲2.1%" },
      },
      {
        title: "ROAS",
        value: "8.1x",
        change: { text: "▲1.3% (+0.10x)", positive: true },
        meta: { units: "—", change: "▲1.3%" },
      },
      {
        title: "Inorg Sales",
        value: "₹2.34 Cr",
        change: { text: "▲1.6% (+₹3.6 lac)", positive: true },
        meta: { units: "1.51 lac", change: "▲1.1%" },
      },
      {
        title: "Conversion",
        value: "4.4%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "—", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "96.8%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "—", change: "▲0.1 pp" },
      },
      {
        title: "SOS",
        value: "37.1%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "Market Share",
        value: "35.4%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "—", change: "▲0.5 pp" },
      },
      {
        title: "Promo My Brand",
        value: "21.0%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "—", change: "▲0.2 pp" },
      },
      {
        title: "Promo Compete",
        value: "28.7%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "CPM",
        value: "₹133",
        change: { text: "▲3.1% (+₹4.0)", positive: true },
        meta: { units: "—", change: "▲3.1%" },
      },
      {
        title: "CPC",
        value: "₹7.4",
        change: { text: "▲1.9% (+₹0.14)", positive: true },
        meta: { units: "—", change: "▲1.9%" },
      },
    ],
  },

  /* -------------------- JUL -------------------- */
  {
    key: "jul",
    label: "Jul",
    logo: monthLogos["jul"],
    columns: [
      {
        title: "Offtakes",
        value: "₹11.2 Cr",
        change: { text: "▲2.4% (+₹26.5 lac)", positive: true },
        meta: { units: "5.4 lac", change: "▲1.1%" },
      },
      {
        title: "Spend",
        value: "₹1.12 Cr",
        change: { text: "▲1.9% (+₹2.1 lac)", positive: true },
        meta: { units: "—", change: "▲1.9%" },
      },
      {
        title: "ROAS",
        value: "8.2x",
        change: { text: "▲1.2% (+0.09x)", positive: true },
        meta: { units: "—", change: "▲1.2%" },
      },
      {
        title: "Inorg Sales",
        value: "₹2.41 Cr",
        change: { text: "▲1.3% (+₹3.2 lac)", positive: true },
        meta: { units: "1.56 lac", change: "▲1.0%" },
      },
      {
        title: "Conversion",
        value: "4.5%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "—", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "97.0%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "—", change: "▲0.2 pp" },
      },
      {
        title: "SOS",
        value: "37.6%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "—", change: "▲0.5 pp" },
      },
      {
        title: "Market Share",
        value: "36.0%",
        change: { text: "▲0.6 pp", positive: true },
        meta: { units: "—", change: "▲0.6 pp" },
      },
      {
        title: "Promo My Brand",
        value: "21.3%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "Promo Compete",
        value: "29.1%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "—", change: "▲0.4 pp" },
      },
      {
        title: "CPM",
        value: "₹137",
        change: { text: "▲3.0% (+₹4.0)", positive: true },
        meta: { units: "—", change: "▲3.0%" },
      },
      {
        title: "CPC",
        value: "₹7.6",
        change: { text: "▲2.1% (+₹0.16)", positive: true },
        meta: { units: "—", change: "▲2.1%" },
      },
    ],
  },

  /* -------------------- AUG -------------------- */
  {
    key: "aug",
    label: "Aug",
    logo: monthLogos["aug"],
    columns: [
      {
        title: "Offtakes",
        value: "₹11.6 Cr",
        change: { text: "▲2.9% (+₹33.1 lac)", positive: true },
        meta: { units: "5.6 lac", change: "▲1.5%" },
      },
      {
        title: "Spend",
        value: "₹1.18 Cr",
        change: { text: "▲2.3% (+₹2.7 lac)", positive: true },
        meta: { units: "—", change: "▲2.3%" },
      },
      {
        title: "ROAS",
        value: "8.3x",
        change: { text: "▲1.4% (+0.12x)", positive: true },
        meta: { units: "—", change: "▲1.4%" },
      },
      {
        title: "Inorg Sales",
        value: "₹2.52 Cr",
        change: { text: "▲1.6% (+₹4.0 lac)", positive: true },
        meta: { units: "1.64 lac", change: "▲1.2%" },
      },
      {
        title: "Conversion",
        value: "4.7%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "—", change: "▲0.2 pp" },
      },
      {
        title: "Availability",
        value: "97.3%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "SOS",
        value: "38.2%",
        change: { text: "▲0.6 pp", positive: true },
        meta: { units: "—", change: "▲0.6 pp" },
      },
      {
        title: "Market Share",
        value: "36.7%",
        change: { text: "▲0.7 pp", positive: true },
        meta: { units: "—", change: "▲0.7 pp" },
      },
      {
        title: "Promo My Brand",
        value: "21.6%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "Promo Compete",
        value: "29.4%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "CPM",
        value: "₹139",
        change: { text: "▲1.8% (+₹2.4)", positive: true },
        meta: { units: "—", change: "▲1.8%" },
      },
      {
        title: "CPC",
        value: "₹7.7",
        change: { text: "▲1.9% (+₹0.15)", positive: true },
        meta: { units: "—", change: "▲1.9%" },
      },
    ],
  },

  /* -------------------- SEP -------------------- */
  {
    key: "sep",
    label: "Sep",
    logo: monthLogos["sep"],
    columns: [
      {
        title: "Offtakes",
        value: "₹11.3 Cr",
        change: { text: "▼1.4% (-₹15.8 lac)", positive: false },
        meta: { units: "5.4 lac", change: "▼1.1%" },
      },
      {
        title: "Spend",
        value: "₹1.14 Cr",
        change: { text: "▼1.2% (-₹1.4 lac)", positive: false },
        meta: { units: "—", change: "▼1.2%" },
      },
      {
        title: "ROAS",
        value: "8.0x",
        change: { text: "▼1.0% (-0.08x)", positive: false },
        meta: { units: "—", change: "▼1.0%" },
      },
      {
        title: "Inorg Sales",
        value: "₹2.44 Cr",
        change: { text: "▼1.3% (-₹3.2 lac)", positive: false },
        meta: { units: "1.58 lac", change: "▼1.1%" },
      },
      {
        title: "Conversion",
        value: "4.5%",
        change: { text: "▼0.2 pp", positive: false },
        meta: { units: "—", change: "▼0.2 pp" },
      },
      {
        title: "Availability",
        value: "96.9%",
        change: { text: "▼0.4 pp", positive: false },
        meta: { units: "—", change: "▼0.4 pp" },
      },
      {
        title: "SOS",
        value: "37.4%",
        change: { text: "▼0.4 pp", positive: false },
        meta: { units: "—", change: "▼0.4 pp" },
      },
      {
        title: "Market Share",
        value: "36.1%",
        change: { text: "▼0.6 pp", positive: false },
        meta: { units: "—", change: "▼0.6 pp" },
      },
      {
        title: "Promo My Brand",
        value: "21.1%",
        change: { text: "▼0.5 pp", positive: false },
        meta: { units: "—", change: "▼0.5 pp" },
      },
      {
        title: "Promo Compete",
        value: "28.9%",
        change: { text: "▼0.5 pp", positive: false },
        meta: { units: "—", change: "▼0.5 pp" },
      },
      {
        title: "CPM",
        value: "₹138",
        change: { text: "▼0.5% (-₹0.7)", positive: false },
        meta: { units: "—", change: "▼0.5%" },
      },
      {
        title: "CPC",
        value: "₹7.6",
        change: { text: "▼0.9% (-₹0.07)", positive: false },
        meta: { units: "—", change: "▼0.9%" },
      },
    ],
  },

  /* -------------------- OCT -------------------- */
  {
    key: "oct",
    label: "Oct",
    logo: monthLogos["oct"],
    columns: [
      {
        title: "Offtakes",
        value: "₹12.4 Cr",
        change: { text: "▲3.8% (+₹45.2 lac)", positive: true },
        meta: { units: "6.0 lac", change: "▲2.3%" },
      },
      {
        title: "Spend",
        value: "₹1.28 Cr",
        change: { text: "▲2.9% (+₹3.6 lac)", positive: true },
        meta: { units: "—", change: "▲2.9%" },
      },
      {
        title: "ROAS",
        value: "8.4x",
        change: { text: "▲1.9% (+0.16x)", positive: true },
        meta: { units: "—", change: "▲1.9%" },
      },
      {
        title: "Inorg Sales",
        value: "₹2.71 Cr",
        change: { text: "▲2.4% (+₹6.3 lac)", positive: true },
        meta: { units: "1.74 lac", change: "▲1.8%" },
      },
      {
        title: "Conversion",
        value: "4.7%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "—", change: "▲0.2 pp" },
      },
      {
        title: "Availability",
        value: "97.4%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "—", change: "▲0.5 pp" },
      },
      {
        title: "SOS",
        value: "38.9%",
        change: { text: "▲0.7 pp", positive: true },
        meta: { units: "—", change: "▲0.7 pp" },
      },
      {
        title: "Market Share",
        value: "37.0%",
        change: { text: "▲0.9 pp", positive: true },
        meta: { units: "—", change: "▲0.9 pp" },
      },
      {
        title: "Promo My Brand",
        value: "22.0%",
        change: { text: "▲0.9 pp", positive: true },
        meta: { units: "—", change: "▲0.9 pp" },
      },
      {
        title: "Promo Compete",
        value: "29.8%",
        change: { text: "▲0.9 pp", positive: true },
        meta: { units: "—", change: "▲0.9 pp" },
      },
      {
        title: "CPM",
        value: "₹141",
        change: { text: "▲2.4% (+₹3.3)", positive: true },
        meta: { units: "—", change: "▲2.4%" },
      },
      {
        title: "CPC",
        value: "₹7.8",
        change: { text: "▲2.1% (+₹0.16)", positive: true },
        meta: { units: "—", change: "▲2.1%" },
      },
    ],
  },

  /* -------------------- NOV -------------------- */
  {
    key: "nov",
    label: "Nov",
    logo: monthLogos["nov"],
    columns: [
      {
        title: "Offtakes",
        value: "₹12.9 Cr",
        change: { text: "▲2.3% (+₹29.6 lac)", positive: true },
        meta: { units: "6.3 lac", change: "▲1.2%" },
      },
      {
        title: "Spend",
        value: "₹1.32 Cr",
        change: { text: "▲1.6% (+₹2.1 lac)", positive: true },
        meta: { units: "—", change: "▲1.6%" },
      },
      {
        title: "ROAS",
        value: "8.5x",
        change: { text: "▲1.0% (+0.08x)", positive: true },
        meta: { units: "—", change: "▲1.0%" },
      },
      {
        title: "Inorg Sales",
        value: "₹2.79 Cr",
        change: { text: "▲1.4% (+₹3.8 lac)", positive: true },
        meta: { units: "1.79 lac", change: "▲0.9%" },
      },
      {
        title: "Conversion",
        value: "4.8%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "—", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "97.7%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "SOS",
        value: "39.3%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "—", change: "▲0.4 pp" },
      },
      {
        title: "Market Share",
        value: "37.4%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "—", change: "▲0.4 pp" },
      },
      {
        title: "Promo My Brand",
        value: "22.3%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "Promo Compete",
        value: "30.1%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "CPM",
        value: "₹143",
        change: { text: "▲1.8% (+₹2.5)", positive: true },
        meta: { units: "—", change: "▲1.8%" },
      },
      {
        title: "CPC",
        value: "₹7.9",
        change: { text: "▲1.4% (+₹0.11)", positive: true },
        meta: { units: "—", change: "▲1.4%" },
      },
    ],
  },

  /* -------------------- DEC -------------------- */
  {
    key: "dec",
    label: "Dec",
    logo: monthLogos["dec"],
    columns: [
      {
        title: "Offtakes",
        value: "₹13.5 Cr",
        change: { text: "▲3.7% (+₹48.2 lac)", positive: true },
        meta: { units: "6.7 lac", change: "▲2.1%" },
      },
      {
        title: "Spend",
        value: "₹1.38 Cr",
        change: { text: "▲2.1% (+₹2.8 lac)", positive: true },
        meta: { units: "—", change: "▲2.1%" },
      },
      {
        title: "ROAS",
        value: "8.7x",
        change: { text: "▲1.9% (+0.16x)", positive: true },
        meta: { units: "—", change: "▲1.9%" },
      },
      {
        title: "Inorg Sales",
        value: "₹2.92 Cr",
        change: { text: "▲1.8% (+₹5.2 lac)", positive: true },
        meta: { units: "1.86 lac", change: "▲1.4%" },
      },
      {
        title: "Conversion",
        value: "5.0%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "—", change: "▲0.2 pp" },
      },
      {
        title: "Availability",
        value: "98.0%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "—", change: "▲0.3 pp" },
      },
      {
        title: "SOS",
        value: "39.8%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "—", change: "▲0.5 pp" },
      },
      {
        title: "Market Share",
        value: "38.1%",
        change: { text: "▲0.7 pp", positive: true },
        meta: { units: "—", change: "▲0.7 pp" },
      },
      {
        title: "Promo My Brand",
        value: "22.9%",
        change: { text: "▲0.6 pp", positive: true },
        meta: { units: "—", change: "▲0.6 pp" },
      },
      {
        title: "Promo Compete",
        value: "30.5%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "—", change: "▲0.4 pp" },
      },
      {
        title: "CPM",
        value: "₹148",
        change: { text: "▲2.7% (+₹3.9)", positive: true },
        meta: { units: "—", change: "▲2.7%" },
      },
      {
        title: "CPC",
        value: "₹8.1",
        change: { text: "▲2.6% (+₹0.21)", positive: true },
        meta: { units: "—", change: "▲2.6%" },
      },
    ],
  },
];

export const defaultCategory = [
  // ---------------------- CASSATA ----------------------
  {
    key: "cassata",
    label: "Cassata",
    logo: categoryLogo,
    columns: [
      {
        title: "Offtakes",
        value: "₹1.32 Cr",
        change: { text: "▲3.1% (+₹4.0 lac)", positive: true },
        meta: { units: "0.68 lac units", change: "▲1.7%" },
      },
      {
        title: "Spend",
        value: "₹18.4 lac",
        change: { text: "▲1.9% (+₹0.35 lac)", positive: true },
        meta: { units: "₹18.4 lac", change: "▲1.9%" },
      },
      {
        title: "ROAS",
        value: "7.1x",
        change: { text: "▲0.2% (+0.01x)", positive: true },
        meta: { units: "₹1.30 Cr return", change: "▲0.2%" },
      },
      {
        title: "Inorg Sales",
        value: "₹0.21 Cr",
        change: { text: "▲2.2% (+₹0.45 lac)", positive: true },
        meta: { units: "0.12 lac units", change: "▲2.2%" },
      },
      {
        title: "Conversion",
        value: "3.9%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "12.4k conversions", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "95.8%",
        change: { text: "▼0.9 pp", positive: false },
        meta: { units: "1,240 stores", change: "▼0.9 pp" },
      },
      {
        title: "SOS",
        value: "29.8%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "29.8 shelf index", change: "▲0.3 pp" },
      },
      {
        title: "Market Share",
        value: "8.3%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "Category: ₹15.8 Cr", change: "▲0.2 pp" },
      },
      {
        title: "Promo My Brand",
        value: "18.2%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "Depth 18.2%", change: "▲0.5 pp" },
      },
      {
        title: "Promo Compete",
        value: "25.1%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "Depth 25.1%", change: "▲0.4 pp" },
      },
      {
        title: "CPM",
        value: "₹116",
        change: { text: "▲1.6% (+₹1.8)", positive: true },
        meta: { units: "14.1 lac impressions", change: "▲1.6%" },
      },
      {
        title: "CPC",
        value: "₹6.4",
        change: { text: "▲1.1% (+₹0.07)", positive: true },
        meta: { units: "0.82 lac clicks", change: "▲1.1%" },
      },
    ],
  },

  // ---------------------- CORE TUB ----------------------
  {
    key: "coreTub",
    label: "Core Tub",
    logo: categoryLogo,
    columns: [
      {
        title: "Offtakes",
        value: "₹3.12 Cr",
        change: { text: "▲3.6% (+₹10.9 lac)", positive: true },
        meta: { units: "1.52 lac units", change: "▲2.1%" },
      },
      {
        title: "Spend",
        value: "₹32.1 lac",
        change: { text: "▲2.2% (+₹0.7 lac)", positive: true },
        meta: { units: "₹32.1 lac", change: "▲2.2%" },
      },
      {
        title: "ROAS",
        value: "8.4x",
        change: { text: "▲0.3% (+0.02x)", positive: true },
        meta: { units: "₹2.71 Cr return", change: "▲0.3%" },
      },
      {
        title: "Inorg Sales",
        value: "₹0.42 Cr",
        change: { text: "▲2.0% (+₹0.8 lac)", positive: true },
        meta: { units: "0.26 lac units", change: "▲2.0%" },
      },
      {
        title: "Conversion",
        value: "4.4%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "19.1k conversions", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "94.2%",
        change: { text: "▼1.0 pp", positive: false },
        meta: { units: "1,720 stores", change: "▼1.0 pp" },
      },
      {
        title: "SOS",
        value: "34.3%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "34.3 shelf index", change: "▲0.4 pp" },
      },
      {
        title: "Market Share",
        value: "22.0%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "Category: ₹14.2 Cr", change: "▲0.3 pp" },
      },
      {
        title: "Promo My Brand",
        value: "20.9%",
        change: { text: "▲0.7 pp", positive: true },
        meta: { units: "Depth 20.9%", change: "▲0.7 pp" },
      },
      {
        title: "Promo Compete",
        value: "27.7%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "Depth 27.7%", change: "▲0.4 pp" },
      },
      {
        title: "CPM",
        value: "₹124",
        change: { text: "▲1.8% (+₹2.1)", positive: true },
        meta: { units: "19.8 lac impressions", change: "▲1.8%" },
      },
      {
        title: "CPC",
        value: "₹7.1",
        change: { text: "▲1.3% (+₹0.09)", positive: true },
        meta: { units: "1.36 lac clicks", change: "▲1.3%" },
      },
    ],
  },

  // ---------------------- CORNETTO ----------------------
  {
    key: "cornetto",
    label: "Cornetto",
    logo: categoryLogo,
    columns: [
      {
        title: "Offtakes",
        value: "₹3.98 Cr",
        change: { text: "▲4.3% (+₹16.9 lac)", positive: true },
        meta: { units: "2.03 lac units", change: "▲3.1%" },
      },
      {
        title: "Spend",
        value: "₹42.9 lac",
        change: { text: "▲2.4% (+₹1.0 lac)", positive: true },
        meta: { units: "₹42.9 lac", change: "▲2.4%" },
      },
      {
        title: "ROAS",
        value: "9.1x",
        change: { text: "▲0.4% (+0.03x)", positive: true },
        meta: { units: "₹3.91 Cr return", change: "▲0.4%" },
      },
      {
        title: "Inorg Sales",
        value: "₹0.58 Cr",
        change: { text: "▲2.5% (+₹1.4 lac)", positive: true },
        meta: { units: "0.34 lac units", change: "▲2.5%" },
      },
      {
        title: "Conversion",
        value: "4.9%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "22.6k conversions", change: "▲0.2 pp" },
      },
      {
        title: "Availability",
        value: "96.8%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "2,140 stores", change: "▲0.5 pp" },
      },
      {
        title: "SOS",
        value: "36.1%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "36.1 shelf index", change: "▲0.4 pp" },
      },
      {
        title: "Market Share",
        value: "27.2%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "Category: ₹14.6 Cr", change: "▲0.5 pp" },
      },
      {
        title: "Promo My Brand",
        value: "21.7%",
        change: { text: "▲0.6 pp", positive: true },
        meta: { units: "Depth 21.7%", change: "▲0.6 pp" },
      },
      {
        title: "Promo Compete",
        value: "28.8%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "Depth 28.8%", change: "▲0.5 pp" },
      },
      {
        title: "CPM",
        value: "₹131",
        change: { text: "▲2.1% (+₹2.7)", positive: true },
        meta: { units: "28.7 lac impressions", change: "▲2.1%" },
      },
      {
        title: "CPC",
        value: "₹7.6",
        change: { text: "▲1.4% (+₹0.11)", positive: true },
        meta: { units: "1.97 lac clicks", change: "▲1.4%" },
      },
    ],
  },

  // ---------------------- CUP ----------------------
  {
    key: "cup",
    label: "Cup",
    logo: categoryLogo,
    columns: [
      {
        title: "Offtakes",
        value: "₹1.94 Cr",
        change: { text: "▲2.4% (+₹4.5 lac)", positive: true },
        meta: { units: "1.04 lac units", change: "▲1.2%" },
      },
      {
        title: "Spend",
        value: "₹16.9 lac",
        change: { text: "▲1.7% (+₹0.28 lac)", positive: true },
        meta: { units: "₹16.9 lac", change: "▲1.7%" },
      },
      {
        title: "ROAS",
        value: "7.8x",
        change: { text: "▲0.2% (+0.02x)", positive: true },
        meta: { units: "₹1.52 Cr return", change: "▲0.2%" },
      },
      {
        title: "Inorg Sales",
        value: "₹0.27 Cr",
        change: { text: "▲1.9% (+₹0.5 lac)", positive: true },
        meta: { units: "0.18 lac units", change: "▲1.9%" },
      },
      {
        title: "Conversion",
        value: "4.2%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "18.4k conversions", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "97.9%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "1,980 stores", change: "▲0.4 pp" },
      },
      {
        title: "SOS",
        value: "28.7%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "28.7 shelf index", change: "▲0.3 pp" },
      },
      {
        title: "Market Share",
        value: "13.0%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "Category: ₹14.9 Cr", change: "▲0.2 pp" },
      },
      {
        title: "Promo My Brand",
        value: "19.6%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "Depth 19.6%", change: "▲0.4 pp" },
      },
      {
        title: "Promo Compete",
        value: "26.4%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "Depth 26.4%", change: "▲0.5 pp" },
      },
      {
        title: "CPM",
        value: "₹112",
        change: { text: "▲1.6% (+₹1.7)", positive: true },
        meta: { units: "13.5 lac impressions", change: "▲1.6%" },
      },
      {
        title: "CPC",
        value: "₹6.9",
        change: { text: "▲1.3% (+₹0.09)", positive: true },
        meta: { units: "1.02 lac clicks", change: "▲1.3%" },
      },
    ],
  },

  // ---------------------- KW STICKS ----------------------
  {
    key: "kwSticks",
    label: "KW Sticks",
    logo: categoryLogo,
    columns: [
      {
        title: "Offtakes",
        value: "₹2.58 Cr",
        change: { text: "▲3.2% (+₹8.0 lac)", positive: true },
        meta: { units: "1.33 lac units", change: "▲1.9%" },
      },
      {
        title: "Spend",
        value: "₹21.8 lac",
        change: { text: "▲1.9% (+₹0.41 lac)", positive: true },
        meta: { units: "₹21.8 lac", change: "▲1.9%" },
      },
      {
        title: "ROAS",
        value: "8.1x",
        change: { text: "▲0.4% (+0.03x)", positive: true },
        meta: { units: "₹2.09 Cr return", change: "▲0.4%" },
      },
      {
        title: "Inorg Sales",
        value: "₹0.36 Cr",
        change: { text: "▲2.1% (+₹0.7 lac)", positive: true },
        meta: { units: "0.24 lac units", change: "▲2.1%" },
      },
      {
        title: "Conversion",
        value: "4.5%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "20.2k conversions", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "93.2%",
        change: { text: "▼1.3 pp", positive: false },
        meta: { units: "1,630 stores", change: "▼1.3 pp" },
      },
      {
        title: "SOS",
        value: "33.2%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "33.2 shelf index", change: "▲0.3 pp" },
      },
      {
        title: "Market Share",
        value: "17.9%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "Category: ₹14.4 Cr", change: "▲0.3 pp" },
      },
      {
        title: "Promo My Brand",
        value: "20.7%",
        change: { text: "▲0.5 pp", positive: true },
        meta: { units: "Depth 20.7%", change: "▲0.5 pp" },
      },
      {
        title: "Promo Compete",
        value: "28.7%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "Depth 28.7%", change: "▲0.4 pp" },
      },
      {
        title: "CPM",
        value: "₹120",
        change: { text: "▲1.8% (+₹2.1)", positive: true },
        meta: { units: "17.6 lac impressions", change: "▲1.8%" },
      },
      {
        title: "CPC",
        value: "₹7.3",
        change: { text: "▲1.2% (+₹0.09)", positive: true },
        meta: { units: "1.28 lac clicks", change: "▲1.2%" },
      },
    ],
  },

  // ---------------------- MAGNUM ----------------------
  {
    key: "magnum",
    label: "Magnum",
    logo: categoryLogo,
    columns: [
      {
        title: "Offtakes",
        value: "₹1.54 Cr",
        change: { text: "▲2.9% (+₹4.3 lac)", positive: true },
        meta: { units: "0.82 lac units", change: "▲1.6%" },
      },
      {
        title: "Spend",
        value: "₹14.6 lac",
        change: { text: "▲1.6% (+₹0.23 lac)", positive: true },
        meta: { units: "₹14.6 lac", change: "▲1.6%" },
      },
      {
        title: "ROAS",
        value: "8.5x",
        change: { text: "▲0.3% (+0.02x)", positive: true },
        meta: { units: "₹1.46 Cr return", change: "▲0.3%" },
      },
      {
        title: "Inorg Sales",
        value: "₹0.24 Cr",
        change: { text: "▲1.8% (+₹0.4 lac)", positive: true },
        meta: { units: "0.15 lac units", change: "▲1.8%" },
      },
      {
        title: "Conversion",
        value: "4.1%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "13.9k conversions", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "96.1%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "1,460 stores", change: "▲0.3 pp" },
      },
      {
        title: "SOS",
        value: "31.9%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "31.9 shelf index", change: "▲0.2 pp" },
      },
      {
        title: "Market Share",
        value: "10.4%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "Category: ₹14.8 Cr", change: "▲0.2 pp" },
      },
      {
        title: "Promo My Brand",
        value: "19.1%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "Depth 19.1%", change: "▲0.3 pp" },
      },
      {
        title: "Promo Compete",
        value: "25.7%",
        change: { text: "▲0.4 pp", positive: true },
        meta: { units: "Depth 25.7%", change: "▲0.4 pp" },
      },
      {
        title: "CPM",
        value: "₹109",
        change: { text: "▲1.4% (+₹1.5)", positive: true },
        meta: { units: "12.8 lac impressions", change: "▲1.4%" },
      },
      {
        title: "CPC",
        value: "₹6.6",
        change: { text: "▲1.1% (+₹0.07)", positive: true },
        meta: { units: "0.87 lac clicks", change: "▲1.1%" },
      },
    ],
  },

  // ---------------------- OTHERS ----------------------
  {
    key: "others",
    label: "Others",
    logo: categoryLogo,
    columns: [
      {
        title: "Offtakes",
        value: "₹1.07 Cr",
        change: { text: "▲1.8% (+₹1.9 lac)", positive: true },
        meta: { units: "0.56 lac units", change: "▲0.9%" },
      },
      {
        title: "Spend",
        value: "₹11.9 lac",
        change: { text: "▲1.3% (+₹0.15 lac)", positive: true },
        meta: { units: "₹11.9 lac", change: "▲1.3%" },
      },
      {
        title: "ROAS",
        value: "7.4x",
        change: { text: "▲0.2% (+0.02x)", positive: true },
        meta: { units: "₹0.88 Cr return", change: "▲0.2%" },
      },
      {
        title: "Inorg Sales",
        value: "₹0.15 Cr",
        change: { text: "▲1.6% (+₹0.25 lac)", positive: true },
        meta: { units: "0.09 lac units", change: "▲1.6%" },
      },
      {
        title: "Conversion",
        value: "3.7%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "9.8k conversions", change: "▲0.1 pp" },
      },
      {
        title: "Availability",
        value: "91.8%",
        change: { text: "▼0.8 pp", positive: false },
        meta: { units: "930 stores", change: "▼0.8 pp" },
      },
      {
        title: "SOS",
        value: "27.8%",
        change: { text: "▲0.2 pp", positive: true },
        meta: { units: "27.8 shelf index", change: "▲0.2 pp" },
      },
      {
        title: "Market Share",
        value: "4.1%",
        change: { text: "▲0.1 pp", positive: true },
        meta: { units: "Category: ₹14.5 Cr", change: "▲0.1 pp" },
      },
      {
        title: "Promo My Brand",
        value: "17.2%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "Depth 17.2%", change: "▲0.3 pp" },
      },
      {
        title: "Promo Compete",
        value: "22.9%",
        change: { text: "▲0.3 pp", positive: true },
        meta: { units: "Depth 22.9%", change: "▲0.3 pp" },
      },
      {
        title: "CPM",
        value: "₹104",
        change: { text: "▲1.1% (+₹1.1)", positive: true },
        meta: { units: "9.4 lac impressions", change: "▲1.1%" },
      },
      {
        title: "CPC",
        value: "₹6.0",
        change: { text: "▲0.9% (+₹0.06)", positive: true },
        meta: { units: "0.69 lac clicks", change: "▲0.9%" },
      },
    ],
  },
];

export const allCategories = [
  {
    name: "Cassata",
    all: {
      offtake: "₹3.15 Cr",
      offtake_change: "+2.3%",
      category_share: "35%",
      category_share_change: "+1.1%",
      category_size: "₹9.0 Cr",
      category_size_change: "+3.2%",
      wt_osa: "92.1%",
      wt_osa_change: "+0.8%",
      wt_disc: "6.8%",
      wt_disc_change: "-0.3%",
      overall_sov: "27.4%",
      overall_sov_change: "+2.2%",
      impressions: "4.2 Cr",
      impressions_change: "+4.1%",
      clicks: "6.4 L",
      clicks_change: "+3.5%",
      ctr: "1.52%",
      ctr_change: "-0.2%",
      cvr: "3.9%",
      cvr_change: "+0.5%",
      orders: "24.6K",
      orders_change: "+1.9%",
      ad_spends: "₹38.6L",
      ad_spends_change: "+4.2%",
      roas: "4.8x",
      roas_change: "-1.3%",
    },
    blinkit: {
      offtake: "₹1.05 Cr",
      offtake_change: "+3.1%",
      category_share: "33%",
      category_share_change: "+1.0%",
      category_size: "₹3.2 Cr",
      category_size_change: "+2.8%",
      wt_osa: "91.5%",
      wt_osa_change: "+0.7%",
      wt_disc: "6.2%",
      wt_disc_change: "-0.2%",
      overall_sov: "26.8%",
      overall_sov_change: "+1.9%",
      impressions: "1.4 Cr",
      impressions_change: "+3.8%",
      clicks: "2.2 L",
      clicks_change: "+3.0%",
      ctr: "1.57%",
      ctr_change: "-0.1%",
      cvr: "4.0%",
      cvr_change: "+0.6%",
      orders: "8.4K",
      orders_change: "+2.0%",
      ad_spends: "₹12.3L",
      ad_spends_change: "+3.9%",
      roas: "4.9x",
      roas_change: "-1.0%",
    },
    zepto: {
      offtake: "₹0.82 Cr",
      offtake_change: "+2.7%",
      category_share: "26%",
      category_share_change: "+0.9%",
      category_size: "₹2.5 Cr",
      category_size_change: "+3.0%",
      wt_osa: "92.0%",
      wt_osa_change: "+0.6%",
      wt_disc: "5.9%",
      wt_disc_change: "-0.3%",
      overall_sov: "25.3%",
      overall_sov_change: "+1.8%",
      impressions: "1.1 Cr",
      impressions_change: "+3.2%",
      clicks: "1.6 L",
      clicks_change: "+2.5%",
      ctr: "1.45%",
      ctr_change: "-0.2%",
      cvr: "3.8%",
      cvr_change: "+0.5%",
      orders: "6.3K",
      orders_change: "+1.6%",
      ad_spends: "₹9.8L",
      ad_spends_change: "+3.1%",
      roas: "4.7x",
      roas_change: "-0.9%",
    },
    swiggy: {
      offtake: "₹0.64 Cr",
      offtake_change: "+2.1%",
      category_share: "20%",
      category_share_change: "+0.8%",
      category_size: "₹2.0 Cr",
      category_size_change: "+2.9%",
      wt_osa: "90.8%",
      wt_osa_change: "+0.5%",
      wt_disc: "6.1%",
      wt_disc_change: "-0.3%",
      overall_sov: "23.5%",
      overall_sov_change: "+1.6%",
      impressions: "0.9 Cr",
      impressions_change: "+3.0%",
      clicks: "1.3 L",
      clicks_change: "+2.2%",
      ctr: "1.44%",
      ctr_change: "-0.1%",
      cvr: "3.7%",
      cvr_change: "+0.4%",
      orders: "5.1K",
      orders_change: "+1.5%",
      ad_spends: "₹8.2L",
      ad_spends_change: "+2.8%",
      roas: "4.6x",
      roas_change: "-0.7%",
    },
    amazon: {
      offtake: "₹0.35 Cr",
      offtake_change: "+3.4%",
      category_share: "10%",
      category_share_change: "+1.0%",
      category_size: "₹1.2 Cr",
      category_size_change: "+3.1%",
      wt_osa: "89.9%",
      wt_osa_change: "+0.5%",
      wt_disc: "6.3%",
      wt_disc_change: "-0.2%",
      overall_sov: "21.7%",
      overall_sov_change: "+1.5%",
      impressions: "0.6 Cr",
      impressions_change: "+2.9%",
      clicks: "0.8 L",
      clicks_change: "+2.1%",
      ctr: "1.33%",
      ctr_change: "-0.1%",
      cvr: "3.6%",
      cvr_change: "+0.4%",
      orders: "3.4K",
      orders_change: "+1.3%",
      ad_spends: "₹6.3L",
      ad_spends_change: "+2.4%",
      roas: "4.5x",
      roas_change: "-0.6%",
    },
    flipkart: {
      offtake: "₹0.29 Cr",
      offtake_change: "+1.9%",
      category_share: "8%",
      category_share_change: "+0.7%",
      category_size: "₹1.0 Cr",
      category_size_change: "+3.0%",
      wt_osa: "89.5%",
      wt_osa_change: "+0.4%",
      wt_disc: "6.4%",
      wt_disc_change: "-0.2%",
      overall_sov: "20.4%",
      overall_sov_change: "+1.2%",
      impressions: "0.5 Cr",
      impressions_change: "+2.8%",
      clicks: "0.6 L",
      clicks_change: "+2.0%",
      ctr: "1.30%",
      ctr_change: "-0.1%",
      cvr: "3.5%",
      cvr_change: "+0.4%",
      orders: "2.8K",
      orders_change: "+1.2%",
      ad_spends: "₹5.7L",
      ad_spends_change: "+2.1%",
      roas: "4.4x",
      roas_change: "-0.5%",
    },
  },
  {
    name: "Core Tub",
    all: {
      offtake: "₹2.25 Cr",
      offtake_change: "-1.5%",
      category_share: "25%",
      category_share_change: "-0.7%",
      category_size: "₹9.0 Cr",
      category_size_change: "+3.2%",
      wt_osa: "88.4%",
      wt_osa_change: "+0.4%",
      wt_disc: "5.2%",
      wt_disc_change: "+0.2%",
      overall_sov: "22.8%",
      overall_sov_change: "-1.5%",
      impressions: "3.1 Cr",
      impressions_change: "-2.1%",
      clicks: "4.8 L",
      clicks_change: "-1.4%",
      ctr: "1.55%",
      ctr_change: "+0.3%",
      cvr: "4.1%",
      cvr_change: "-0.6%",
      orders: "19.4K",
      orders_change: "-0.9%",
      ad_spends: "₹31.8L",
      ad_spends_change: "-1.1%",
      roas: "4.3x",
      roas_change: "-0.8%",
    },
    blinkit: {
      offtake: "₹0.75 Cr",
      offtake_change: "-0.9%",
      category_share: "30%",
      category_share_change: "-0.5%",
      category_size: "₹2.6 Cr",
      category_size_change: "+2.7%",
      wt_osa: "87.5%",
      wt_osa_change: "+0.3%",
      wt_disc: "5.4%",
      wt_disc_change: "+0.2%",
      overall_sov: "21.9%",
      overall_sov_change: "-1.3%",
      impressions: "1.0 Cr",
      impressions_change: "-1.7%",
      clicks: "1.6 L",
      clicks_change: "-1.0%",
      ctr: "1.60%",
      ctr_change: "+0.2%",
      cvr: "4.0%",
      cvr_change: "-0.5%",
      orders: "6.3K",
      orders_change: "-0.7%",
      ad_spends: "₹10.4L",
      ad_spends_change: "-0.8%",
      roas: "4.4x",
      roas_change: "-0.7%",
    },
    zepto: {
      offtake: "₹0.57 Cr",
      offtake_change: "-1.2%",
      category_share: "25%",
      category_share_change: "-0.6%",
      category_size: "₹2.2 Cr",
      category_size_change: "+2.8%",
      wt_osa: "88.0%",
      wt_osa_change: "+0.4%",
      wt_disc: "5.1%",
      wt_disc_change: "+0.1%",
      overall_sov: "22.1%",
      overall_sov_change: "-1.4%",
      impressions: "0.8 Cr",
      impressions_change: "-1.6%",
      clicks: "1.3 L",
      clicks_change: "-0.9%",
      ctr: "1.58%",
      ctr_change: "+0.2%",
      cvr: "4.1%",
      cvr_change: "-0.4%",
      orders: "5.0K",
      orders_change: "-0.8%",
      ad_spends: "₹8.9L",
      ad_spends_change: "-0.9%",
      roas: "4.3x",
      roas_change: "-0.6%",
    },
    swiggy: {
      offtake: "₹0.46 Cr",
      offtake_change: "-1.0%",
      category_share: "20%",
      category_share_change: "-0.4%",
      category_size: "₹1.8 Cr",
      category_size_change: "+2.9%",
      wt_osa: "87.8%",
      wt_osa_change: "+0.3%",
      wt_disc: "5.3%",
      wt_disc_change: "+0.1%",
      overall_sov: "22.4%",
      overall_sov_change: "-1.2%",
      impressions: "0.7 Cr",
      impressions_change: "-1.5%",
      clicks: "1.0 L",
      clicks_change: "-0.8%",
      ctr: "1.52%",
      ctr_change: "+0.2%",
      cvr: "4.0%",
      cvr_change: "-0.5%",
      orders: "4.1K",
      orders_change: "-0.6%",
      ad_spends: "₹7.8L",
      ad_spends_change: "-0.7%",
      roas: "4.2x",
      roas_change: "-0.5%",
    },
    amazon: {
      offtake: "₹0.27 Cr",
      offtake_change: "-0.6%",
      category_share: "12%",
      category_share_change: "-0.3%",
      category_size: "₹1.2 Cr",
      category_size_change: "+2.8%",
      wt_osa: "86.9%",
      wt_osa_change: "+0.3%",
      wt_disc: "5.2%",
      wt_disc_change: "+0.2%",
      overall_sov: "21.8%",
      overall_sov_change: "-1.0%",
      impressions: "0.5 Cr",
      impressions_change: "-1.3%",
      clicks: "0.7 L",
      clicks_change: "-0.7%",
      ctr: "1.40%",
      ctr_change: "+0.1%",
      cvr: "3.9%",
      cvr_change: "-0.4%",
      orders: "3.0K",
      orders_change: "-0.5%",
      ad_spends: "₹6.2L",
      ad_spends_change: "-0.6%",
      roas: "4.1x",
      roas_change: "-0.4%",
    },
    flipkart: {
      offtake: "₹0.20 Cr",
      offtake_change: "-0.8%",
      category_share: "8%",
      category_share_change: "-0.2%",
      category_size: "₹1.0 Cr",
      category_size_change: "+2.7%",
      wt_osa: "86.5%",
      wt_osa_change: "+0.2%",
      wt_disc: "5.3%",
      wt_disc_change: "+0.1%",
      overall_sov: "21.2%",
      overall_sov_change: "-0.9%",
      impressions: "0.4 Cr",
      impressions_change: "-1.2%",
      clicks: "0.6 L",
      clicks_change: "-0.6%",
      ctr: "1.35%",
      ctr_change: "+0.1%",
      cvr: "3.8%",
      cvr_change: "-0.3%",
      orders: "2.4K",
      orders_change: "-0.4%",
      ad_spends: "₹5.1L",
      ad_spends_change: "-0.5%",
      roas: "4.0x",
      roas_change: "-0.3%",
    },
  },
  {
    name: "Magnum",
    all: {
      offtake: "₹2.25 Cr",
      offtake_change: "+1.1%",
      category_share: "25%",
      category_share_change: "+0.5%",
      category_size: "₹9.0 Cr",
      category_size_change: "+3.2%",
      wt_osa: "89.6%",
      wt_osa_change: "+0.7%",
      wt_disc: "4.9%",
      wt_disc_change: "-0.4%",
      overall_sov: "25.6%",
      overall_sov_change: "+1.2%",
      impressions: "3.3 Cr",
      impressions_change: "+1.7%",
      clicks: "5.0 L",
      clicks_change: "+2.3%",
      ctr: "1.51%",
      ctr_change: "-0.1%",
      cvr: "3.8%",
      cvr_change: "+0.4%",
      orders: "20.1K",
      orders_change: "+1.5%",
      ad_spends: "₹33.4L",
      ad_spends_change: "+2.1%",
      roas: "4.6x",
      roas_change: "+0.9%",
    },
    blinkit: {
      offtake: "₹0.75 Cr",
      offtake_change: "+1.6%",
      category_share: "30%",
      category_share_change: "+0.8%",
      category_size: "₹2.5 Cr",
      category_size_change: "+2.9%",
      wt_osa: "89.0%",
      wt_osa_change: "+0.6%",
      wt_disc: "4.7%",
      wt_disc_change: "-0.3%",
      overall_sov: "24.9%",
      overall_sov_change: "+1.1%",
      impressions: "1.1 Cr",
      impressions_change: "+1.5%",
      clicks: "1.6 L",
      clicks_change: "+2.0%",
      ctr: "1.45%",
      ctr_change: "-0.1%",
      cvr: "3.8%",
      cvr_change: "+0.4%",
      orders: "6.4K",
      orders_change: "+1.3%",
      ad_spends: "₹10.2L",
      ad_spends_change: "+1.7%",
      roas: "4.6x",
      roas_change: "+0.8%",
    },
    zepto: {
      offtake: "₹0.57 Cr",
      offtake_change: "+0.8%",
      category_share: "25%",
      category_share_change: "+0.6%",
      category_size: "₹2.1 Cr",
      category_size_change: "+2.8%",
      wt_osa: "89.4%",
      wt_osa_change: "+0.5%",
      wt_disc: "4.8%",
      wt_disc_change: "-0.2%",
      overall_sov: "25.0%",
      overall_sov_change: "+1.0%",
      impressions: "0.9 Cr",
      impressions_change: "+1.4%",
      clicks: "1.3 L",
      clicks_change: "+1.8%",
      ctr: "1.44%",
      ctr_change: "-0.1%",
      cvr: "3.7%",
      cvr_change: "+0.3%",
      orders: "5.0K",
      orders_change: "+1.2%",
      ad_spends: "₹8.7L",
      ad_spends_change: "+1.5%",
      roas: "4.5x",
      roas_change: "+0.7%",
    },
    swiggy: {
      offtake: "₹0.52 Cr",
      offtake_change: "+0.9%",
      category_share: "22%",
      category_share_change: "+0.5%",
      category_size: "₹2.0 Cr",
      category_size_change: "+2.7%",
      wt_osa: "89.1%",
      wt_osa_change: "+0.5%",
      wt_disc: "4.9%",
      wt_disc_change: "-0.2%",
      overall_sov: "24.6%",
      overall_sov_change: "+0.9%",
      impressions: "0.8 Cr",
      impressions_change: "+1.3%",
      clicks: "1.1 L",
      clicks_change: "+1.7%",
      ctr: "1.43%",
      ctr_change: "-0.1%",
      cvr: "3.7%",
      cvr_change: "+0.3%",
      orders: "4.2K",
      orders_change: "+1.1%",
      ad_spends: "₹7.6L",
      ad_spends_change: "+1.4%",
      roas: "4.4x",
      roas_change: "+0.6%",
    },
    amazon: {
      offtake: "₹0.28 Cr",
      offtake_change: "+0.7%",
      category_share: "12%",
      category_share_change: "+0.4%",
      category_size: "₹1.2 Cr",
      category_size_change: "+2.6%",
      wt_osa: "88.5%",
      wt_osa_change: "+0.4%",
      wt_disc: "4.8%",
      wt_disc_change: "-0.2%",
      overall_sov: "23.9%",
      overall_sov_change: "+0.8%",
      impressions: "0.5 Cr",
      impressions_change: "+1.1%",
      clicks: "0.7 L",
      clicks_change: "+1.5%",
      ctr: "1.40%",
      ctr_change: "-0.1%",
      cvr: "3.6%",
      cvr_change: "+0.2%",
      orders: "2.8K",
      orders_change: "+1.0%",
      ad_spends: "₹6.1L",
      ad_spends_change: "+1.3%",
      roas: "4.3x",
      roas_change: "+0.5%",
    },
    flipkart: {
      offtake: "₹0.20 Cr",
      offtake_change: "+0.5%",
      category_share: "8%",
      category_share_change: "+0.3%",
      category_size: "₹1.0 Cr",
      category_size_change: "+2.6%",
      wt_osa: "88.2%",
      wt_osa_change: "+0.3%",
      wt_disc: "4.9%",
      wt_disc_change: "-0.2%",
      overall_sov: "23.4%",
      overall_sov_change: "+0.7%",
      impressions: "0.4 Cr",
      impressions_change: "+1.0%",
      clicks: "0.6 L",
      clicks_change: "+1.4%",
      ctr: "1.38%",
      ctr_change: "-0.1%",
      cvr: "3.5%",
      cvr_change: "+0.2%",
      orders: "2.1K",
      orders_change: "+0.9%",
      ad_spends: "₹5.2L",
      ad_spends_change: "+1.2%",
      roas: "4.2x",
      roas_change: "+0.4%",
    },
  },
  {
    name: "KW Sticks",
    all: {
      offtake: "₹1.35 Cr",
      offtake_change: "-0.8%",
      category_share: "15%",
      category_share_change: "-0.5%",
      category_size: "₹9.0 Cr",
      category_size_change: "+2.7%",
      wt_osa: "88.7%",
      wt_osa_change: "-0.4%",
      wt_disc: "5.2%",
      wt_disc_change: "+0.3%",
      overall_sov: "18.3%",
      overall_sov_change: "-0.6%",
      impressions: "2.2 Cr",
      impressions_change: "-1.1%",
      clicks: "3.1 L",
      clicks_change: "-1.4%",
      ctr: "1.41%",
      ctr_change: "-0.2%",
      cvr: "3.4%",
      cvr_change: "-0.3%",
      orders: "10.5K",
      orders_change: "-1.0%",
      ad_spends: "₹22.6L",
      ad_spends_change: "-0.8%",
      roas: "4.1x",
      roas_change: "-0.5%",
    },
    blinkit: {
      offtake: "₹0.47 Cr",
      offtake_change: "-0.6%",
      category_share: "35%",
      category_share_change: "-0.4%",
      category_size: "₹1.9 Cr",
      category_size_change: "+2.4%",
      wt_osa: "88.5%",
      wt_osa_change: "-0.3%",
      wt_disc: "5.3%",
      wt_disc_change: "+0.3%",
      overall_sov: "18.1%",
      overall_sov_change: "-0.5%",
      impressions: "0.7 Cr",
      impressions_change: "-1.0%",
      clicks: "1.0 L",
      clicks_change: "-1.3%",
      ctr: "1.42%",
      ctr_change: "-0.2%",
      cvr: "3.5%",
      cvr_change: "-0.2%",
      orders: "3.7K",
      orders_change: "-0.9%",
      ad_spends: "₹7.5L",
      ad_spends_change: "-0.7%",
      roas: "4.2x",
      roas_change: "-0.4%",
    },
    zepto: {
      offtake: "₹0.34 Cr",
      offtake_change: "-0.7%",
      category_share: "25%",
      category_share_change: "-0.5%",
      category_size: "₹1.5 Cr",
      category_size_change: "+2.3%",
      wt_osa: "88.6%",
      wt_osa_change: "-0.3%",
      wt_disc: "5.2%",
      wt_disc_change: "+0.2%",
      overall_sov: "18.2%",
      overall_sov_change: "-0.5%",
      impressions: "0.5 Cr",
      impressions_change: "-1.1%",
      clicks: "0.7 L",
      clicks_change: "-1.4%",
      ctr: "1.41%",
      ctr_change: "-0.2%",
      cvr: "3.4%",
      cvr_change: "-0.3%",
      orders: "2.9K",
      orders_change: "-1.0%",
      ad_spends: "₹6.2L",
      ad_spends_change: "-0.8%",
      roas: "4.1x",
      roas_change: "-0.5%",
    },
    swiggy: {
      offtake: "₹0.27 Cr",
      offtake_change: "-0.8%",
      category_share: "20%",
      category_share_change: "-0.6%",
      category_size: "₹1.3 Cr",
      category_size_change: "+2.3%",
      wt_osa: "88.4%",
      wt_osa_change: "-0.3%",
      wt_disc: "5.2%",
      wt_disc_change: "+0.2%",
      overall_sov: "18.3%",
      overall_sov_change: "-0.5%",
      impressions: "0.4 Cr",
      impressions_change: "-1.1%",
      clicks: "0.6 L",
      clicks_change: "-1.4%",
      ctr: "1.40%",
      ctr_change: "-0.2%",
      cvr: "3.3%",
      cvr_change: "-0.3%",
      orders: "2.3K",
      orders_change: "-1.0%",
      ad_spends: "₹5.3L",
      ad_spends_change: "-0.8%",
      roas: "4.0x",
      roas_change: "-0.5%",
    },
    amazon: {
      offtake: "₹0.16 Cr",
      offtake_change: "-0.9%",
      category_share: "12%",
      category_share_change: "-0.6%",
      category_size: "₹1.1 Cr",
      category_size_change: "+2.2%",
      wt_osa: "88.2%",
      wt_osa_change: "-0.4%",
      wt_disc: "5.1%",
      wt_disc_change: "+0.2%",
      overall_sov: "18.4%",
      overall_sov_change: "-0.5%",
      impressions: "0.3 Cr",
      impressions_change: "-1.1%",
      clicks: "0.4 L",
      clicks_change: "-1.3%",
      ctr: "1.39%",
      ctr_change: "-0.2%",
      cvr: "3.3%",
      cvr_change: "-0.3%",
      orders: "1.6K",
      orders_change: "-1.0%",
      ad_spends: "₹4.5L",
      ad_spends_change: "-0.8%",
      roas: "4.0x",
      roas_change: "-0.5%",
    },
    flipkart: {
      offtake: "₹0.11 Cr",
      offtake_change: "-1.0%",
      category_share: "8%",
      category_share_change: "-0.6%",
      category_size: "₹1.0 Cr",
      category_size_change: "+2.2%",
      wt_osa: "88.1%",
      wt_osa_change: "-0.4%",
      wt_disc: "5.0%",
      wt_disc_change: "+0.2%",
      overall_sov: "18.5%",
      overall_sov_change: "-0.5%",
      impressions: "0.2 Cr",
      impressions_change: "-1.1%",
      clicks: "0.3 L",
      clicks_change: "-1.3%",
      ctr: "1.38%",
      ctr_change: "-0.2%",
      cvr: "3.2%",
      cvr_change: "-0.3%",
      orders: "1.1K",
      orders_change: "-1.0%",
      ad_spends: "₹3.9L",
      ad_spends_change: "-0.8%",
      roas: "3.9x",
      roas_change: "-0.5%",
    },
  },
];

export const allProducts = [
  {
    name: "Dairy Day Mango Tub",
    all: {
      offtake: "₹3.42 Cr",
      offtake_change: "+3.1%",
      category_share: "37%",
      category_share_change: "+1.4%",
      category_size: "₹9.3 Cr",
      category_size_change: "+3.8%",
      wt_osa: "93.4%",
      wt_osa_change: "+1.1%",
      wt_disc: "6.1%",
      wt_disc_change: "-0.4%",
      overall_sov: "28.2%",
      overall_sov_change: "+2.5%",
      impressions: "4.5 Cr",
      impressions_change: "+4.4%",
      clicks: "6.9 L",
      clicks_change: "+3.9%",
      ctr: "1.54%",
      ctr_change: "-0.1%",
      cvr: "4.2%",
      cvr_change: "+0.7%",
      orders: "26.3K",
      orders_change: "+2.4%",
      ad_spends: "₹39.8L",
      ad_spends_change: "+4.6%",
      roas: "5.1x",
      roas_change: "-1.0%",
    },
    blinkit: {
      offtake: "₹1.18 Cr",
      offtake_change: "+3.8%",
      category_share: "34%",
      category_share_change: "+1.3%",
      category_size: "₹3.4 Cr",
      category_size_change: "+3.1%",
      wt_osa: "92.7%",
      wt_osa_change: "+0.8%",
      wt_disc: "5.8%",
      wt_disc_change: "-0.3%",
      overall_sov: "27.6%",
      overall_sov_change: "+2.1%",
      impressions: "1.5 Cr",
      impressions_change: "+4.0%",
      clicks: "2.4 L",
      clicks_change: "+3.3%",
      ctr: "1.60%",
      ctr_change: "-0.1%",
      cvr: "4.3%",
      cvr_change: "+0.7%",
      orders: "9.1K",
      orders_change: "+2.4%",
      ad_spends: "₹12.9L",
      ad_spends_change: "+4.1%",
      roas: "5.2x",
      roas_change: "-0.8%",
    },
    zepto: {
      offtake: "₹0.90 Cr",
      offtake_change: "+3.0%",
      category_share: "27%",
      category_share_change: "+1.0%",
      category_size: "₹2.6 Cr",
      category_size_change: "+3.5%",
      wt_osa: "93.0%",
      wt_osa_change: "+0.9%",
      wt_disc: "5.6%",
      wt_disc_change: "-0.2%",
      overall_sov: "26.1%",
      overall_sov_change: "+1.9%",
      impressions: "1.2 Cr",
      impressions_change: "+3.5%",
      clicks: "1.7 L",
      clicks_change: "+2.8%",
      ctr: "1.47%",
      ctr_change: "-0.1%",
      cvr: "4.0%",
      cvr_change: "+0.6%",
      orders: "6.9K",
      orders_change: "+1.9%",
      ad_spends: "₹10.2L",
      ad_spends_change: "+3.3%",
      roas: "4.9x",
      roas_change: "-0.7%",
    },
    swiggy: {
      offtake: "₹0.70 Cr",
      offtake_change: "+2.8%",
      category_share: "21%",
      category_share_change: "+0.9%",
      category_size: "₹2.1 Cr",
      category_size_change: "+3.2%",
      wt_osa: "91.8%",
      wt_osa_change: "+0.6%",
      wt_disc: "5.9%",
      wt_disc_change: "-0.2%",
      overall_sov: "24.3%",
      overall_sov_change: "+1.7%",
      impressions: "1.0 Cr",
      impressions_change: "+3.2%",
      clicks: "1.5 L",
      clicks_change: "+2.4%",
      ctr: "1.46%",
      ctr_change: "-0.1%",
      cvr: "3.9%",
      cvr_change: "+0.4%",
      orders: "5.7K",
      orders_change: "+1.6%",
      ad_spends: "₹8.8L",
      ad_spends_change: "+3.0%",
      roas: "4.7x",
      roas_change: "-0.6%",
    },
    amazon: {
      offtake: "₹0.38 Cr",
      offtake_change: "+3.6%",
      category_share: "11%",
      category_share_change: "+1.1%",
      category_size: "₹1.3 Cr",
      category_size_change: "+3.3%",
      wt_osa: "90.7%",
      wt_osa_change: "+0.6%",
      wt_disc: "6.0%",
      wt_disc_change: "-0.2%",
      overall_sov: "22.4%",
      overall_sov_change: "+1.6%",
      impressions: "0.7 Cr",
      impressions_change: "+3.1%",
      clicks: "0.9 L",
      clicks_change: "+2.3%",
      ctr: "1.35%",
      ctr_change: "-0.1%",
      cvr: "3.8%",
      cvr_change: "+0.4%",
      orders: "3.7K",
      orders_change: "+1.4%",
      ad_spends: "₹6.6L",
      ad_spends_change: "+2.6%",
      roas: "4.6x",
      roas_change: "-0.5%",
    },
    flipkart: {
      offtake: "₹0.32 Cr",
      offtake_change: "+2.3%",
      category_share: "8%",
      category_share_change: "+0.8%",
      category_size: "₹1.1 Cr",
      category_size_change: "+3.1%",
      wt_osa: "90.1%",
      wt_osa_change: "+0.5%",
      wt_disc: "6.2%",
      wt_disc_change: "-0.2%",
      overall_sov: "21.1%",
      overall_sov_change: "+1.3%",
      impressions: "0.6 Cr",
      impressions_change: "+2.9%",
      clicks: "0.7 L",
      clicks_change: "+2.1%",
      ctr: "1.32%",
      ctr_change: "-0.1%",
      cvr: "3.6%",
      cvr_change: "+0.3%",
      orders: "3.0K",
      orders_change: "+1.1%",
      ad_spends: "₹5.9L",
      ad_spends_change: "+2.3%",
      roas: "4.5x",
      roas_change: "-0.4%",
    },
  },

  /* -------------------------------------------------- */
  /* --------------- SECOND PRODUCT --------------------*/
  /* -------------------------------------------------- */

  {
    name: "Dairy Day Vanilla Tub",
    all: {
      offtake: "₹2.41 Cr",
      offtake_change: "-1.1%",
      category_share: "26%",
      category_share_change: "-0.5%",
      category_size: "₹9.3 Cr",
      category_size_change: "+3.2%",
      wt_osa: "89.2%",
      wt_osa_change: "+0.5%",
      wt_disc: "5.4%",
      wt_disc_change: "+0.1%",
      overall_sov: "23.1%",
      overall_sov_change: "-1.3%",
      impressions: "3.4 Cr",
      impressions_change: "-1.8%",
      clicks: "5.1 L",
      clicks_change: "-1.2%",
      ctr: "1.50%",
      ctr_change: "+0.2%",
      cvr: "4.2%",
      cvr_change: "-0.5%",
      orders: "20.2K",
      orders_change: "-0.8%",
      ad_spends: "₹32.7L",
      ad_spends_change: "-0.6%",
      roas: "4.4x",
      roas_change: "-0.7%",
    },
    blinkit: {
      offtake: "₹0.82 Cr",
      offtake_change: "-0.7%",
      category_share: "31%",
      category_share_change: "-0.4%",
      category_size: "₹2.7 Cr",
      category_size_change: "+2.8%",
      wt_osa: "88.7%",
      wt_osa_change: "+0.3%",
      wt_disc: "5.5%",
      wt_disc_change: "+0.2%",
      overall_sov: "22.4%",
      overall_sov_change: "-1.1%",
      impressions: "1.1 Cr",
      impressions_change: "-1.5%",
      clicks: "1.7 L",
      clicks_change: "-0.9%",
      ctr: "1.57%",
      ctr_change: "+0.2%",
      cvr: "4.1%",
      cvr_change: "-0.4%",
      orders: "6.8K",
      orders_change: "-0.6%",
      ad_spends: "₹10.8L",
      ad_spends_change: "-0.5%",
      roas: "4.5x",
      roas_change: "-0.6%",
    },
    zepto: {
      offtake: "₹0.61 Cr",
      offtake_change: "-1.0%",
      category_share: "26%",
      category_share_change: "-0.5%",
      category_size: "₹2.3 Cr",
      category_size_change: "+2.7%",
      wt_osa: "89.0%",
      wt_osa_change: "+0.4%",
      wt_disc: "5.3%",
      wt_disc_change: "+0.1%",
      overall_sov: "22.6%",
      overall_sov_change: "-1.2%",
      impressions: "0.9 Cr",
      impressions_change: "-1.4%",
      clicks: "1.4 L",
      clicks_change: "-0.8%",
      ctr: "1.55%",
      ctr_change: "+0.2%",
      cvr: "4.0%",
      cvr_change: "-0.4%",
      orders: "5.4K",
      orders_change: "-0.7%",
      ad_spends: "₹9.2L",
      ad_spends_change: "-0.7%",
      roas: "4.4x",
      roas_change: "-0.5%",
    },
    swiggy: {
      offtake: "₹0.50 Cr",
      offtake_change: "-0.9%",
      category_share: "21%",
      category_share_change: "-0.4%",
      category_size: "₹1.9 Cr",
      category_size_change: "+2.6%",
      wt_osa: "88.8%",
      wt_osa_change: "+0.3%",
      wt_disc: "5.4%",
      wt_disc_change: "+0.1%",
      overall_sov: "22.2%",
      overall_sov_change: "-1.0%",
      impressions: "0.8 Cr",
      impressions_change: "-1.3%",
      clicks: "1.1 L",
      clicks_change: "-0.7%",
      ctr: "1.53%",
      ctr_change: "+0.2%",
      cvr: "3.9%",
      cvr_change: "-0.3%",
      orders: "4.4K",
      orders_change: "-0.6%",
      ad_spends: "₹8.1L",
      ad_spends_change: "-0.6%",
      roas: "4.2x",
      roas_change: "-0.4%",
    },
    amazon: {
      offtake: "₹0.29 Cr",
      offtake_change: "-0.5%",
      category_share: "13%",
      category_share_change: "-0.3%",
      category_size: "₹1.3 Cr",
      category_size_change: "+2.6%",
      wt_osa: "88.1%",
      wt_osa_change: "+0.3%",
      wt_disc: "5.3%",
      wt_disc_change: "+0.1%",
      overall_sov: "21.7%",
      overall_sov_change: "-0.8%",
      impressions: "0.6 Cr",
      impressions_change: "-1.2%",
      clicks: "0.8 L",
      clicks_change: "-0.6%",
      ctr: "1.44%",
      ctr_change: "+0.1%",
      cvr: "3.8%",
      cvr_change: "-0.3%",
      orders: "3.2K",
      orders_change: "-0.5%",
      ad_spends: "₹6.5L",
      ad_spends_change: "-0.5%",
      roas: "4.1x",
      roas_change: "-0.3%",
    },
    flipkart: {
      offtake: "₹0.23 Cr",
      offtake_change: "-0.6%",
      category_share: "9%",
      category_share_change: "-0.2%",
      category_size: "₹1.1 Cr",
      category_size_change: "+2.5%",
      wt_osa: "87.9%",
      wt_osa_change: "+0.2%",
      wt_disc: "5.2%",
      wt_disc_change: "+0.1%",
      overall_sov: "21.0%",
      overall_sov_change: "-0.7%",
      impressions: "0.5 Cr",
      impressions_change: "-1.1%",
      clicks: "0.7 L",
      clicks_change: "-0.5%",
      ctr: "1.39%",
      ctr_change: "+0.1%",
      cvr: "3.7%",
      cvr_change: "-0.2%",
      orders: "2.6K",
      orders_change: "-0.4%",
      ad_spends: "₹5.4L",
      ad_spends_change: "-0.4%",
      roas: "4.0x",
      roas_change: "-0.3%",
    },
  },

  /* -------------------------------------------------- */
  /* --------------- THIRD PRODUCT ---------------------*/
  /* -------------------------------------------------- */

  {
    name: "kwality Walls Kesar Tub",
    all: {
      offtake: "₹2.48 Cr",
      offtake_change: "+1.3%",
      category_share: "27%",
      category_share_change: "+0.6%",
      category_size: "₹9.4 Cr",
      category_size_change: "+3.4%",
      wt_osa: "90.2%",
      wt_osa_change: "+0.8%",
      wt_disc: "4.7%",
      wt_disc_change: "-0.3%",
      overall_sov: "26.1%",
      overall_sov_change: "+1.3%",
      impressions: "3.5 Cr",
      impressions_change: "+1.9%",
      clicks: "5.4 L",
      clicks_change: "+2.5%",
      ctr: "1.54%",
      ctr_change: "-0.1%",
      cvr: "3.9%",
      cvr_change: "+0.5%",
      orders: "21.4K",
      orders_change: "+1.7%",
      ad_spends: "₹34.2L",
      ad_spends_change: "+2.3%",
      roas: "4.8x",
      roas_change: "+0.8%",
    },
    blinkit: {
      offtake: "₹0.82 Cr",
      offtake_change: "+1.8%",
      category_share: "31%",
      category_share_change: "+0.9%",
      category_size: "₹2.6 Cr",
      category_size_change: "+3.0%",
      wt_osa: "89.7%",
      wt_osa_change: "+0.7%",
      wt_disc: "4.6%",
      wt_disc_change: "-0.3%",
      overall_sov: "25.4%",
      overall_sov_change: "+1.2%",
      impressions: "1.2 Cr",
      impressions_change: "+1.7%",
      clicks: "1.8 L",
      clicks_change: "+2.2%",
      ctr: "1.46%",
      ctr_change: "-0.1%",
      cvr: "3.9%",
      cvr_change: "+0.4%",
      orders: "6.9K",
      orders_change: "+1.5%",
      ad_spends: "₹10.6L",
      ad_spends_change: "+1.9%",
      roas: "4.8x",
      roas_change: "+0.7%",
    },
    zepto: {
      offtake: "₹0.61 Cr",
      offtake_change: "+1.1%",
      category_share: "26%",
      category_share_change: "+0.7%",
      category_size: "₹2.2 Cr",
      category_size_change: "+2.9%",
      wt_osa: "90.0%",
      wt_osa_change: "+0.6%",
      wt_disc: "4.7%",
      wt_disc_change: "-0.2%",
      overall_sov: "25.5%",
      overall_sov_change: "+1.1%",
      impressions: "1.0 Cr",
      impressions_change: "+1.6%",
      clicks: "1.4 L",
      clicks_change: "+2.0%",
      ctr: "1.45%",
      ctr_change: "-0.1%",
      cvr: "3.8%",
      cvr_change: "+0.3%",
      orders: "5.3K",
      orders_change: "+1.4%",
      ad_spends: "₹9.1L",
      ad_spends_change: "+1.7%",
      roas: "4.6x",
      roas_change: "+0.6%",
    },
    swiggy: {
      offtake: "₹0.55 Cr",
      offtake_change: "+1.0%",
      category_share: "22%",
      category_share_change: "+0.4%",
      category_size: "₹2.1 Cr",
      category_size_change: "+2.7%",
      wt_osa: "89.6%",
      wt_osa_change: "+0.6%",
      wt_disc: "4.8%",
      wt_disc_change: "-0.2%",
      overall_sov: "24.9%",
      overall_sov_change: "+1.0%",
      impressions: "0.9 Cr",
      impressions_change: "+1.5%",
      clicks: "1.2 L",
      clicks_change: "+1.9%",
      ctr: "1.43%",
      ctr_change: "-0.1%",
      cvr: "3.7%",
      cvr_change: "+0.3%",
      orders: "4.5K",
      orders_change: "+1.3%",
      ad_spends: "₹7.8L",
      ad_spends_change: "+1.6%",
      roas: "4.5x",
      roas_change: "+0.5%",
    },
    amazon: {
      offtake: "₹0.30 Cr",
      offtake_change: "+0.9%",
      category_share: "12%",
      category_share_change: "+0.3%",
      category_size: "₹1.3 Cr",
      category_size_change: "+2.6%",
      wt_osa: "89.0%",
      wt_osa_change: "+0.5%",
      wt_disc: "4.7%",
      wt_disc_change: "-0.2%",
      overall_sov: "24.2%",
      overall_sov_change: "+0.9%",
      impressions: "0.6 Cr",
      impressions_change: "+1.3%",
      clicks: "0.8 L",
      clicks_change: "+1.7%",
      ctr: "1.41%",
      ctr_change: "-0.1%",
      cvr: "3.6%",
      cvr_change: "+0.2%",
      orders: "3.0K",
      orders_change: "+1.1%",
      ad_spends: "₹6.4L",
      ad_spends_change: "+1.5%",
      roas: "4.4x",
      roas_change: "+0.5%",
    },
    flipkart: {
      offtake: "₹0.22 Cr",
      offtake_change: "+0.7%",
      category_share: "8%",
      category_share_change: "+0.2%",
      category_size: "₹1.1 Cr",
      category_size_change: "+2.5%",
      wt_osa: "88.7%",
      wt_osa_change: "+0.4%",
      wt_disc: "4.8%",
      wt_disc_change: "-0.1%",
      overall_sov: "23.6%",
      overall_sov_change: "+0.8%",
      impressions: "0.5 Cr",
      impressions_change: "+1.2%",
      clicks: "0.6 L",
      clicks_change: "+1.6%",
      ctr: "1.39%",
      ctr_change: "-0.1%",
      cvr: "3.5%",
      cvr_change: "+0.2%",
      orders: "2.3K",
      orders_change: "+0.9%",
      ad_spends: "₹5.3L",
      ad_spends_change: "+1.4%",
      roas: "4.3x",
      roas_change: "+0.4%",
    },
  },

  /* -------------------------------------------------- */
  /* --------------- FOURTH PRODUCT --------------------*/
  /* -------------------------------------------------- */

  {
    name: "Mother Dairy Vanilla Tub",
    all: {
      offtake: "₹1.48 Cr",
      offtake_change: "-0.5%",
      category_share: "16%",
      category_share_change: "-0.4%",
      category_size: "₹9.1 Cr",
      category_size_change: "+2.9%",
      wt_osa: "89.3%",
      wt_osa_change: "-0.3%",
      wt_disc: "5.4%",
      wt_disc_change: "+0.2%",
      overall_sov: "19.1%",
      overall_sov_change: "-0.4%",
      impressions: "2.4 Cr",
      impressions_change: "-0.9%",
      clicks: "3.4 L",
      clicks_change: "-1.0%",
      ctr: "1.40%",
      ctr_change: "-0.1%",
      cvr: "3.5%",
      cvr_change: "-0.2%",
      orders: "11.2K",
      orders_change: "-0.7%",
      ad_spends: "₹23.9L",
      ad_spends_change: "-0.5%",
      roas: "4.2x",
      roas_change: "-0.4%",
    },
    blinkit: {
      offtake: "₹0.53 Cr",
      offtake_change: "-0.4%",
      category_share: "36%",
      category_share_change: "-0.3%",
      category_size: "₹2.0 Cr",
      category_size_change: "+2.6%",
      wt_osa: "89.0%",
      wt_osa_change: "-0.2%",
      wt_disc: "5.5%",
      wt_disc_change: "+0.2%",
      overall_sov: "18.9%",
      overall_sov_change: "-0.4%",
      impressions: "0.8 Cr",
      impressions_change: "-0.8%",
      clicks: "1.2 L",
      clicks_change: "-1.0%",
      ctr: "1.41%",
      ctr_change: "-0.1%",
      cvr: "3.6%",
      cvr_change: "-0.1%",
      orders: "4.1K",
      orders_change: "-0.6%",
      ad_spends: "₹7.9L",
      ad_spends_change: "-0.6%",
      roas: "4.3x",
      roas_change: "-0.4%",
    },
    zepto: {
      offtake: "₹0.38 Cr",
      offtake_change: "-0.6%",
      category_share: "26%",
      category_share_change: "-0.4%",
      category_size: "₹1.6 Cr",
      category_size_change: "+2.4%",
      wt_osa: "89.1%",
      wt_osa_change: "-0.2%",
      wt_disc: "5.4%",
      wt_disc_change: "+0.2%",
      overall_sov: "19.0%",
      overall_sov_change: "-0.4%",
      impressions: "0.6 Cr",
      impressions_change: "-0.9%",
      clicks: "0.8 L",
      clicks_change: "-1.1%",
      ctr: "1.40%",
      ctr_change: "-0.1%",
      cvr: "3.5%",
      cvr_change: "-0.2%",
      orders: "3.2K",
      orders_change: "-0.7%",
      ad_spends: "₹6.5L",
      ad_spends_change: "-0.6%",
      roas: "4.2x",
      roas_change: "-0.4%",
    },
    swiggy: {
      offtake: "₹0.30 Cr",
      offtake_change: "-0.7%",
      category_share: "21%",
      category_share_change: "-0.5%",
      category_size: "₹1.4 Cr",
      category_size_change: "+2.3%",
      wt_osa: "88.9%",
      wt_osa_change: "-0.3%",
      wt_disc: "5.3%",
      wt_disc_change: "+0.1%",
      overall_sov: "19.1%",
      overall_sov_change: "-0.3%",
      impressions: "0.5 Cr",
      impressions_change: "-1.0%",
      clicks: "0.7 L",
      clicks_change: "-1.2%",
      ctr: "1.38%",
      ctr_change: "-0.1%",
      cvr: "3.4%",
      cvr_change: "-0.2%",
      orders: "2.6K",
      orders_change: "-0.7%",
      ad_spends: "₹5.6L",
      ad_spends_change: "-0.5%",
      roas: "4.1x",
      roas_change: "-0.3%",
    },
    amazon: {
      offtake: "₹0.18 Cr",
      offtake_change: "-0.8%",
      category_share: "12%",
      category_share_change: "-0.5%",
      category_size: "₹1.2 Cr",
      category_size_change: "+2.2%",
      wt_osa: "88.7%",
      wt_osa_change: "-0.3%",
      wt_disc: "5.2%",
      wt_disc_change: "+0.2%",
      overall_sov: "19.2%",
      overall_sov_change: "-0.3%",
      impressions: "0.3 Cr",
      impressions_change: "-0.9%",
      clicks: "0.5 L",
      clicks_change: "-1.0%",
      ctr: "1.37%",
      ctr_change: "-0.1%",
      cvr: "3.3%",
      cvr_change: "-0.2%",
      orders: "1.8K",
      orders_change: "-0.6%",
      ad_spends: "₹4.7L",
      ad_spends_change: "-0.5%",
      roas: "4.0x",
      roas_change: "-0.3%",
    },
    flipkart: {
      offtake: "₹0.12 Cr",
      offtake_change: "-0.9%",
      category_share: "9%",
      category_share_change: "-0.3%",
      category_size: "₹1.0 Cr",
      category_size_change: "+2.2%",
      wt_osa: "88.6%",
      wt_osa_change: "-0.4%",
      wt_disc: "5.1%",
      wt_disc_change: "+0.2%",
      overall_sov: "19.3%",
      overall_sov_change: "-0.3%",
      impressions: "0.2 Cr",
      impressions_change: "-0.8%",
      clicks: "0.3 L",
      clicks_change: "-0.9%",
      ctr: "1.36%",
      ctr_change: "-0.1%",
      cvr: "3.2%",
      cvr_change: "-0.2%",
      orders: "1.2K",
      orders_change: "-0.6%",
      ad_spends: "₹4.0L",
      ad_spends_change: "-0.4%",
      roas: "3.9x",
      roas_change: "-0.2%",
    },
  },
];
