
import indiaGeoJson from "./india_states.json";

export const INDIA_GEOJSON = indiaGeoJson;

export const INDIA_BOUNDS = [
    [68.1, 6.5], // Southwest coordinates
    [97.4, 37.6], // Northeast coordinates
];

export const STATES = [
    {
        id: "AP",
        name: "Andhra Pradesh",
        geojson_name: "Andhra Pradesh",
        idx: 0,
        center: [79.74, 15.91],
        importance: "High",
    },
    {
        id: "AR",
        name: "Arunachal Pradesh",
        geojson_name: "Arunachal Pradesh",
        idx: 1,
        center: [94.72, 28.21],
        importance: "Low",
    },
    {
        id: "AS",
        name: "Assam",
        geojson_name: "Assam",
        idx: 2,
        center: [92.93, 26.2],
        importance: "Medium",
    },
    {
        id: "BR",
        name: "Bihar",
        geojson_name: "Bihar",
        idx: 3,
        center: [85.31, 25.09],
        importance: "High",
    },
    {
        id: "CT",
        name: "Chhattisgarh",
        geojson_name: "Chhattisgarh",
        idx: 4,
        center: [81.86, 21.27],
        importance: "Medium",
    },
    {
        id: "GA",
        name: "Goa",
        geojson_name: "Goa",
        idx: 5,
        center: [74.12, 15.29],
        importance: "Low",
    },
    {
        id: "GJ",
        name: "Gujarat",
        geojson_name: "Gujarat",
        idx: 6,
        center: [71.19, 22.25],
        importance: "High",
    },
    {
        id: "HR",
        name: "Haryana",
        geojson_name: "Haryana",
        idx: 7,
        center: [76.08, 29.05],
        importance: "Medium",
    },
    {
        id: "HP",
        name: "Himachal Pradesh",
        geojson_name: "Himachal Pradesh",
        idx: 8,
        center: [77.17, 31.1],
        importance: "Low",
    },
    {
        id: "JK",
        name: "Jammu & Kashmir",
        geojson_name: "Jammu & Kashmir",
        idx: 9,
        center: [74.79, 34.08],
        importance: "Low",
    },
    {
        id: "JH",
        name: "Jharkhand",
        geojson_name: "Jharkhand",
        idx: 10,
        center: [85.27, 23.61],
        importance: "Medium",
    },
    {
        id: "KA",
        name: "Karnataka",
        geojson_name: "Karnataka",
        idx: 11,
        center: [75.71, 15.31],
        importance: "High",
    },
    {
        id: "KL",
        name: "Kerala",
        geojson_name: "Kerala",
        idx: 12,
        center: [76.27, 10.85],
        importance: "High",
    },
    {
        id: "MP",
        name: "Madhya Pradesh",
        geojson_name: "Madhya Pradesh",
        idx: 13,
        center: [78.65, 22.97],
        importance: "High",
    },
    {
        id: "MH",
        name: "Maharashtra",
        geojson_name: "Maharashtra",
        idx: 14,
        center: [75.71, 19.75],
        importance: "High",
    },
    {
        id: "MN",
        name: "Manipur",
        geojson_name: "Manipur",
        idx: 15,
        center: [93.9, 24.66],
        importance: "Low",
    },
    {
        id: "ML",
        name: "Meghalaya",
        geojson_name: "Meghalaya",
        idx: 16,
        center: [91.36, 25.46],
        importance: "Low",
    },
    {
        id: "MZ",
        name: "Mizoram",
        geojson_name: "Mizoram",
        idx: 17,
        center: [92.93, 23.16],
        importance: "Low",
    },
    {
        id: "NL",
        name: "Nagaland",
        geojson_name: "Nagaland",
        idx: 18,
        center: [94.56, 26.15],
        importance: "Low",
    },
    {
        id: "OD",
        name: "Odisha",
        geojson_name: "Odisha",
        idx: 19,
        center: [84.8, 20.95],
        importance: "Medium",
    },
    {
        id: "PB",
        name: "Punjab",
        geojson_name: "Punjab",
        idx: 20,
        center: [75.34, 31.14],
        importance: "High",
    },
    {
        id: "RJ",
        name: "Rajasthan",
        geojson_name: "Rajasthan",
        idx: 21,
        center: [74.21, 27.02],
        importance: "High",
    },
    {
        id: "SK",
        name: "Sikkim",
        geojson_name: "Sikkim",
        idx: 22,
        center: [88.51, 27.53],
        importance: "Low",
    },
    {
        id: "TN",
        name: "Tamil Nadu",
        geojson_name: "Tamil Nadu",
        idx: 23,
        center: [78.65, 11.12],
        importance: "High",
    },
    {
        id: "TG",
        name: "Telangana",
        geojson_name: "Telangana",
        idx: 24,
        center: [79.01, 18.11],
        importance: "High",
    },
    {
        id: "TR",
        name: "Tripura",
        geojson_name: "Tripura",
        idx: 25,
        center: [91.98, 23.94],
        importance: "Low",
    },
    {
        id: "UP",
        name: "Uttar Pradesh",
        geojson_name: "Uttar Pradesh",
        idx: 26,
        center: [80.94, 26.84],
        importance: "High",
    },
    {
        id: "UT",
        name: "Uttarakhand",
        geojson_name: "Uttarakhand",
        idx: 27,
        center: [79.06, 30.06],
        importance: "Medium",
    },
    {
        id: "WB",
        name: "West Bengal",
        geojson_name: "West Bengal",
        idx: 28,
        center: [87.85, 22.98],
        importance: "High",
    },
    {
        id: "DL",
        name: "Delhi",
        geojson_name: "NCT of Delhi",
        idx: 29,
        center: [77.1, 28.7],
        importance: "High",
    },
    {
        id: "LA",
        name: "Ladakh",
        geojson_name: "Ladakh",
        idx: 30,
        center: [77.57, 34.15],
        importance: "Low",
    },
];

export const CITIES = [
    { name: "Mumbai", state_id: "MH", coords: [72.87, 19.07], value: 100 },
    { name: "Pune", state_id: "MH", coords: [73.85, 18.52], value: 80 },
    { name: "Nagpur", state_id: "MH", coords: [79.08, 21.14], value: 60 },
    { name: "Delhi", state_id: "DL", coords: [77.1, 28.7], value: 95 },
    { name: "Bengaluru", state_id: "KA", coords: [77.59, 12.97], value: 90 },
    { name: "Gurugram", state_id: "HR", coords: [77.0266, 28.4595], value: 85 },
    { name: "Faridabad", state_id: "HR", coords: [77.3178, 28.4089], value: 75 },
    { name: "Mysore", state_id: "KA", coords: [76.63, 12.29], value: 50 },
    { name: "Chennai", state_id: "TN", coords: [80.27, 13.08], value: 85 },
    { name: "Coimbatore", state_id: "TN", coords: [76.95, 11.01], value: 60 },
    { name: "Hyderabad", state_id: "TG", coords: [78.48, 17.38], value: 88 },
    { name: "Warangal", state_id: "TG", coords: [79.59, 17.96], value: 40 },
    { name: "Kolkata", state_id: "WB", coords: [88.36, 22.57], value: 82 },
    { name: "Asansol", state_id: "WB", coords: [86.95, 23.67], value: 45 },
    { name: "Lucknow", state_id: "UP", coords: [80.94, 26.84], value: 75 },
    { name: "Kanpur", state_id: "UP", coords: [80.33, 26.44], value: 70 },
    { name: "Varanasi", state_id: "UP", coords: [82.97, 25.31], value: 65 },
    { name: "Jaipur", state_id: "RJ", coords: [75.78, 26.91], value: 78 },
    { name: "Udaipur", state_id: "RJ", coords: [73.71, 24.58], value: 55 },
    { name: "Chandigarh", state_id: "PB", coords: [76.77, 30.73], value: 72 },
    { name: "Ludhiana", state_id: "PB", coords: [75.85, 30.9], value: 68 },
    { name: "Ahmedabad", state_id: "GJ", coords: [72.57, 23.02], value: 84 },
    { name: "Surat", state_id: "GJ", coords: [72.83, 21.17], value: 76 },
    { name: "Bhopal", state_id: "MP", coords: [77.41, 23.25], value: 70 },
    { name: "Indore", state_id: "MP", coords: [75.85, 22.71], value: 74 },
    { name: "Patna", state_id: "BR", coords: [85.13, 25.59], value: 65 },
    { name: "Gaya", state_id: "BR", coords: [84.99, 24.79], value: 40 },
    { name: "Ranchi", state_id: "JH", coords: [85.3, 23.34], value: 60 },
    { name: "Jamshedpur", state_id: "JH", coords: [86.2, 22.8], value: 58 },
    { name: "Raipur", state_id: "CT", coords: [81.62, 21.25], value: 55 },
    { name: "Bhilai", state_id: "CT", coords: [81.38, 21.19], value: 50 },
    { name: "Bhubaneswar", state_id: "OD", coords: [85.82, 20.29], value: 62 },
    { name: "Cuttack", state_id: "OD", coords: [85.87, 20.46], value: 58 },
    { name: "Guwahati", state_id: "AS", coords: [91.73, 26.14], value: 66 },
    { name: "Dibrugarh", state_id: "AS", coords: [94.91, 27.47], value: 45 },
];
